### ISSUE TITLE
full WASI support

### ISSUE THREAD

**Issue by mathetake** [tetratelabs/wazero#10]
https://github.com/mathetake/gasm/tree/master/wasi

**Comment by Carnageous** [comment]
Hi, could you explain what you mean with "full"? Is there a roadmap of what needs to be implemented to consider this as WASI compatible (Like network access, filesystem...)?

**Comment by mathetake** [comment]
@Carnageous I just meant implementing `as many host functions as possible` so I won't have any road map or something like that. Any contribution is welcome 🥇

**Comment by codefromthecrypt** [comment]
we've stubbed all the snapshot01 functions and mentioned what course to take further. basically it is on-demand to do more, as snapshot01 is dead and snapshot02 will be different and incompatible https://github.com/tetratelabs/wazero#webassembly-system-interface-wasi
