### ISSUE TITLE
Unsafe assignment when sharing a cache across multiple runtimes

### ISSUE THREAD

**Issue by pkwarren** [tetratelabs/wazero#1020]
**Describe the bug**
There appears to be a potential race condition here: https://github.com/tetratelabs/wazero/blob/3fc5392570de4715e3c8d844879017efdad7a0b2/runtime.go#L119-L121

Since the eng is lazily instantiated, if multiple goroutines call `NewRuntimeWithConfig` with an uninitialized cache, it appears that multiple engines could be created/assigned and potentially not cleaned up properly.

**To Reproduce**
Haven't written a test to reproduce - just noticed via code inspection.

**Expected behavior**
If a cache shared by multiple runtimes are assumed to share a single engine, it should be assigned with proper locking to ensure no race conditions or memory leaks can occur.

**Screenshots**
n/a

**Environment (please complete the relevant information):**
- Go version: 1.19.4
- wazero Version: 3fc5392570de4715e3c8d844879017efdad7a0b2
- Host architecture: arm64
- Runtime mode: compiler

**Additional context**
n/a

**Comment by mathetake** [comment]
@pkwarren thank you for raising this, actually it is a race and here's a fix #1021. But I'm just curious how did you notice this? Did you just run the tests with `-race` in this repo or using the new cache object already in your project?
