### ISSUE TITLE
WASI execution exception and program hangs

### ISSUE THREAD

**Issue by Dreamacro** [tetratelabs/wazero#1025]
**Describe the bug**
I tried to update to the latest version (v1.0.0-pre.7.0.20230111032309-2df84c679c86) and something went wrong.

Using Quickjs wasi to run benchmark results in an exception and the program hangs on the benchmark.

The version before the update was v0.0.0-20220601012402-e0e9e27326d3

**To Reproduce**
runtime with wazero
```go
package main

import (
	"context"
	_ "embed"
	"log"
	"os"

	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/imports/wasi_snapshot_preview1"
)

//go:embed zigjs.wasm
var zigjsWasm []byte

func main() {
	ctx := context.Background()

	r := wazero.NewRuntime(ctx)
	defer r.Close(ctx)

	wasi_snapshot_preview1.MustInstantiate(ctx, r)

	code, err := r.CompileModule(ctx, zigjsWasm)
	if err != nil {
		log.Panicln(err)
	}

	pwd, err := os.Getwd()
	if err != nil {
		log.Panicln(err)
	}

	config := wazero.NewModuleConfig().WithStdout(os.Stdout).WithFS(os.DirFS(pwd))

	_, err = r.InstantiateModule(ctx, code, config.WithArgs("wasi", os.Args[1]))
	if err != nil {
		log.Panicln(err)
	}
}
```

[zigjs.wasm.zip](https://github.com/tetratelabs/wazero/files/10401516/zigjs.wasm.zip) is a quickjs wasi build with zig

**Expected behavior**
Output the same value similar to wasmtime, which is impossible 20x fast more than wasmtime 🙊

**Screenshots**

wazero output
```
$ ./qjs-runtime ./quickjs-2021-03-27/tests/bench-v8/combined.js
PROGRESS Richards
RESULT Richards 3530
PROGRESS DeltaBlue
RESULT DeltaBlue 6612
## hang on
```

wasmtime output
```
./wasmtime run --dir=. zigjs.wasm ./quickjs-2021-03-27/tests/bench-v8/combined.js
PROGRESS Richards
RESULT Richards 159
PROGRESS DeltaBlue
RESULT DeltaBlue 189
PROGRESS Encrypt
PROGRESS Decrypt
RESULT Crypto 121
PROGRESS RayTrace
RESULT RayTrace 352
PROGRESS Earley
PROGRESS Boyer
RESULT EarleyBoyer 449
PROGRESS RegExp
RESULT RegExp 61.4
PROGRESS Splay
RESULT Splay 767
PROGRESS NavierStokes
RESULT NavierStokes 202
SCORE 220
undefine
```

**Environment (please complete the relevant information):**
- Go version: 1.19.5
- wazero Version: v1.0.0-pre.7.0.20230111032309-2df84c679c86
- Host architecture: amd64/arm64
- Runtime mode: compiler

**Additional context**
quickjs benchmark test code https://bellard.org/quickjs/quickjs-extras-2021-03-27.tar.xz

**Comment by mathetake** [comment]
Could you try using `wazero` command which is installable via `go install github.com/tetratelabs/wazero@main`. I can see the same result as in wasmtime with the main branch of wazero:

```
$ uname -ms
Darwin arm64

$ wazero run --mount $(pwd):/ zigjs.wasm ./quickjs-2021-03-27/tests/bench-v8/combined.js
PROGRESS Richards
RESULT Richards 205
PROGRESS DeltaBlue
RESULT DeltaBlue 200
PROGRESS Encrypt
PROGRESS Decrypt
RESULT Crypto 197
PROGRESS RayTrace
RESULT RayTrace 161
PROGRESS Earley
PROGRESS Boyer
RESULT EarleyBoyer 306
PROGRESS RegExp
RESULT RegExp 45.7
PROGRESS Splay
RESULT Splay 463
PROGRESS NavierStokes
RESULT NavierStokes 346
SCORE 203
undefine
```

**Comment by mathetake** [comment]
Also confirmed with linux/amd64:
```
$ uname -ms
Linux x86_64

$ wazero run --mount $(pwd):/ zigjs.wasm ./quickjs-2021-03-27/tests/bench-v8/combined.js
PROGRESS Richards
RESULT Richards 138
PROGRESS DeltaBlue
RESULT DeltaBlue 161
PROGRESS Encrypt
PROGRESS Decrypt
RESULT Crypto 137
PROGRESS RayTrace
RESULT RayTrace 196
PROGRESS Earley
PROGRESS Boyer
RESULT EarleyBoyer 327
PROGRESS RegExp
RESULT RegExp 51.1
PROGRESS Splay
RESULT Splay 431
PROGRESS NavierStokes
RESULT NavierStokes 245
SCORE 179
undefine
```

**Comment by mathetake** [comment]
Having said that, this might be something to do with the file system related (diff between the impl ^ and wazero cmd): cc @codefromthecrypt

**Comment by Dreamacro** [comment]
@mathetake Yes, I get normal results with wazero cli, but why do I get strange results when I use wazero as a library?

**Comment by codefromthecrypt** [comment]
the mount logic is changing shortly, so let's re-test that after. I'm polishing it for review today

**Comment by codefromthecrypt** [comment]
ps the magic CLI arg to see what's going on is `-hostlogging=filesystem`

**Comment by mathetake** [comment]
@Dreamacro  so the problem in your code is that you haven't configured the clock, which is necessary syscall for accurate benchmarks:

```
 cat diff.patch 
diff --git a/main.go b/main.go
index da379b0..3d8f7b9 100644
--- a/main.go
+++ b/main.go
@@ -31,7 +31,7 @@ func main() {
                log.Panicln(err)
        }
 
-       config := wazero.NewModuleConfig().WithStdout(os.Stdout).WithFS(os.DirFS(pwd))
+       config := wazero.NewModuleConfig().WithStdout(os.Stdout).WithSysWalltime().WithFS(os.DirFS(pwd))
 
        _, err = r.InstantiateModule(ctx, code, config.WithArgs("wasi", os.Args[1]))
        if err != nil {
```

this is the fix your code and will make this work as expected. closing.

**Comment by Dreamacro** [comment]
@mathetake thanks, it works.

I noticed that the cli is using these ModuleConfig options:

https://github.com/tetratelabs/wazero/blob/29ebe82d2d56447cb27b2ffa1a6f0a0332e0fc72/cmd/wazero/wazero.go#L215-L223

So I'm confused that what usage does ModuleConfig not use `WithSysWalltime`?

**Comment by codefromthecrypt** [comment]
@Dreamacro smart contracts prefer code to always execute the same speed, so remove things that can affect that, such as real clocks or RNG. Also some security scenarios prefer to not leak the underlying host resources. How this helps!

**Comment by Dreamacro** [comment]
@codefromthecrypt Thanks for the answer, got it 👍
