### ISSUE TITLE
Complete Tinygo os package support for WASI

### ISSUE THREAD

**Issue by achille-roussel** [tetratelabs/wazero#1044]
Currently, tinygo lacks implementations in the `os` package when building with `-target wasi` to be able to run the `fstest.TestFS` test suite for implementations such as `os.DirFS`. This issue is intended to track the changes required to address these limitations and allow running tinygo programs with full support for file system capabilities in Wazero.

At this time, we know of the following steps to address the issue:

- [ ] https://github.com/tinygo-org/tinygo/pull/3370
- [ ] https://github.com/tinygo-org/tinygo/pull/3381
- [ ] implement `os.(*File).ReadDir`
  - https://github.com/tinygo-org/tinygo/issues/3087)
  - https://github.com/achille-roussel/tinygo/pull/1
- [ ] implement `os.(*File).WriteAt`
  - https://github.com/achille-roussel/tinygo/pull/2
- [ ] implement `os.(*File).Sync`
  - https://github.com/achille-roussel/tinygo/pull/3
- [ ] implement `os.(*File).Truncate`
  - https://github.com/achille-roussel/tinygo/pull/4
- [ ] implement `os.Chtimes`
  - https://github.com/achille-roussel/tinygo/pull/5

**Comment by codefromthecrypt** [comment]
maybe a nag sweep is in order (ping issues and/or slack if any of ^^ can land). @achille-roussel do you mind being the naggy?

**Comment by achille-roussel** [comment]
Looks like the bug that I attempted to fix with https://github.com/tinygo-org/tinygo/pull/3381 does not trigger with Go 1.20 (the problem code is gone), so I think we'll be able to make progress again on this issue.

**Comment by mathetake** [comment]
Can we close this as there's no action item in wazero repo?

**Comment by codefromthecrypt** [comment]
fair enough. Thanks for raising the issues @achille-roussel! we can still see status from your links even if this is closed.
