### ISSUE TITLE
Can a WASM module access host memory directly?

### ISSUE THREAD

**Issue by ncruces** [tetratelabs/wazero#1050]
I expect the answer to the above question to be a hard no, but still thought I'd ask.
Thanks!

----

Also, to get [XY problem](https://xyproblem.info/) out of the way, this is what I'm trying to do.

I'm exploring [Go bindings to SQLite using `wazero`](https://github.com/ncruces/go-sqlite3).
And… I'm mostly finished with the easy bits.

I got `:memory:` databases working; used [`test_demovfs.c`](https://www.sqlite.org/src/doc/trunk/src/test_demovfs.c) with WASI for file databases; and ported it to Go for much improved performance.

The hard bit is concurrency, especially cross process concurrency. If I don't do this right (compatibly with other SQLite implementations) and you access databases concurrently, you will corrupt data.

To do concurrency right, I need file locking (which is hard to do portably, but should raise no `wazero` issues).

And this the motivation for this issue: to use WAL mode concurrently, I need to [`mmap` memory](https://www.sqlite.org/wal.html#implementation_of_shared_memory_for_the_wal_index). But to do `mmap` portably, I can't decide the address of mapped memory. Go [`mmap`](https://pkg.go.dev/golang.org/x/sys/unix#Mmap) returns a new `[]byte`.

**Comment by ncruces** [comment]
Sorry to spam the issue tracker. Feel free to close as off-topic.

File locking is nearly done, so I'm _close_ to an MVP that doesn't risk corrupting databases left and right.

Concurrency is achieved by launching a new SQLite `api.Module` for every “database connection,” and relying on the “file locking” that SQLite uses to synchronize between processes to _also_ synchronize between `api.Module`s.

This works (I can access the same database file concurrently from multiple Go routines), but the level of concurrency is _limited_. SQLite quickly complains that the database is locked and gives up. This is expected.

The solution for this in SQLite world is to “use WAL mode,” but this requires shared memory (between `api.Module`s in the same process, and ideally between processes). This doesn't seem feasible. There are proposals for shared memory (and `mmap`), but they're a long way out.

The next best way to achieve some concurrency is threading, which might also be a non-starter.

But, on that topic, and if it's not too much to ask, do we know how `wazero` interacts with goroutines/threads? How bad is it to call exported functions of the same `api.Module` from multiple goroutines? If the `wazero` side of it is “safe” SQLite allows one to provide synchronization primitives externally (which could be implemented in Go).

**Comment by ncruces** [comment]
Concretely, this quote [from](https://wazero.io/languages/#concurrency)  is almost _encouraging_:
_”Concretely, if using wazero, a Wasm function call remains on the calling goroutine until it completes.”_

I say this, because many other pitfalls are _avoidable_ (I can provide my own synchronization primitives). My worry is more in the vein of what happens if one call forces memory to grow?

**Comment by mathetake** [comment]
yep, the only concern is `memory.grow` and `table.grow` (which I assume SQLitght is not using), and other than that it is ok to use multiple functions from the same api.Module withe proper locking in the host as they have completely separate call stacks.

**Comment by mathetake** [comment]
on safate wrt `memory.grow`, you can use https://github.com/tetratelabs/wazero/blob/main/config.go#L65-L69

**Comment by ncruces** [comment]
That's actually not a bad idea. SQLite can be configured [never to `malloc`](https://www.sqlite.org/malloc.html#memsys5). Using a large buffer (they mention _"few dozen megabytes"_, it's easy to provide more) that might do. Next challenge, reentrant mutexes. Fun stuff. I wish I had more time.

Thanks for your guidance @mathetake! `wazero` has been great to work with.

**Comment by mathetake** [comment]
actually this conversation with you @ncruces brought me to the solution of the current flake with gojs https://github.com/tetratelabs/wazero/pull/1063 where I set the memory max in the binary with `WithMemoryCapacityFromMax` enabled, and then the flake has gone (concurrent access to single api.Module is actually feasible with proper design of host functions).

**Comment by ncruces** [comment]
I'm glad this “helped” @mathetake. I'm still not 100% that functions have _“have completely separate call stacks.”_.

I mean, WASM doesn't allow pointers to stack, so how does `alloca` work? Seems it used to be a (presumably shared?) [global](http://troubles.md/the-stack-is-not-the-stack/), _aka._ not goroutine safe.

SQLite can be configured to avoid `alloca`, but I'm sure it probably uses (emulated) pointers to stack in other ways.

**Comment by mathetake** [comment]
oh I meant the callstack of wazero's Engine implementations, not the Wasm's stack. And yeah on second though, you are actually right about the stack usage - any C code or LLVM based language maintains the "stack" in the linear memory and the pointer as a global variable of Wasm, and that is definitely not thread safe, therefore it's totally impossible to execute concurrently. (gojs is different - they maintain their in-linear-memory stack separately per execution). so tldr is that even though it's safe to execute api.Function from one module concurrently from the host Go app pointer of view, the practical applications are not safe for it.

**Comment by ncruces** [comment]
As a followup (if anyone finds themselves here): in general C functions are not safe to call concurrently from multiple goroutines, and likely can ***not*** be made safe. There are exceptions to this rule, however, and they can be useful.

At this point in time (early 2023) WASM C binaries compiled with `clang` have a C stack that grows _down_ from `addr = STACK_SIZE` (blowing up if you reach zero); the heap starts from `STACK_SIZE`. The current `$__stack_pointer` is a global variable. You can't have multiple goroutines sharing this resource.

But not all functions use the C stack. You can disassemble your WASM to WAT figure out if a function needs it.

Here's an example of a function that ***does use*** the C stack (gets 16 bytes of stack, returns them at the end):
```wat
(func $sqlite3_str_appendf (;67;) (type 2) (param i32 i32 i32)
  (local i32)
  global.get $__stack_pointer
  i32.const 16
  i32.sub
  local.tee 3
  global.set $__stack_pointer
  local.get 3
  local.get 2
  i32.store offset=12
  local.get 0
  local.get 1
  local.get 2
  call $sqlite3_str_vappendf
  local.get 3
  i32.const 16
  i32.add
  global.set $__stack_pointer
)
```

Here's an example of a function that ***does not use*** the C stack (need to inspect the entire call tree):
```wat
(func $__wasm_call_dtors (;48;) (type 4))
(func $sqlite3_interrupt (;1229;) (type 1) (param i32)
  local.get 0
  i32.const 1
  i32.store offset=288
)
(func $sqlite3_interrupt.command_export (;1538;) (type 1) (param i32)
  local.get 0
  call $sqlite3_interrupt
  call $__wasm_call_dtors
)
(export "sqlite3_interrupt" (func $sqlite3_interrupt.command_export))
```

The exported `sqlite3_interrupt` only calls functions that never touch the `$__stack_pointer`, so it's safe to call from concurrently from any goroutine.

And this is a _very_ interesting function to call from a 2nd goroutine: it sets a flag that interrupts a long running operation on the 1st goroutine.
