### ISSUE TITLE
Wazero Embedded

### ISSUE THREAD

**Issue by jordan-rash** [tetratelabs/wazero#1065]
**Is your feature request related to a problem? Please describe.**
I have started working on building a [wasmCloud](github.com/wasmcloud/wasmcloud) host on top of Wazero with the ultimate goal of using it for the embedded use-case (on something like a Pico).  This would ultimately mean building Wazero with Tinygo.

**Describe the solution you'd like**
At this point, just to test the waters, I have tried building `cmd/wazero` with `GOOS=linux GOARCH=amd64 tinygo build` (tinygo 26).  This throws single error
```
# github.com/tetratelabs/wazero/internal/wasmdebug
../../internal/wasmdebug/debug.go:117:9: PrintStack not declared by package debug
```

Using the `-target=pico` throws more syscall type errors.

I don't expect this to work at this time.  I am just hoping to start a discussion on whether or not this is something Wazero would like to support eventually (given appropriate TinyGo support)

**Describe alternatives you've considered**
I haven't given any other alternatives consideration at this time as the pure go Wazero solution is something I would really like to utilize

**Comment by mathetake** [comment]
as discussed in slack, this is not an issue of wazero, but tinygo's, so closing!
