### ISSUE TITLE
wasi: openFlags() handles flags exclusive

### ISSUE THREAD

**Issue by ktye** [tetratelabs/wazero#1068]
In [openFlags()](https://github.com/tetratelabs/wazero/blob/main/imports/wasi_snapshot_preview1/fs.go#L1373),
if both `trunc` and `creat` are given, only `creat` is applied and existing files are not truncated:

```go
	if oflags&O_TRUNC != 0 {
		openFlags = os.O_RDWR | os.O_TRUNC
	}
	if oflags&O_CREAT != 0 {
		openFlags = os.O_RDWR | os.O_CREATE
	}
	if fdflags&FD_APPEND != 0 {
		openFlags = os.O_RDWR | os.O_APPEND
	}
```
I assume it was ment to be `openFlags |= ..`

**Environment (please complete the relevant information):**
- Go version: [1.19.1]
- wazero Version: [d57bdecadbe577e1e6a112342b688826c7023f80]
- Host architecture: [amd64]
- Runtime mode: [cmd/wazero]

**Comment by codefromthecrypt** [comment]
embarrassing. sorry! https://github.com/tetratelabs/wazero/pull/1069
