### ISSUE TITLE
Reconsider ExitError wrapping

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#1081]
Right now, we don't wrap ExitError, to avoid clutter in logs on an intentional exit. For example, we don't need to see the stack trace from main who is exiting normally. Recently, zig started to call `proc_exit` after abort, instead of unreachable. So what happens now, is we don't see the stack trace due to our avoiding wrapping the exit error. I'm not sure what the best path to take here is, but for now it is left as don't wrap.

See https://github.com/tetratelabs/wazero/pull/1080

**Comment by mathetake** [comment]
https://github.com/tetratelabs/wazero/compare/wrapaerrr?expand=1

how about this? This will output like this:
```
 wazero run ./zig-out/bin/main.wasm   
reached unreachable code
wasm stack trace:
        wasi_snapshot_preview1.proc_exit(i32)
        .os.exit(i32)
                0x329: /Users/mathetake/zig-macos-aarch64-0.11.0-dev.1499+23b7d2889/lib/std/os.zig:616:23
        .os.abort()
                0x1b9: /Users/mathetake/zig-macos-aarch64-0.11.0-dev.1499+23b7d2889/lib/std/os.zig:553:13
        .builtin.default_panic(i32,i32,i32,i32)
                0x86: /Users/mathetake/zig-macos-aarch64-0.11.0-dev.1499+23b7d2889/lib/std/builtin.zig:863:25
        .main.main() i32
                0x25: /Users/mathetake/wazero/internal/testing/dwarftestdata/testdata/zig/main.zig:10:5 (inlined)
                      /Users/mathetake/wazero/internal/testing/dwarftestdata/testdata/zig/main.zig:6:5 (inlined)
                      /Users/mathetake/wazero/internal/testing/dwarftestdata/testdata/zig/main.zig:2:5
        ._start()
                0x1c5: /Users/mathetake/zig-macos-aarch64-0.11.0-dev.1499+23b7d2889/lib/std/start.zig:616:37 (inlined)
                       /Users/mathetake/zig-macos-aarch64-0.11.0-dev.1499+23b7d2889/lib/std/start.zig:240:42

```

**Comment by codefromthecrypt** [comment]
I think what happened was I had to change `exe.setTarget(CrossTarget{ .cpu_arch = .wasm32, .os_tag = .freestanding });` from wasi to freestanding due to the behavior change. I think mainly we don't want a stack trace if exit is called, though I feel I should have put a before/after in this issue when raising!

**Comment by mathetake** [comment]
The output above is for `.os_tag = .wasi` and the current output is like this (no trace, just a message):
```
$ wazero run ./zig-out/bin/main.wasm   
reached unreachable code
```
