### ISSUE TITLE
Add example to instantiate  Wasm instances concurrently on single `wazero.Runtime`

### ISSUE THREAD

**Issue by stffabi** [tetratelabs/wazero#1103]
Unfortunately I was unable to find any information for thread safety guarantees of the engine. 

Is it safe to use a single engine from multiple go routines under the assumption that all called wasm modules are thread-safe itself? E.g. every go routine has it's own distinct module that it's execting.

Thanks for any information about this topic and for this really awesome project 🙏 .

**Comment by stffabi** [comment]
Oh sorry, I've mistakenly created a bug report and can't remove the label. Sorry for that...

**Comment by mathetake** [comment]
>  every go routine has it's own distinct module that it's expecting.

yes, this is safe. Note that we don't have a jergon `Engine` in the API, but instead `wazero.Runtime` (conceptually equal though).

We indeed owe the example of how to use a single `wazero.Runtime` to instantiate multiple instances per Goroutine concurrently to showcase the exact use case of yours @stffabi.

**Comment by mathetake** [comment]
changed the title for adding example on this!

**Comment by stffabi** [comment]
Awesome, thanks so much for clarifying that.

**Comment by mathetake** [comment]
there you go https://github.com/tetratelabs/wazero/pull/1107
