### ISSUE TITLE
Allow to pass ModuleConfig to InstantiateModuleFromBinary 

### ISSUE THREAD

**Issue by stffabi** [tetratelabs/wazero#1105]
**Is your feature request related to a problem? Please describe.**
When instantiating a module directly from binary it's not possible to pass a `ModuleConfig`, for example to use a custom FS for the module.

**Describe the solution you'd like**
A possibility to use `InstantiateModuleFromBinary` with a custom `ModuleConfig`

**Describe alternatives you've considered**
It's possible to do this with calling first a `CompileModule` and `InstantiateModule`. But since there's a all in one function it would also be awesome if the `ModuleConfig` could be used there.

**Comment by codefromthecrypt** [comment]
We used to have this and we removed it to be conscious of the size of the public API and the number of similar methods in it. That said, ModuleConfig is how you pass things like filesystem config and breaking that into separate steps is likely a first timer pain vs a feature. Happy to add it back.

**Comment by codefromthecrypt** [comment]
https://github.com/tetratelabs/wazero/pull/1129

**Comment by stffabi** [comment]
Awesome, thanks so much for this.
