### ISSUE TITLE
Make wazero buildable on any GOOS/GOARCH

### ISSUE THREAD

**Issue by mathetake** [tetratelabs/wazero#1106]
**Describe the bug**
Even though it should be possible to run interpreter mode on any platform, currently some parts of our codes are not as portable as it's supposed to do. For example,

```
$ GOOS=illumos GOARCH=amd64 go build ./...
# github.com/tetratelabs/wazero/internal/platform
internal/platform/open_file.go:14:24: undefined: syscall.O_DIRECTORY
```

This should succeed.

**To Reproduce**

```bash
go tool dist list -json | jq -r '.[] | "\(.GOARCH) \(.GOOS)"'| xargs -n2 bash -c 'GOARCH=$0 GOOS=$1 go build -v ./...'
```

**Expected behavior**

```bash
go tool dist list -json | jq -r '.[] | "\(.GOARCH) \(.GOOS)"'| xargs -n2 bash -c 'GOARCH=$0 GOOS=$1 go build -v ./...'
```

succeed without any error.

**Additional context**

After this, we should run the unittests and spectests on as much platforms as possible

**Comment by codefromthecrypt** [comment]
thanks a lot cc @achille-roussel

**Comment by codefromthecrypt** [comment]
I was thinking about that os.DirFS should probably fall back to `os` package somehow, but we're only recently complete covering the functions we need. could be a good time to go back and audit this.

**Comment by codefromthecrypt** [comment]
@achille-roussel wasn't so much a ping from fault reply more a ping of interest ;) I was teasing takeshi about how/if we could brute force or randomize testing all platforms go supports, so yeah your ideas are in line with that. Meanwhile, as he tagged it help wanted I suppose any fixes you can find would be welcome!

**Comment by mathetake** [comment]
FWIW the first-class targets are fine 

```
$ go tool dist list -json | jq -r '.[] | select( .FirstClass == true )| "\(.GOARCH) \(.GOOS)"'| xargs -n2 bash -c 'GOARCH=$0 GOOS=$1 go build  ./...'

$ echo $?
0
```

and this is not only about the fs, but the 99% errros are  the CGo-related stuff (as you can see by executing the oneliner I pasted): 

```
$ go tool dist list -json | jq -r '.[] | "\(.GOARCH) \(.GOOS)"'| xargs -n2 bash -c 'GOARCH=$0 GOOS=$1 go build -v ./...' 2>&1 | head
# github.com/tetratelabs/wazero/examples/import-go
loadinternal: cannot find runtime/cgo
/usr/local/go/pkg/tool/darwin_arm64/link: running clang failed: exit status 1
clang: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
ld: unknown/unsupported architecture name for: -arch armv4t
clang: error: linker command failed with exit code 1 (use -v to see invocation)

# github.com/tetratelabs/wazero/examples/allocation/zig
loadinternal: cannot find runtime/cgo
/usr/local/go/pkg/tool/darwin_arm64/link: running clang failed: exit status 1
```

**Comment by codefromthecrypt** [comment]
> So I have to ask, what's your stance on [golang.org/x/sys/unix](https://pkg.go.dev/golang.org/x/sys/unix) and [golang.org/x/sys/windows](https://pkg.go.dev/golang.org/x/sys/windows)?

wazero has a no dependencies so we've been spot-supporting things in our internal platform package, which isn't well organized yet. It is a goal to have the filesystem pluggable and at that point a more portable low-level one could happen where it can't now (because the apis are internal)

**Comment by ncruces** [comment]
Then I assume the fix for this specific case is simply to use an internal `const` that's `syscall.O_DIRECTORY` everywhere and `0x1000000` on `illumos`/`solaris` ([source](https://github.com/illumos/illumos-gate/blob/master/usr/src/uts/common/sys/fcntl.h#L90)).

I just tried @mathetake's command and could build `wazero` for all other platforms (I had some errors, but I think they were on my own code).

**Comment by codefromthecrypt** [comment]
thanks for the tip! I can get this in before 1.0

**Comment by mathetake** [comment]
@ncruces thanks for the help!
