### ISSUE TITLE
Encoding and decoding code section questions.

### ISSUE THREAD

**Issue by 1046102779** [tetratelabs/wazero#1127]
## Demo
WebAssembly Code Section payload: `byte_count|2|0x7E 1|0x7F`  => `0x7E 0x7E 0x7F` => `int32, int32, int64`

## Decode Code Section

```golang
wasm.Code[0].LocalTypes={int32, int32, int64}
```
## Encode Code Section

```golang
WebAssembly Code Section byte_count|1|0x7F|2|0x7E
```

## Inconsistent for decode and encode code section

I found that EncodeCode `vec(locals)` is a reverse process, not a forward process like Decode.

At first I thought it might be a dependency between local variables.
for example:
```golang
var a int32 = 1;
var b int32= a+1;
```

So it may be reversed, and it must be in order, instead of using a map mapping like `map[ValueType]int64`. When I saw the `decodeCodeSection` process, I found that the result list is not the reverse process of `result[vs-i-1]=c`, so I think the codec of the code section is inconsistent.

## Expected

encode code section code:
```shell
WebAssembly Code Section byte_count|2|0x7E|1|0x7F
```
## Code Section Implement
https://github.com/tetratelabs/wazero/blob/main/internal/wasm/binary/section.go#L173
```golang
func decodeCodeSection(r *bytes.Reader) ([]*wasm.Code, error) {
        ......

	result := make([]*wasm.Code, vs)
	for i := uint32(0); i < vs; i++ {
		c, err := decodeCode(r, codeSectionStart)
		if err != nil {
			return nil, fmt.Errorf("read %d-th code segment: %v", i, err)
		}
		result[i] = c
	}
	return result, nil
}

```

https://github.com/tetratelabs/wazero/blob/main/internal/wasm/binary/code.go#L102
```golang
func encodeCode(c *wasm.Code) []byte {
        ......
	localBlockCount := uint32(0) // how many blocks of locals with the same type (types can repeat!)
	var localBlocks []byte
	localTypeLen := len(c.LocalTypes)
	if localTypeLen > 0 {
		i := localTypeLen - 1
		var runCount uint32              // count of the same type
		var lastValueType wasm.ValueType // initialize to an invalid type 0

		// iterate backwards so it is easier to size prefix
		for ; i >= 0; i-- {
			vt := c.LocalTypes[i]
	                ...
		}
		localBlocks = append(leb128.EncodeUint32(runCount), localBlocks...)
                ......
	}
        ......
	return append(leb128.EncodeUint32(uint32(len(code))), code...)
}
```

**Comment by mathetake** [comment]
Sorry could you tell us whats the specific problem you are having with Encoding? It's encoding is only used in testing of wazero, and not for users.

**Comment by 1046102779** [comment]
Why does the bytecode store local variables sequentially when decoding, but store local variables in reverse when encoding? There seems to be an inconsistency here.

**Comment by mathetake** [comment]
no, if you closely look at the code, it''s not reverse encoding, and consistent. https://github.com/tetratelabs/wazero/blob/main/internal/wasm/binary/code.go#L109

**Comment by mathetake** [comment]
FYI as I said, encoding is not used in the main code of wazero and nothing to see for wazero users. If you are interested in binary encoding and stuff, see https://github.com/tetratelabs/wabin for examole.

**Comment by 1046102779** [comment]
Thanks. @mathetake
