### ISSUE TITLE
real world app example?

### ISSUE THREAD

**Issue by ultperf** [tetratelabs/wazero#1136]
anything with a real world app like this?
https://github.com/jetli/rust-yew-realworld-example-app

any tutorials on how to perform simple json api call fetch etc using wazero?

**Comment by mathetake** [comment]
could you elaborate on what kind of example specifically you want here? I have no idea how wazero relates to the repository you linked.

**Comment by mathetake** [comment]
Wazero is not for Web App, and it’s Wasm rune time that can be embedded in Go applications as you can see in README
