### ISSUE TITLE
Is uint32 overflow in uint32-accepting function arguments by design?

### ISSUE THREAD

**Issue by cube2222** [tetratelabs/wazero#1196]
Hey! Me again. Not sure if this one's a bug, or just non-obvious expected / undefined behaviour.

**Describe the bug**
When registering a Go function that accepts only ValueTypeI32s, I sometimes start getting a value `x` that overflows an uint32, such that `uint32(x)` is the correct value. So for example instead of the correct 49998 I'll get 4295017294.

**To Reproduce**
Code is here: https://github.com/cube2222/wasmsql/tree/minimal-reproduce

Short description: toy compiler that compiles nodes and expressions to wasm. It appends them to an existing WASM file that was compiled to from Rust. The main.go file in the linked file just ranges from 1 to 50000 and outputs it all to a Go buffer. It does that by first allocating a single page of memory, and then calling a flush function repeatedly, as the buffer gets full.

Steps to run: `go run . 2> test.txt`

Interesting notes:
- There's a debug host function that gets two arguments, prints them both, and returns the second one. It's what's used to demonstrate the problem.
- The code reads a file the rustlib/rustlib.wasm file, adds an "execute" function to it along with a few imports, then writes that to test.wasm, and executes it.
- There's a test.wat file in the root you can take a look at, relevant function is $execute
- main.go:140 you can find the debug function definition
- it's emitted in output.go:69; it prints the value of `i`, the range's output, in a loop.

**Expected behavior**
In the test.txt file you should get `debug incorrect 42 i` and `debug correct 42 i`where i ranges from 1 to 49999. What you'll find is debug incorrect having the second argument flipped right away, and the first argument (42) also flipping at some point, fairly randomly.

Using the interpreter instead of the compiler works correctly.

**Environment (please complete the relevant information):**
- Go version: go1.19
- wazero Version: v1.0.0-rc.1
- Host architecture: arm64 M2 MacBook
- Runtime mode: works correctly on interpreter, incorrectly on compiler

**Additional context**
As mentioned, I'm not actually sure if this is a bug or non-obvious "expected behaviour". Just casting all the function arguments from uint64 to uint32 works. It's still weird I'm getting values bigger than uint32 if the function is defined as accepting i32s.

**Comment by mathetake** [comment]
yes, this is by design the upper 32bits are arbitrary and you are recommended to always cast it to 32-bit variant. See https://github.com/tetratelabs/wazero/blob/main/api/wasm.go#L319-L320

**Comment by cube2222** [comment]
Alright, thanks for the quick response!
