### ISSUE TITLE
Module closure notification 

### ISSUE THREAD

**Issue by ncruces** [tetratelabs/wazero#1197]
Is there an idiomatic way to get notified of module closure (e.g. a `panic`, or WASI `proc_exit`)?

My use case is releasing resources (closing a file) when the module crashes. I could check the return value of every function call but im wondering if there's a better way.

On a related note, and I haven't tested it yet, does WASI close files when the module closes? I'd consider it a bug if not (but haven't read the specs on it), and looking over the code I couldn't find anything ensuring `FSContext.Close` gets called.

**Comment by codefromthecrypt** [comment]
right now, the only thing that shows you if something exited is in the experimental logger, which has LogScopeExit. This logs that the function was called, but it isn't about the fact that the underlying module was closed.

To know a module was closed even when not from a function (ex. defer closing it), we'd need a non-function hook like #1150

In any case, files are closed when the module is (syscontext does this or we'd have windows errors galore)

**Comment by ncruces** [comment]
If I understood your second point correctly, this gets called *always* when the module closes:
https://github.com/tetratelabs/wazero/blob/a9b3301862be7bb33f8123898c84c63242f9e596/internal/wasm/call_context.go#L165-L181

I guess my RFE, if it makes sense, would be to be able to inject something like `CodeCloser` in there.

Unfortunately, I open my own files, from Go, not just because WASI overhead was considerable, but because I need file locking.

As for your first suggestion, it seems the idiomatic way (if this was not an experimental API) would be to follow this [example](https://pkg.go.dev/github.com/tetratelabs/wazero@v1.0.0-rc.1/experimental#example-package-CustomListenerFactory), and check for errors on `After`.

I wonder what's the overhead of doing that, vs. wrapping all calls in my own function, which I think I'm already doing (mostly for ergonomic reasons).

Thanks, as always!

**Comment by codefromthecrypt** [comment]
> I guess my RFE, if it makes sense, would be to be able to inject something like CodeCloser in there.

I think this plumbing will be similar in nature to the request around a memory.grow hook. Basically the scope is *anything*, so it will get notified twice for folks using WASI, once for explicit close inside `proc_exit` and an implicit redundant close due to a `defer rt.Close(ctx)`, unless we choose to not notify after closed.

> I wonder what's the overhead of doing that, vs. wrapping all calls in my own function, which I think I'm already doing (mostly for ergonomic reasons).

IMHO the main plus on interceptors is decoupling vs performance of self-rolled, basically that you can make instrumentation code and have it hook in, and hook in on code you can't control.

> Thanks, as always!

Thanks for the feedback and let us know how your thoughts progress. We'll likely revisit this after 1.0, as interceptors aren't intended to be permanently experimental :)

**Comment by codefromthecrypt** [comment]
oh, so your main use case is to close module-scope resources, am I right?

If so, we have this in other places as well. Sometime soon after 1.0, we'll make a thing in hostmodulebuilder to allow hooks when a module is instantiated (allocate something on instantiate which is closed on close). This is needed for adding new types of sys calls, as some have different types of resources that should be module scoped (e.g. if someone wants to play with pre-opened sockets). cc @achille-roussel @Pryz

**Comment by codefromthecrypt** [comment]
I know things change over time, so asking again for that reason. Does knowing if a module exited helped (#1573) or do we still need to expose a notification hook?

**Comment by codefromthecrypt** [comment]
from @ncruces we should still pursue this

> As Clifton, I'm solved with a wrapper, but there's still stuff I need to (or should) close as soon as the module exits for any reason and it'd make it easier:
> * like WASI I need to close file handles
> * I now also have generic handles (for callbacks, Go memory the WASM should force alive, etc) which could be GCed with the module, but were I special case io.Close to allow users to themselves open files or connections in there.

**Comment by ncruces** [comment]
This would still be useful for the same reason `ensureResourcesClosed` still exists internally.

https://github.com/tetratelabs/wazero/blob/15fa5c4de50b628a3b979956e01184ecde9ee286/internal/wasm/module_instance.go#L143

This can be solved with a wrapper, though, and we can decide not to expose it.

**Comment by codefromthecrypt** [comment]
PTAL https://github.com/tetratelabs/wazero/pull/1574
