### ISSUE TITLE
Executing a Function from another Module 

### ISSUE THREAD

**Issue by tafseer-khan** [tetratelabs/wazero#1211]
Executing a host function from a function called from another module returns a pointer to original module. Memory address referenced from the other module is not accessible, as the pointer is from the original module.

```go
//go:wasm-module host
//export printModuleName()
func printModuleName()


//export function1
func function1() {
	printModuleName()
}
```

```go
//go:wasm-module module1
//export function1
func function1()

func function2() {
	function1()
}
```

```go
func printModuleName(ctx, module) error {
	fmt.Println(module.Name())
}

````

calling function2 from module1
```go
module2.ExportedFunction("function2").Call()
```

prints

```
module2
```

Thus memory addressed in module1 are not accessible from function1 being called by function2. 

Not sure if this is intended or not.

**Comment by mathetake** [comment]
That's how the Wasm specification is defined.

**Comment by tafseer-khan** [comment]
@mathetake That will break any host function call from Module1 in the example, including WASI.
```go
fmt.Println("Hello")
```
Does not work

**Comment by mathetake** [comment]
no, problem is you're importing essentially not "host functions" but rather Wasm functions. Host Functions will have access to the callers memory and that's how it works.

**Comment by mathetake** [comment]
"any imported Wasm function only has access to its own sandbox" is another way to describe it. In your case, "module2" NEVER has access to the memory of "module1", and module1, which calls the host function, passes its own memory, not module2's. Host functions are only have context of very its callers. That's universal design and implementation detail for any available Wasm runtime.

**Comment by tafseer-khan** [comment]
I know of this. However what I'm describing goes against it.

Host -> Mod2.Func2 -> Mod1.Func1 -> Host.printModuleName(ctx, module) { module == Mod2, basically gives Mod1 access to Mod2 memory through the Host function }

For example if printModuleName was doing something like;
```go
func printModuleName(ctx context.Context, mod api.Module) error {
  mod.Memory().Write(SomeRandomBytes)
}
```

**Comment by mathetake** [comment]
oh? you said in the description it's printing `module1`, no?

**Comment by codefromthecrypt** [comment]
I think this might be easier to describe as a unit test? humans aren't perfect compilers ;)

the jist of it doesn't seem to require tinygo, as it seems simple enough to describe in text format. https://github.com/tetratelabs/wazero/blob/main/internal/integration_test/engine/adhoc_test.go

**Comment by mathetake** [comment]
actually I'm working on it (adding unittest)

**Comment by tafseer-khan** [comment]
> oh? you said in the description it's printing `module1`, no?

Oops, that was a mistype on my part.

**Comment by mathetake** [comment]
ok thanks @tafseer-khan looks like there's a bug introduced at some point, and we haven't covered in the unit test. Thank you for your patience and reporting!

**Comment by mathetake** [comment]
fyi: memory was passed safely, just that module names etc accidentally became the original callers (this case module2)

**Comment by tafseer-khan** [comment]
Thanks for taking the time to look into this.
