### ISSUE TITLE
Is there document about how to encode instr to bytes?

### ISSUE THREAD

**Issue by jiaohu** [tetratelabs/wazero#1219]
I have read the code below. However I can not get why you encode the instr in this way., For I want to add other instrs such as `ADC`.

For example, there is a `ADD` instr. And I could only know the first byte with sfops `0b10001011`, and other bytes I have no idea.
<img width="1023" alt="image" src="https://user-images.githubusercontent.com/13608671/224298764-78bd3e1a-9c2c-4142-9f8a-0b367c926b32.png">

  
```golang
func (a *AssemblerImpl) encodeRegisterToRegister(n *nodeImpl) (err error) {
	switch inst := n.instruction; inst {
	case ADD, ADDW, SUB:
		if err = checkRegisterToRegisterType(n.srcReg, n.dstReg, true, true); err != nil {
			return
		}

		// https://developer.arm.com/documentation/ddi0596/2021-12/Index-by-Encoding/Data-Processing----Register?lang=en#addsub_shift
		var sfops byte
		switch inst {
		case ADD:
			sfops = 0b100
		case ADDW:
		case SUB:
			sfops = 0b110
		}

		srcRegBits, dstRegBits := registerBits(n.srcReg), registerBits(n.dstReg)
		a.Buf.Write([]byte{
			(dstRegBits << 5) | dstRegBits,
			dstRegBits >> 3,
			srcRegBits,
			(sfops << 5) | 0b01011,
		})
...
}
```

**Comment by mathetake** [comment]
> I have read the code below. However I can not get why you encode the instr in this way., For I want to add other instrs such as ADC.


why do you want to add `ADC`?

**Comment by mathetake** [comment]
ok I see in any way this is a question on how to read aarch64 doc, and nothing relevant to wazero. Closing.

**Comment by mathetake** [comment]
Unfortunately, we don't have any documentation, but in short speaking of the snippet you pasted, we just encode it shift=0 on ADD, ADDW, SUB. And for shifted registers, we have different func `encodeLeftShiftedRegisterToRegister`.

Note that our assembler is in no way a complete impl, but only supports instructions used in our initial compiler.

**Comment by jiaohu** [comment]
Ok, still thanks.
