### ISSUE TITLE
sfops encoded disaccord to the document

### ISSUE THREAD

**Issue by jiaohu** [tetratelabs/wazero#1250]
https://github.com/tetratelabs/wazero/blob/5d8d8d05de13e41b8c52f42788cce3c7250bcd27/internal/asm/arm64/impl.go#L911

When I read the code, I find that the `sfops` of `ADDW` not  obey the [document](https://developer.arm.com/documentation/ddi0596/2021-12/Index-by-Encoding/Data-Processing----Register?lang=en#addsub_shift) in `encodeRegisterToRegister`.  **Is there any explain about this?**

<img width="845" alt="image" src="https://user-images.githubusercontent.com/13608671/225825831-420682fc-1bad-47f0-aacb-08d841c48c5d.png">

**Comment by codefromthecrypt** [comment]
ps if you like to chat about things, probably better to use gophers slack instead of issues. here's a link with instructions https://wazero.io/community/#keeping-up-to-date
