### ISSUE TITLE
How can I use wazero to instantiate WebAssembly.Memory

### ISSUE THREAD

**Issue by boli2017** [tetratelabs/wazero#1308]
jscode：
`init: function() {
            var e;
            window.WebAssembly && window.fetch && (e = {
                env: {
                    memory: new WebAssembly.Memory({
                        initial: 2
                    }),
                    abort: function() {}
                }
            },
            fetch("/static/wasm/enc.wasm").then((function(e) {
                return e.arrayBuffer()
            }
            )).then((function(t) {
                return WebAssembly.instantiate(t, e)
            }
            )).then((function(e) {
                h = e
            }
            )))
        }`

some code in wat file:
`(module
  (func $env.abort (;0;) (import "env" "abort") (param i32 i32 i32 i32))
  (memory $env.memory (;0;) (export "memory") (import "env" "memory") 1)`

I use `	_, err = r.NewHostModuleBuilder("env").
		NewFunctionBuilder().
		WithFunc(func(a, b, c, d uint32) {
			return
		}).
		Export("abort").
		NewFunctionBuilder().
		WithFunc(func() {
			return
		}).
		Export("memory").
		Instantiate(ctx)
	if err != nil {
		panic(err)
	}`
it run with "panic: export "memory" in module "env" is a func, not a memory"
How can I deal with it, help me, thanks!

**Comment by mathetake** [comment]
duplicate question to https://github.com/tetratelabs/wazero/issues/1059#issuecomment-1402342596
