### ISSUE TITLE
Support epoll on stdin

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#1317]
I thought we fixed this, but must have missed a spot. If you remove [nonBlockReader](https://github.com/ktock/container2wasm/blob/main/tests/wazero/main.go#L59) from container2wasm's wazero runner. Tests fail. Let's see what implementation is needed to get things together.

See https://github.com/ktock/container2wasm/pull/28#discussion_r1152863786

cc @evacchi @ncruces @ktock

**Comment by ktock** [comment]
Reproducer from https://github.com/ktock/container2wasm/pull/28#discussion_r1152941780


sample c program:

```c
#include <stdio.h>
#include <unistd.h>
#include <sys/select.h>

int main(int argc, char **argv)
{
  char buf[5];
  int len = 5, ret;
  fd_set rfds;
  struct timeval tv;

  FD_ZERO(&rfds);
  FD_SET(0, &rfds);

  tv.tv_sec = 3;
  tv.tv_usec = 0;
  printf("waiting for 3s for inputs...\n");
  ret = select(1, &rfds, NULL, NULL, &tv);
  if ((ret > 0) && FD_ISSET(0, &rfds)) {
    ret = read(0, buf, len);
    if (ret > 0) {
      printf("got %.*s (first 5 chars)\n", ret, buf);
    }
  } else {
    printf("no input\n");
  }
}
```

wazero code:

```go
package main

import (
	"context"
	"os"

	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/imports/wasi_snapshot_preview1"
)

func main() {
	ctx := context.Background()
	c, err := os.ReadFile(os.Args[1])
	if err != nil {
		panic(err)
	}
	r := wazero.NewRuntime(ctx)
	defer func() {
		r.Close(ctx)
	}()
	wasi_snapshot_preview1.MustInstantiate(ctx, r)
	compiled, err := r.CompileModule(ctx, c)
	if err != nil {
		panic(err)
	}
	_, err = r.InstantiateModule(ctx, compiled, wazero.NewModuleConfig().WithStdout(os.Stdout).WithStderr(os.Stderr).WithStdin(os.Stdin))
	if err != nil {
		panic(err)
	}
	return
}
```

wasm file is built using wasi-sdk 19.0: [out.tar.gz](https://github.com/ktock/container2wasm/files/11109627/out.tar.gz)

```
clang --sysroot=${WASI_SDK_PATH}/share/wasi-sysroot -o /out.wasm /main.c
```

On host, it works properly. It waits for inputs for 3s and prints the input string.

```console
$ gcc main.c && ./a.out
waiting for inputs...
hi
got hi
 (first 5 chars)
```

On wazero, `select()` doesn't wait nor detect for input and returns immediately.

```console
$ go run main.go ./out/out.wasm
waiting for inputs...
no input
```

**Comment by mathetake** [comment]
@evacchi wanna take a shot while I'm working on #1342 ? 😎

**Comment by evacchi** [comment]
looking into this!

**Comment by evacchi** [comment]
also notable:

```
❯ echo a | wazero run main.wasm
waiting for inputs...
got a
 (first 5 chars)
```

however, `got a` gets printed _after_ the timeout. This is probably because of the `nanosleep()` in clock handling, while the  data should take priority in that case. Of course without the timeout the data from stdin is read correctly if it's a pipe, but it returns immediately if it's a tty.

**Comment by mathetake** [comment]
FWIW, to use the sleeping etc correctly, you are recommended to configure sys wall and sleep functions properly as below, otherwise things could go wrong:

```diff
 diff main.go main_fixed.go 
26c26
<       _, err = r.InstantiateModule(ctx, compiled, wazero.NewModuleConfig().WithStdout(os.Stdout).WithStderr(os.Stderr).WithStdin(os.Stdin))
---
>       _, err = r.InstantiateModule(ctx, compiled, wazero.NewModuleConfig().WithStdout(os.Stdout).WithStderr(os.Stderr).WithStdin(os.Stdin).WithSysWalltime().WithSysNanotime().WithSysNanosleep())

```

**Comment by evacchi** [comment]
@ktock I think this draft PR should improve over the status quo https://github.com/tetratelabs/wazero/pull/1346

**Comment by ktock** [comment]
Thanks, left some comments on that PR.
