### ISSUE TITLE
Initialize memory from limit (with WithMemoryLimitPages + WithMemoryCapacityFromMax)

### ISSUE THREAD

**Issue by inkeliz** [tetratelabs/wazero#1330]
**Is your feature request related to a problem? Please describe.**
I would like to prevent re-allocation, so I tried to use `WithMemoryLimitPages(256).WithMemoryCapacityFromMax(true)`, in that
case it would allocate 256 pages and never change.

However, that is not what happens. Since the WASM-module is not defining `max memory`, the `WithMemoryCapacityFromMax(true)` is useless.

**Describe the solution you'd like**
Maybe exposing the memory, in general, so we can provide any custom Memory implementation, or provide more option to avoid re-allocation.

**Describe alternatives you've considered**
I tried `WithMemoryLimitPages(255).WithMemoryCapacityFromMax(true)`, but it doesn't allocates 255 ahead-of-time.

**Comment by mathetake** [comment]
https://github.com/tetratelabs/wazero/pull/1335
