### ISSUE TITLE
How to execute a specified function in a wasm file using cli

### ISSUE THREAD

**Issue by orangeC23** [tetratelabs/wazero#1347]
Run the command `./bin/wazero run --help`, however, there aren't any args for executing a specified function.

**Comment by codefromthecrypt** [comment]
we currently don't support arbitrary function invocation. Can you mention an example of what you are trying to invoke? Most of the time we find people are invoking toy applications like calculators, so it will help to know a more realistic use of this feature.

**Comment by gedw99** [comment]
Hey 

https://github.com/bots-garden/capsule can do what you want @orangeC23 

it’s one of the many projects using Wazero ..
