### ISSUE TITLE
cli exits with 0 on trap

### ISSUE THREAD

**Issue by yamt** [tetratelabs/wazero#1360]
**Describe the bug**
wazero cli exits with 0 on trap.

it's more common for wasm runtime cli to use non-zero exit code.
cf. https://github.com/yamt/toywasm/blob/f56b5efe8b945a4938baf7802da242f37727264f/wat/trap.wat#L3-L9

**To Reproduce**
```
spacetanuki% curl -O -L https://raw.githubusercontent.com/yamt/toywasm/master/wat/trap.wat
<snip>
spacetanuki% wat2wasm trap.wat
spacetanuki% wazero run trap.wasm
spacetanuki% echo $?
0
spacetanuki% 
```

**Expected behavior**
non-zero exit code.

**Screenshots**

**Environment (please complete the relevant information):**
- Go version: i don't remember
- wazero Version: v1.0.0-pre.9
- Host architecture: amd64
- Runtime mode: interpreter and compiler

**Additional context**

**Comment by codefromthecrypt** [comment]
can you verify this with v1.0.0? Indeed unreachable should cause some error

**Comment by mathetake** [comment]
yeah upgrading to v.1.0.1 solved this.
