### ISSUE TITLE
compiler: perform BuiltinFunctionCheckExitCode natively

### ISSUE THREAD

**Issue by mathetake** [tetratelabs/wazero#1409]
wazeroir's [BuiltinFunctionCheckExitCode operation](https://github.com/tetratelabs/wazero/blob/main/internal/wazeroir/operations.go#L714-L715) has been introduced in the context cancelation integration in #1108. Basically, this operation is supposed to perform the check on `ModuleInstance.Closed` value, and exit the execution if the value is not zero.

Currently, the compiler's implementation is pretty naive like simply exiting the native world and call `ModuleInstance.FailIfClosed`.
https://github.com/tetratelabs/wazero/blob/86444c67a37dbf9e693ae5b365901f64968d9025/internal/engine/compiler/impl_amd64.go#L271-L272

https://github.com/tetratelabs/wazero/blob/86444c67a37dbf9e693ae5b365901f64968d9025/internal/engine/compiler/engine.go#L1012-L1016

but this comes with the cost - `BuiltinFunctionCheckExitCode` is [inserted at all of the `loop` instructions](https://github.com/tetratelabs/wazero/blob/86444c67a37dbf9e693ae5b365901f64968d9025/internal/wazeroir/compiler.go#L475) and each time we call a Go function. `FailIfClosed` function checks the exit code atomically, but it is not necessary as in anyway the implementation is not synchronous (e.g. we don't check the code until the Wasm VM reaches loop instruction even when the context reaches timeout 10 years ago in extreme case).

Given that assumption we do not need to check it synchronously, we could optimize the translation of `BuiltinFunctionCheckExitCode` by simply checking the exit code natively. 

The proposed change should come with 
- Native check of `ExitCode` in `compiler.compileBuiltinFunctionCheckExitCode` function for both arm64 and amd64
    - native code has access to it via `callEngine.moduleInstance`
- The benchmark on the cost of context cancelation integration

**Comment by mathetake** [comment]
@evacchi could you take on after #1406

**Comment by evacchi** [comment]
Nice!👍

**Comment by evacchi** [comment]
If I understand correctly this boils down to `c.compileExitFromNativeCode(exitCode)` when `exitCode` is nonzero; where `exitCode` is extracted from `(*moduleInstance).Closed` (`closed >> 32`); `Closed` is at the address `callEngineModuleContextModuleInstanceOffset` because it is at offset `0` of the struct

**Comment by mathetake** [comment]
no, you misunderstood `compileExitFromNativeCode(exitCode)`. That is compile time function and it accepts `nativeCallStatusCode` which is different from "exitCode" stored at ModuleInstance. See the existing code base on how it works.

**Comment by mathetake** [comment]
ps the new benchmark's case should look like `for i := 0; i < 10000; i++ {}` in wat where basically execute the many loop in-Wasm so that we can see the cost of each loop header without being offset by the other noises

**Comment by mathetake** [comment]
Ok, I just realized that this is in theory impossible - if we does this check completely in "native world", then Goroutine switch doesn't happen and therefore the ExitCode might not get updated forever (See [compiler/RATIONALE.md](https://github.com/tetratelabs/wazero/blob/main/internal/engine/compiler/RATIONALE.md#why-its-safe-to-execute-runtime-generated-machine-codes-against-async-goroutine-preemption).

That's why @evacchi is experiencing the forever-hung whatever change you make when t.Parallel was enabled in the tests in #1413.

With that said, I am closing this as not planned. Thanks @evacchi  for your investigation and try!
