### ISSUE TITLE
Trying to use Dear ImGui compiled to wasm

### ISSUE THREAD

**Issue by the-goodies** [tetratelabs/wazero#1415]
I'm trying to get [Dear ImGui](https://github.com/ocornut/imgui) compiled to wasm and integrate it with wazero. Here's how I compile Dear ImGui:
```em++ main.cpp imgui.cpp imgui_draw.cpp imgui_tables.cpp imgui_widgets.cpp -s EXPORT_ALL=1 -s LINKABLE=1 -s STANDALONE_WASM -o imgui.wasm``` where `main.cpp` is just `int main() { return 0; } `, otherwise it doesn't compile.

Next, I try to use compiled `imgui.wasm` from Go like this:

```go
package main

import (
	"context"
	_ "embed"
	"fmt"

	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/imports/emscripten"
)

//go:embed imgui.wasm
var imgui []byte

func main() {
	ctx := context.Background()
	r := wazero.NewRuntime(ctx)
	defer r.Close(ctx)

	emscripten.MustInstantiate(ctx, r)

	mod, err := r.Instantiate(ctx, imgui)
	if err != nil {
		panic(fmt.Sprintf("failed to instantiate module: %v", err))
	}

	fmt.Printf("%+v\n", mod.ExportedFunctionDefinitions())
}
```

Upon running, it panics after Instantiate function call:
`panic: failed to instantiate module: "emscripten_glGenQueriesEXT" is not exported in module "env"`

So I'm not sure, whether it's wazero fault, or I have not properly compiled ImGui to wasm or it's something else entirely. Do I have to export this **emscripten_glGenQueriesEXT** function from Go? **glGenQueriesEXT** seems to be some OpenGL function and it's nowhere to be found in Dear ImGui because it doesn't use any OpenGL.

**Environment:**
- Go version: 1.20
- wazero Version: v1.0.3
- Host architecture: Windows10; amd64

**Comment by ncruces** [comment]
> Do I have to export this emscripten_glGenQueriesEXT function from Go?

Yes, that's what you'd need to do. Or rather, that's what it's telling you, but maybe not what you want to do.

Anyway. Dear ImGui needs a [backend](https://github.com/ocornut/imgui/tree/master/backends)  to render anything. Which backend do you intend to use?

You can think of it like this. WASM runs in a virtual machine. For the virtual machine to have a (virtual) screen, or a keyboard, you need to provide it. If you want to connect it to your real screen and keyboard, you need to write the glue code.

So if you want to use OpenGL to render Imgui to your real screen, you're going to need to use the GL backend and provide OpenGL functions to the WASM virtual machine that call real OpenGL. You'd write a host module for this, called `env`, and provide functions (like `glGenQueriesEXT`) in it.

That said, I'm not sure if OpenGL is the right choice here.

**Comment by the-goodies** [comment]
> Anyway. Dear ImGui needs a [backend](https://github.com/ocornut/imgui/tree/master/backends) to render anything. Which backend do you intend to use?

Since ImGui is backend agnostic, there's no need to have any backend within **Wasm module** itself, only ImGui is sufficient.
Then I can use GLFW/Win32 from Go host while passing it's input information to **Wasm ImGui** and receive render data back from it, which can be rendered with OpenGL/Directx11 from Go host again.

I'm trying to see if it's possible to use ImGui from Go without CGO:
- ImGui compiled to Wasm using Emscripten - no CGO required
- OpenGL and GLFW - no CGO required on Windows ([Ebitengine](https://github.com/hajimehoshi/ebiten) has implementation without CGO)

Well, that's the goal 😄 Today I managed to correctly compile ImGui to Wasm, without it requiring glGenQueriesExt and similar function imports: 
```
emcc -DIMGUI_USER_CONFIG=\"my_imgui_config.h\" main.cpp cimgui.cpp imgui.cpp imgui_demo.cpp imgui_draw.cpp imgui_tables.cpp imgui_widgets.cpp -o imgui.wasm
```
`cimgui.cpp` is generated using [dear_bindings](https://github.com/dearimgui/dear_bindings), which exports ImGui C API.
`my_imgui_config.h` is an additional ImGui user config file, which makes exported functions from `cimgui.cpp` be actually included and not discarded (previously I used `-s EXPORT_ALL=1 -s LINKABLE=1` for this, but it included way too many unnecessary things, where one of those was glGenQueriesExt import):
```h
#include <emscripten.h>
#define CIMGUI_API EMSCRIPTEN_KEEPALIVE
```

Now onto trying to figure out how to pass and receive complex types: strings, structs, pointers and so on.

**Comment by codefromthecrypt** [comment]
@the-goodies our issues list is used for things that result in changes to the codebase. At this point, I feel this is more support in nature, and grateful @ncruces was able to help provide some guidance. Typically discussions like this happen on the #wazero channel on gophers slack (or other channels like emscripten's). Would it be ok to close this issue and move the chat there? This will keep those watching from seeing trial and error notifications which don't affect this codebase. There are more instructions about how to join here if you like https://wazero.io/community/#keeping-up-to-date

**Comment by ncruces** [comment]
@the-goodies I agree that this is the way. Interesting project. Keep us updated on Slack.

**Comment by the-goodies** [comment]
> Would it be ok to close this issue and move the chat there?

Ok, closing.
