### ISSUE TITLE
complete internal platform.File

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#1417]
This issue tracks completion of the plaform.File type, started in #1290

Generally, this process includes migration off every place we use fs.FS or something cast from `File.File()` to functions on `platform.File`. We'll know we are feature complete when the helper function `platform.File.File()` can be removed. Each function should prefer the same signature (removing path) on `sysfs.FS` and when absent try to balance the signature between an existing "fd" syscall function with practicalities of the call site.

Here are the functions to convert. The function signature on `platform.File` will be different at least errno result.
- [x] `fs.File.Stat() (FileInfo, error)` e.g. for  `fs.fstat` in gojs
  * `Stat() (Stat_t, syscall.Errno)` in #1290
- [x] `fs.File.Close() error` e.g. for  `fs.close` in gojs
  * `Close() syscall.Errno` in #1290
- [x] `Sync() error` e.g. for `fs.fsync` in gojs
  * `Sync() syscall.Errno` in #1426
- [x] `Chmod(fs.FileMode) error` e.g. for `fs.fchmod` in gojs
  * `Chmod(fs.FileMode) syscall.Errno` #1423
- [x] `platform.ChownFile(f fs.File, uid, gid int) syscall.Errno` e.g. for `fs.fchown` in gojs
  * `Chown(uid, gid int) syscall.Errno` #1422
- [x] `Truncate(size int64) error` e.g. for `fs.ftruncate` in gojs
  * `Truncate(int) syscall.Errno` #1417
- [x] `FileDatasync(f fs.File) (err syscall.Errno)` e.g. for `wasi_snapshot_preview1.fd_datasync`
  * `Datasync() syscall.Errno` in #1427
- [x] `io.Reader` e.g. for `fs.read` in gojs; `wasi_snapshot_preview1.fd_read`
  * `read(p []byte) (n int, errno syscall.Errno)` in #1439
- [x] `io.ReaderAt` e.g. for `fs.read` and `pread` in gojs; `wasi_snapshot_preview1.fd_read` and `fd_pread`
- [x] `.(io.Writer)` e.g. to check if a file is writeable without writing
  * `AccessMode() int` in #1438
- [x] `io.Writer` e.g. for `fs.write` in gojs; `wasi_snapshot_preview1.fd_write`
  * `Write(p []byte) (n int, errno syscall.Errno)` in #1438
- [x] `io.WriterAt` e.g. for `fs.write` and `pwrite` in gojs; `wasi_snapshot_preview1.fd_write` and `fd_pwrite`
  * `Pwrite(p []byte, off int64) (n int, errno syscall.Errno)` in #1438
- [x] `io.Seeker` e.g. for `wasi_snapshot_preview1.fd_seek` and `fd_tell`
  * `Seek(offset int64, whence int) (newOffset int64, errno syscall.Errno)` and `IsDir() (bool, syscall.Errno)` in #1441
- [x] `platform.Readdir` e.g. for `wasi_snapshot_preview1.fd_readdir`
  * `Readdir(n int) (dirents []Dirent, errno syscall.Errno)` in #1454
- [x] `FileEntry.ReOpenDir()` e.g. for `wasi_snapshot_preview1.fd_readdir`
  * `Seek(0, SeekStart)` for directories in #1455
- [x] `FileEntry.Inode` e.g. for `wasi_snapshot_preview1.fd_readdir` on dot directories
  * `Ino() (uint64, syscall.Errno)` in #1455
- [x] `platform.UtimensFile` e.g. for `wasi_snapshot_preview1.fd_filestat_set_times`
  * `Utimens(times *[2]syscall.Timespec) syscall.Errno` in #1440
- [x] `Poll(duration time.Duration)`  `platform.Select()`  e.g. for `wasi_snapshot_preview1.fd_poll`
  * `PollRead(timeout *time.Duration) (ready bool, errno syscall.Errno)` in #1447
- [x]  `.(*sys.StdioFileReader)` e.g. for `wasi_snapshot_preview1.fd_fdstat_set_flags`
  * `IsNonblock() bool` in #1447
  * `SetNonblock(enable bool) syscall.Errno` in #1447
- [x] `FileEntry.ChangeOpenFlag` e.g. for `wasi_snapshot_preview1.fd_fdstat_set_flags`
  * `IsAppend() bool` in #1455
  * `SetApend(enable bool) syscall.Errno` in #1455

## Implementation approach

Basically, the functions would be exposed in syscall form (so return errno which collects error mapping inside the File object which helps with for example the windows mapping sprawl etc).

So, things like `chmodFile, ok := f.File.File().(chmodFile)` will be redone so that the Chmod function lives on the File type itself, and the pattern we use for adding functions to `sysfs.FS` is exactly used here, except we have a bonus. The bonus is some functions, such as Chmod are already designed. So, we simply remove the path parameter and know what we are doing.

Others, like `Write` may have some stylistic design depending on which way we go. Practice helps us from wandering on what ifs that aren't relevant to the call sites. Remember, the only purpose of this API is for implementing things like WASI, this isn't for general use.

Here's an example  for Chmod. So we already went through work for this on sysfs.FS, so no need to redo that work. We simply copy/paste and make it coherent. 

For example, sysfs.FS has this (used for path based ops)
```go
	Chmod(path string, perm fs.FileMode) syscall.Errno
```

So, an expected change is to add that to the File type as below and cross-reference the godoc.
```go
	Chmod(perm fs.FileMode) syscall.Errno
```

**Comment by codefromthecrypt** [comment]
https://github.com/tetratelabs/wazero/pull/1422 migrates the signature for Chown

**Comment by codefromthecrypt** [comment]
https://github.com/tetratelabs/wazero/pull/1423 was chmod

**Comment by codefromthecrypt** [comment]
modeling poll won't happen on the platform.File type as it accepts multiple FDs 
https://pubs.opengroup.org/onlinepubs/9699919799/functions/poll.html

The file type is really one for each `f` function which operates only on one file/file descriptor, e.g. `ftruncate`. That said, we may have some supporting function on the file type for polling.

**Comment by achille-roussel** [comment]
Epic! 👏

**Comment by codefromthecrypt** [comment]
https://github.com/tetratelabs/wazero/pull/1455 actually completes this

**Comment by codefromthecrypt** [comment]
FYI I fully audited the translations in the checkboxes above. There is still more work to do before the file types are ready to expose (e.g. see if we can get rid of `File.AccessMode` and `File.Ino`). However, the code is all in one place now, and wasn't before.
