### ISSUE TITLE
TensorFlow Lite Bindings: import func[wasi_snapshot_preview1.fd_seek]: signature mismatch

### ISSUE THREAD

**Issue by clarkmcc** [tetratelabs/wazero#1461]
**Describe the bug**

I don't know if this is a bug or just something that needs a workaround. I'm writing bindings for TensorFlow Lite using [tfjs-backend-wasm-simd.wasm.zip](https://github.com/tetratelabs/wazero/files/11467292/tfjs-backend-wasm-simd.wasm.zip). The problem is that it seems to think that the signature for fd_seek should be all i32
```wat
(type $t10 (func (param i32 i32 i32 i32 i32) (result i32)))
...
(import "wasi_snapshot_preview1" "fd_seek" (func $wasi_snapshot_preview1.fd_seek (type $t10)))
```
But in wazero it is exported as `i32 i64 i32 i32`. Is there any way around this?

**Environment (please complete the relevant information):**
- Go version: [e.g. 1.18.1] go version go1.20.2 darwin/arm64
- wazero Version: [e.g. c815060196bbfaa2d0f66a6ddbe64ba026523944] v1.1.0
- Host architecture: [e.g. amd64] arm64
- Runtime mode: [e.g. interpreter or compiler] compiler

**Comment by achille-roussel** [comment]
Hello @clarkmcc, thanks for reporting!

I believe the signature of `fd_seek` in wazero is correct here: https://github.com/WebAssembly/WASI/blob/main/legacy/preview1/docs.md

- fd is a `i32`
- filedelta is a `i64`
- whence is a `i32`
- the last argument is a pointer to the location where to write the result, so it is a `i32`
- the return value is the error code, which is a `i32`

This looks like a bug in the compiler or standard library that was used to build the wasm module. Would you know how it was compiled?

**Comment by clarkmcc** [comment]
Okay, good to know. I compiled it using Bazel directly from the source. I'm guessing I might be out of luck then? I tried hijacking the wasi module to write my own wrapper, but since the real implementation of fd_seek is private, I wasn't able to go that route.

---

To build from source, follow these steps:

1. Clone the TensorFlow.js repository:

```bash
git clone https://github.com/tensorflow/tfjs.git
```

2. Navigate to the tfjs-backend-wasm directory:

```bash
cd tfjs/tfjs-backend-wasm
```
3. Install dependencies:
```
yarn
```

4. Build the project:
```
yarn build-npm
```
This command will build the WASM binary, JavaScript bindings, and other required files. 

5. Locate the WASM binary:
After the build process is complete, you can find the WASM binary file in the dist/ directory. The file is named tfjs-backend-wasm.wasm.

**Comment by clarkmcc** [comment]
After a quick conversation with ChatGPT it sounds like this might be the explanation.

> In this signature, there are five input parameters and one output:
> 
> - File descriptor (i32)
> - Offset low part (i32)
> - Offset high part (i32)
> - Whence (i32)
> - Resulting offset pointer (i32)
> The function signature indicates that fd_seek uses a 64-bit offset split into two 32-bit parts (low and high). This is likely to maintain compatibility across platforms and browsers that may not fully support 64-bit integers.
> 
> When working with the TensorFlow.js WASM backend, you should use the function signature it expects for compatibility. If you are implementing the fd_seek function or creating bindings for TensorFlow.js, make sure you follow the signature TensorFlow.js expects.
> 
> Keep in mind that TensorFlow.js has a custom implementation of the WASI APIs to ensure compatibility and performance, which may not match the official WASI API exactly.

**Comment by clarkmcc** [comment]
Also probably related to https://github.com/WebAssembly/WASI/issues/54

**Comment by ncruces** [comment]
How about disassembling the WASM into WAT (which you seem to have done already), and wrapping the function there?

**Comment by clarkmcc** [comment]
@ncruces Interesting idea! I have no idea how to do that but I'll figure it out. Thanks!

**Comment by achille-roussel** [comment]
If you use wazero as a library you might be able to change the signature of `fd_seek` using https://pkg.go.dev/github.com/tetratelabs/wazero@v1.1.0/imports/wasi_snapshot_preview1#NewFunctionExporter

That being said, this seems like a bad practice, specifications exist to allow interoperability between systems, TensorFlow shouldn't diverge from it.

**Comment by ncruces** [comment]
The problem with overriding (I gather) is that you're not wrapping, so can't delegate to the old implementation, so it might not help if you can't translate the fd into a file (because we don't expose the fs API).

Wrapping in WASM with some glue would fix this. I'd try to write a similar glue function in C (same signature), compile and disassemble it.

**Comment by clarkmcc** [comment]
@ncruces yeah, that was the challenge I ran into this morning. Adding some glue code to the wat seemed to do the trick! I don't know if this is right, but it compiles at least. It will be a pain to deal with whenever I upgrade the module, but this is a great start. Thanks for pointing me in the right direction!

```wasm
(import "wasi_snapshot_preview1" "fd_seek" (func $wasi_snapshot_preview1.fd_seek (param i32 i64 i32 i32) (result i32)))
(func $fd_seek_wrapper (param $fd i32) (param $offset_low i32) (param $offset_high i32) (param $whence i32) (param $result_offset_ptr i32) (result i32)
  ;; Convert the 64-bit offset from two 32-bit parts to a single 64-bit integer
  (local $offset i64)
  (local.set $offset
    (i64.add
      (i64.extend_i32_u (local.get $offset_low))
      (i64.shl
        (i64.extend_i32_u (local.get $offset_high))
        (i64.const 32)
      )
    )
  )

  ;; Call the wasi_snapshot_preview1 fd_seek function with the converted parameters
  (call $wasi_snapshot_preview1.fd_seek
    (local.get $fd)
    (local.get $offset)
    (local.get $whence)
    (local.get $result_offset_ptr)
  )
)
```

**Comment by achille-roussel** [comment]
Ah you're correct @ncruces, we don't expose a way to access exported functions on the host builder, my bad :)

**Comment by ncruces** [comment]
Glad it helped. The code seems to make sense, not sure if it'll work. Also possible it doesn't even get used at all.
