### ISSUE TITLE
go get deprecation

### ISSUE THREAD

**Issue by hgsbart** [tetratelabs/wazero#1497]
**Describe the bug**
go get is deprecated and not working on latest version.

**To Reproduce**
go install not working on windows x64

**Expected behavior**
go get github.com/tetratelabs/wazero@latest
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.
PS C:\> go install github.com/tetratelabs/wazero@latest
package github.com/tetratelabs/wazero is not a main package

**Screenshots**

**Environment (please complete the relevant information):**
- go version go1.20.4 windows/amd64
- wazero Version: [e.g. c815060196bbfaa2d0f66a6ddbe64ba026523944]
- amd64

**Comment by mathetake** [comment]
sorry this is not a bug but you are literally recommended to do `go install github.com/tetratelabs/wazero@latest` instead of `go get`.

**Comment by hgsbart** [comment]
@mathetake I did that and this is the result "package github.com/tetratelabs/wazero is not a main package"

**Comment by mathetake** [comment]
on second thought you are trying to add the wazero as a library? then please read your error carefully and you will notice that  it's due to your are doing it outside your project (without go module). I would recommend you refer to the Go's official documentation.

**Comment by hgsbart** [comment]
@mathetake ok thank you

**Comment by mathetake** [comment]
in anyway this is not a question about wazero, purely the question about Go toolchain.
