### ISSUE TITLE
go: regression in path/filepath test suite

### ISSUE THREAD

**Issue by achille-roussel** [tetratelabs/wazero#1518]
**Describe the bug**

Running tests for the Go standard `path/filepath` package is failing on wazero v1.2.0+

**To Reproduce**

- clone the Go source code
- from the root directory of the Go source tree, compile Go: `cd src && ./make.bash`
- from the root directory of the Go source tree, run the following command :
```
$ GOWASIRUNTIME=wazero GOROOT=$PWD GOOS=wasip1 GOARCH=wasm PATH=$PWD/misc/wasm:$PATH ./bin/go test ./src/path/filepath
--- FAIL: TestWalkSymlinkRoot (0.00s)
    --- FAIL: TestWalkSymlinkRoot/double_link_with_slash (0.00s)
        path_test.go:916: `/var/folders/qc/zv1mt0j11sscgjygfx47nxlm0000gn/T/TestWalkSymlinkRoot2033040065/001/linklink/`: Lrw-------
        path_test.go:925: Walk(`/var/folders/qc/zv1mt0j11sscgjygfx47nxlm0000gn/T/TestWalkSymlinkRoot2033040065/001/linklink/`) visited [`/var/folders/qc/zv1mt0j11sscgjygfx47nxlm0000gn/T/TestWalkSymlinkRoot2033040065/001/linklink`]; want [`/var/folders/qc/zv1mt0j11sscgjygfx47nxlm0000gn/T/TestWalkSymlinkRoot2033040065/001/linklink` `/var/folders/qc/zv1mt0j11sscgjygfx47nxlm0000gn/T/TestWalkSymlinkRoot2033040065/001/linklink/foo`]
FAIL
FAIL	path/filepath	0.322s
FAIL
```

**Expected behavior**

The test should pass.

**Screenshots**

**Environment (please complete the relevant information):**
- Go version: v1.20.4
- wazero Version: v1.2.0
- Host architecture: darwin/arm64
- Runtime mode: compiler

**Comment by evacchi** [comment]
If I understood correctly, @chriso noted this is a behavioral issue of macOS and [the test is being skipped in the Go codebase unless it runs on Linux](https://github.com/golang/go/blob/9efa625d8425fd97381c80c948689c0eb0f76769/src/path/filepath/path_test.go#L906)

see also https://github.com/golang/go/issues/59586#issuecomment-1507375729

**Comment by evacchi** [comment]
I think we can close this?

**Comment by chriso** [comment]
+1 to closing. We noticed that wasi-go has the same issue on macOS. Based on the discussions in https://github.com/golang/go/issues/59586, we're confident it's an OS bug rather than an issue with the WASI layer.
