### ISSUE TITLE
About the latest release?

### ISSUE THREAD

**Issue by chenrui333** [tetratelabs/wazero#1521]
👋 it looks like 1.2.1 is not marked as latest release, create this issue to confirm if I missed anything. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/133764

**Comment by codefromthecrypt** [comment]
sorry it is the latest release, just I haven't finished writing release notes. I defer clicking latest release until I've done the paperwork :) I'll try to do it faster next time!

**Comment by codefromthecrypt** [comment]
https://github.com/tetratelabs/wazero/releases/tag/v1.2.1

**Comment by chenrui333** [comment]
Thanks!! :)
