### ISSUE TITLE
make names section parser/decoder public

### ISSUE THREAD

**Issue by nilslice** [tetratelabs/wazero#1523]
Hello! I'd like to be able to get a wasm module's decoded names section from Wazero. For all functions in the wasm code, I would like to have the name (if available) and index of the function in a name map or similar (as you already have it in the internal package): 

https://github.com/tetratelabs/wazero/blob/b01ba67fdcf32997d22a0f56b723a71c1c40cd75/internal/wasm/binary/names.go#L30

I understand wanting to keep a minimal public API, and that this being internal lets you control it more flexibly, outside of any releases. However, there aren't many good alternative solutions that I've encountered. This package (https://github.com/akupila/go-wasm) and a fork, are both unmaintained and rather old. I'd like to avoid parsing the module more than once as well, if possible. So using Wazero here in this context would be convenient, especially since it already (?) does this work.

If you're open to this and would prefer to see a contribution made, I'm happy to submit a PR. But I wanted to check first that this wasn't already available through some other means, or that you would be open to making the API public.

**Comment by codefromthecrypt** [comment]
Hi, maybe the separate binary decoding project we spun out isn't easy to find.. can this work for you? https://github.com/tetratelabs/wabin

**Comment by nilslice** [comment]
@codefromthecrypt - thanks! this did not show up in my search, so thanks for sharing. 

This looks like it will work indeed.
