### ISSUE TITLE
Allow FSConfig to have arbitrarily nested mounts

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#1525]
**Is your feature request related to a problem? Please describe.**

Right now, you can mount /dev, but not /dev/net. This was most recently noticed by @Xe

**Describe the solution you'd like**

Mounts should be allowed to overlap, with the last added, most specific win. inodes should make sense when doing stat or readdir.

**Describe alternatives you've considered**

Currently, we just don't allow it. When originally written, the psuedo root directory had a lot of edge cases and this is even more. However, it is solvable if we do very good testing and don't punt inode tests.

**Additional context**

So, for example, if you mount
 * /dev and /dev/net, the directory listing of /dev will include its entries plus net in a consistent order
   * if the mount for /dev already includes net, its stat info will be overridden with the one from /dev/net mount
   * when reading /dev/net in wasip1, where dot dirents are required, ".." is the inode of the /dev mount

* / and /usr/bin,  the directory listing of /usr is a pseudo dir which includes bin
  * in wasi the ".." dirent of /usr/bin goes to the pseudo dir "/usr", and the ".." of /usr to root.

There are also some edge cases to handle around writes. basically make sure no psuedo dir is writable. resolving symlinks may be put out of scope.

**Comment by ncruces** [comment]
This is a can of worms, and not how mounts work (and thus much worse and much more complicated than) on a real file system that allows mounts.

**Comment by codefromthecrypt** [comment]
ps a workaround, not fantastic, is to mount a single-entry directory. This doesn't handle both "/usr" and "/usr/bin", but a lot of times, folks aren't asking to mount both, rather they want to skip making a single-entry "/usr"

A transparent alternative for CLI users is to hide this and do it in main. Make a temp dir and symlink the "/usr/bin"'s host dir into it, then mount that tmp dir as "/usr".

**Comment by ncruces** [comment]
I understand why users would want this, and I'm not saying we shouldn't support it, but we need to be fully aware of the difficulties.

Mounting a filesystem to `/usr/bin` normally requires it to exist as a directory, which we can `mv` but not `rmdir`. Not so here. We'll tie mount-points to paths (not directories) which can simply disappear, become inaccessible, turn out to be files (not directories), all outside our control.

This is more akin to an NFS mount inside another NFS mount, with changes happening concurrently on both servers.

**Comment by codefromthecrypt** [comment]
this is only a wazero issue because we make a composite filesystem to avoid wasi-like behavior. The only reason we make a composite filesystem is to support GOOS=js as its syscall layer is not pre-open based.

here's a thought. knowing go is transitioning to GOOS=wasip1, we can degrade GOOS=js filesystem support to where there is only one mount, root. then, we remove the composite FS entirely and pun the issue to wasi pre-opens which would then deal with the overlap issue.

**Comment by codefromthecrypt** [comment]
I went with https://github.com/tetratelabs/wazero/pull/1536
