### ISSUE TITLE
How to use WithFSConfig to specify read and write permissions that are not accessible under a folder?

### ISSUE THREAD

**Issue by springrain** [tetratelabs/wazero#1532]
How to use WithFSConfig to specify read and write permissions that are not accessible under a folder?
for example, there are /data/read and /data/write under the /data folder, how to achieve /data/read readOnly, /data/write can be written?

**Comment by evacchi** [comment]
I don't think this is currently possible. You are able to mount a directory under the root and then specify rw access to those; e.g. /data_read, /data_write; at the moment it is not possible to mount sub-directories e.g. mount read under /data; it is a feature that has been requested though, so we may add support for it. 

See #1525

**Comment by springrain** [comment]
Mount the /data directory, how to specify read and write permissions to the subdirectories below it?

**Comment by evacchi** [comment]
you can only set rw permissions at the mount level

			config = config.WithReadOnlyDirMount(dir, guestPath)

or 

			config = config.WithDirMount(dir, guestPath)

**Comment by springrain** [comment]
Thank you so much, I'm waiting for the new feature to be able to set subdirectory read and write permissions at the same time

**Comment by codefromthecrypt** [comment]
after https://github.com/tetratelabs/wazero/pull/1536 arbitrary nesting will be allowed (except GOOS=js).

However, I wouldn't suggest to make complex permission schemes via mounts. Other options are to set OS level permissions on the files.

Later when our filesystem API stabilizes, we'll expose it and this will allow you to control access to anything without having us change FSConfig for each sort of configuration.

**Comment by codefromthecrypt** [comment]
https://github.com/tetratelabs/wazero/pull/1605 allows you to do whatever you want, and includes a read-only adapter example.
