### ISSUE TITLE
[question] wazero.NewModuleConfig().withName("permission"), how to get name("permission") in wasm?

### ISSUE THREAD

**Issue by springrain** [tetratelabs/wazero#1540]
wazero.NewModuleConfig().withName("permission"), how to get name("permission") in wasm?

**Comment by codefromthecrypt** [comment]
There is no way to read the custom section data from inside a wasm binary.

PS can you please use gophers slack for questions? I have asked you a few times ai far. The issues list is not a good way to handle questions as it spams watchers.

**Comment by springrain** [comment]
Okay, I'll ask questions later on Gophers Slack
