### ISSUE TITLE
Private API breaks attempts at tracing - alternative approach?

### ISSUE THREAD

**Issue by rossjones** [tetratelabs/wazero#1545]
**Describe the bug**

Recently a commit (https://github.com/tetratelabs/wazero/commit/197facf7a93c4b3cae1af896660b506368201a3d) added an internal/private interface (internalapi.wazeroOnly) to various APIs (api.Function, api.Module).

Over in https://github.com/bacalhau-project/bacalhau/blob/main/pkg/executor/wasm/trace.go we were wrapping these APIs to generate opentelemetry traces of various things during execution.  We are now unable to do this as the interface is in an internal package that we are unable to import. 

**To Reproduce**

This dependabot PR shows the issue 

https://github.com/bacalhau-project/bacalhau/pull/2610 

**Expected behavior**

Is there a recommended (non-experimental) mechanism available for us to obtain opentelemetry traces for things like instantiating/compiling modules, Call etc.

**Environment (please complete the relevant information):**
- Go version: 1.20.5
- wazero Version: 1.2.1
- Host architecture: arm64

**Comment by ncruces** [comment]
Have you tried to replace this:
```go
type tracedRuntime struct {
	delegate wazero.Runtime
}
```

With this:
```go
type tracedRuntime struct {
	wazero.Runtime
}
```

**Comment by rossjones** [comment]
That then introduces infinite recursion when we replace `t.delegate.InstantiateModule` with `t.InstantiateModule`.

```
func (t tracedRuntime) InstantiateModule(
	ctx context.Context,
	compiled wazero.CompiledModule,
	config wazero.ModuleConfig,
) (api.Module, error) {
	ctx, span := system.NewSpan(ctx, system.GetTracer(), "pkg/executor/wasm.tracedRuntime.InstantiateModule")
	defer span.End()
	module, err := telemetry.RecordErrorOnSpanTwo[api.Module](span)(t.InstantiateModule(ctx, compiled, config))
	if err == nil && module != nil {
		if name := module.Name(); name != "" {
			span.SetAttributes(semconv.CodeNamespace(name))
		}
		module = tracedModule{module}
	}
	return module, err
}

```

**Comment by rossjones** [comment]
🤦🏻 
Thank you, that has clearly fixed it. TIL.

**Comment by ncruces** [comment]
Great!

The intent is precisely to allow us to add functionality to these "internal" interfaces without breaking you _and_ your customers in the future.

If we add a method to one of these interfaces, your wrappers will continue working, except they won't wrap that specific method.

This is true even if your creating a library and your downstream users upgrade wazero without your intervention.

**Comment by codefromthecrypt** [comment]
really excellent support @ncruces .. you are a champ!
