### ISSUE TITLE
example basic does not work when add.wasm is built in go1.21rc2 

### ISSUE THREAD

**Issue by bigwhite** [tetratelabs/wazero#1550]
**Describe the bug**

example basic does not work when add.wasm is built in go1.21rc2 . 

the mod.ExportedFunction("add") can not found "add" function.

**To Reproduce**
Description of the host and wasm code that reproduces the behavior.
Smoothest debugging will be if you can share a repository with the
actual code.

```
I use the go1.21rc2. 

// in examples/basic/testdata

GOARCH=wasm GOOS=wasip1 go build -o add.wasm add.go

// in examples/basic

$go run add.go 5 6
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x11877b5]

goroutine 1 [running]:
main.main()
	/Users/tonybai/go/src/github.com/wazero/wazero/examples/basic/add.go:58 +0x295
exit status 2

```

**Expected behavior**
output 11.

**Screenshots**

**Environment (please complete the relevant information):**
- Go version:go 1.21rc2
- wazero Version: v1.2.1
- Host architecture:  amd64/darwin
- Runtime mode:  compiler

**Additional context**

**Comment by achille-roussel** [comment]
Hello @bigwhite 

It would be useful to have access to the source code you used to reproduce the issue, tho I'll attempt to reply based on the information you provided.

This does not appear to be a problem specific to Wazero but rather it is related to Go. There is no mechanism for exporting custom functions in Go 1.21, declaring an `add` function in the Go source does not result in that function being exported in the compiled WebAssembly. Therefore when the lookup of `mod.ExportedFunction("add")` will return `nil` and the attempt to call it will cause a dereference of a null pointer that could trigger the panic you reported.

**Comment by leighmcculloch** [comment]
> it is related to Go. There is no mechanism for exporting custom functions in Go 1.21, declaring an `add` function in the Go source does not result in that function being exported in the compiled WebAssembly

There's a proposal to add support for exporting specific functions, it's here:
- https://github.com/golang/go/issues/42372

**Comment by bigwhite** [comment]
@achille-roussel thanks for your clear reply. I will use tinygo instead of go compiler until it support go:wasmexport directive.
