### ISSUE TITLE
WithFS(fs.FS) directory read returns unexpected results

### ISSUE THREAD

**Issue by GeorgeMac** [tetratelabs/wazero#1553]
> Nice to meet you all. I love this project 👋 

**Describe the bug**

I have found some obscure behaviour when I provide custom implementations of `fs.FS`.
I see inconsistent behaviour when compared with `os.DirFS` instance.
I can see they flow through very different paths in the codebase (I the see adaptor for `fs.FS`).
So I am not surprised there can be differences.

However, if I write a project in Go and compile with go1.21 wasip1 target, I get inconsistent results from reading directory entries when the FS added is not an `os.DirFS`. Only the root `.` entry gets returned.

I have created a minimal reproduction.

**To Reproduce**

Take the following Go code to be compiled to wasm using the `wasip1` target:

```go
package main

import (
	"fmt"
	"io/fs"
	"os"
)

func main() {
	fs.WalkDir(os.DirFS("."), ".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}

		fmt.Println(path, d)

		return nil
	})
}
```

I have this in a local directory called `cmd/walk/main.go` and compile it to `walk.wasm`:

```
GOOS=wasip1 GOARCH=wasm gotip build -o walk.wasm cmd/walk/main.go
```

Now take the following Go program using wazero to invoke it:

```go
package main

import (
	"context"
	"fmt"
	"io/fs"
	"log"
	"os"

	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/imports/wasi_snapshot_preview1"
	"github.com/tetratelabs/wazero/sys"
)

func main() {
	ctx := context.Background()

	r := wazero.NewRuntime(ctx)
	defer r.Close(ctx) // This closes everything this Runtime created.

	config := wazero.NewModuleConfig().
		WithStdout(os.Stdout).WithStderr(os.Stderr).WithFS(FS{os.DirFS(".")})

	wasi_snapshot_preview1.MustInstantiate(ctx, r)

	wasm, err := os.ReadFile(os.Args[1])
	if err != nil {
		log.Panicln(err)
	}

	if _, err = r.InstantiateWithConfig(ctx, wasm, config.WithArgs("wasi")); err != nil {
		if exitErr, ok := err.(*sys.ExitError); ok && exitErr.ExitCode() != 0 {
			fmt.Fprintf(os.Stderr, "exit_code: %d\n", exitErr.ExitCode())
		} else if !ok {
			log.Panicln(err)
		}
	}
}

type FS struct {
	fs fs.FS
}

func (f FS) Open(name string) (fs.File, error) {
	fi, err := f.fs.Open(name)
	if rdf, ok := fi.(fs.ReadDirFile); ok {
		return Dir{rdf}, err
	}

	return File{fi}, err
}

type File struct {
	fs.File
}

type Dir struct {
	fs.ReadDirFile
}
```

**Expected behavior**

To see more than just `.` printed.

When I switch the line called `WithFS(FS{os.DirFS(".")})` to just `WithFS(os.DirFS("."))` I see the entire directories contents printed out.

**Outputs**

```
➜  go run *.go walk.wasm
. d ./
```
> custom `fs.FS` implementation

```
➜  go run *.go walk.wasm
. d ./
.git d .git/
.git/HEAD - HEAD
.git/config - config
.git/description - description
.git/hooks d hooks/
.git/hooks/applypatch-msg.sample - applypatch-msg.sample
.git/hooks/commit-msg.sample - commit-msg.sample
.git/hooks/fsmonitor-watchman.sample - fsmonitor-watchman.sample
.git/hooks/post-update.sample - post-update.sample
.git/hooks/pre-applypatch.sample - pre-applypatch.sample
.git/hooks/pre-commit.sample - pre-commit.sample
.git/hooks/pre-merge-commit.sample - pre-merge-commit.sample
.git/hooks/pre-push.sample - pre-push.sample
.git/hooks/pre-rebase.sample - pre-rebase.sample
.git/hooks/pre-receive.sample - pre-receive.sample
.git/hooks/prepare-commit-msg.sample - prepare-commit-msg.sample
.git/hooks/push-to-checkout.sample - push-to-checkout.sample
.git/hooks/update.sample - update.sample
.git/info d info/
.git/info/exclude - exclude
.git/objects d objects/
.git/objects/info d info/
.git/objects/pack d pack/
.git/refs d refs/
.git/refs/heads d heads/
.git/refs/tags d tags/
cmd d cmd/
cmd/walk d walk/
cmd/walk/main.go - main.go
fs.go - fs.go
go.mod - go.mod
go.sum - go.sum
main.go - main.go
walk.wasm - walk.wasm
```
> using `os.DirFS` implementation

**Environment (please complete the relevant information):**
- Go version: [e.g. 1.20.4] to build wazero and `gotip` to compile the wasm code.
- wazero Version: v1.21.1
- Host architecture: arm (Mac M1)
- Runtime mode: [e.g. interpreter or compiler] (not sure I can tell, can you?)

**Comment by GeorgeMac** [comment]
p.s. The `RATIONALE.md` doc is great. While it is a quite a chunk to process, it make me appreciate the subtle pain in the neck it must be to create a consistent experience between `fs.FS`, `os.DirFS` and keeping abreast of the evolving WASI standard.

I tried litering a bunch of print statements around wazero and my code (I am indeed a print statement debugger) in an attempt to better understand the call paths taking place between using `os.DirFS` and `fs.FS`. I tweaked some things and to no avail. Last thing I noticed were the `fs.FS` file instances all appear to have 0 for their inodes (makes sense `fs.FS` doesn't expose that information), but I wondered if something was depending on those being accurate somewhere else. Maybe that is causing havok 🤷 (insert dog in space I don't know what I am doing meme).

**Comment by GeorgeMac** [comment]
small update: I've actually found my program appears to be exiting in the middle of the program with a `nil` error returned from `InstantiateWithConfig`. My littering of print statements in the `imports/wasi_snapshot_preview1` directory shows that with the `fs.FS` implementation I would be in the middle of printing during `fdReaddirFn` and it just halts and the program exits cleanly.

**Comment by codefromthecrypt** [comment]
Indeed inodes are only supported on real files at the moment, because they require access to the underlying file descriptor, and further magic on windows. You can see we cast to [os.File ](https://github.com/tetratelabs/wazero/blob/c93bbf29fb79b9906e60c28420af865febc9f7e1/internal/sysfs/file.go#L185). This is why your wrapper isn't working the same way.

Also, ack RATIONALE is a bit of a firehose. We are frequently updating it, again [today](https://github.com/tetratelabs/wazero/pull/1549). Main idea has been more about collecting the decisions vs structuring the flow of the document, choosing battles basically.

We're trying hard to get through the hurdles so we can expose a stable file interface, which would make what you are trying to do (wrapping?) far simpler. We need to at least show wasi preview2 will work, and sadly that's still unstable until the fall.

thanks for the updates and bear in mind that gophers slack is a better place to get Q&A. You can get the details [here](https://wazero.io/community/#keeping-up-to-date). If you have anything that needs a change, maybe keep this open. Otherwise, close if you don't mind and we'll see you on slack?

**Comment by codefromthecrypt** [comment]
one last tip is you might consider the [logging interceptor.](https://github.com/tetratelabs/wazero/blob/c93bbf29fb79b9906e60c28420af865febc9f7e1/experimental/logging/log_listener_example_test.go). This won't trace inside your functions, but it will give better context about what GOOS=wasip1 is calling. There are other cool tools out there, too, including [wzprof](https://github.com/stealthrocket/wzprof) which may be helpful. See you

**Comment by GeorgeMac** [comment]
Thanks @codefromthecrypt 🙏 I will come say hey in Slack. and thanks for the logging tip.
Going to try that out 👍

**Comment by GeorgeMac** [comment]
I did some more spelunking and put my findings in Slack, but thought I would re-iterate them here.

It seems that Go's `wasip1` implementation when parsing directory entries, regards `ino == 0` as the entry being absent from the directory:
https://github.com/golang/go/blob/master/src/syscall/dirent.go#L78-L80

When I added bunch of dirty print statements everwhere, the only thing that appeared to differ between the implementations was at the encoded entries into into memory has an ino of 0 when using a custom implementation of `fs.FS`.

Not sure what this means going forwards for `fs.FS` implementations. Could these `ino` values be safely fabricated?

**Comment by GeorgeMac** [comment]
Sorry for many many messages. However, I got this all to work by just setting Ino using an atomic integer.

Now I get directory listings via `fs.FS` implementations.
I will try and tidy things up, I have been working from the latest tagged release, so I am sure things have moved around.
However, I will propose this silly hacky solution and you can consider it. It is probably a bad idea for good reason.

**Comment by codefromthecrypt** [comment]
here's an alternate way out which might satisfy the original issue even if it doesn't help with truly virtual files. https://github.com/tetratelabs/wazero/pull/1558
