### ISSUE TITLE
Support forcing non-zero inodes in Readdir

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#1559]
**Is your feature request related to a problem? Please describe.**

Our tentative fsapi.Dirent type has an inode field, because Go cannot return one in a portable fashion.
* `fs.FileInfo` has no stable means to expose an inode.
* `fs.ReadDirFile` cannot return these for this reason, and `os.File.Readdir` is not encouraged for performance reasons.
* `os.File` can only return inods on certain platforms with `syscall.Stat_t`. Notably this isn't returned on Windows.
* `os.SameFile` uses inodes, but the fields are hidden, so we can't return them.

Due to the above, during a Readdir, we can end up without inodes for windows, or other operating systems. These can be backfilled with lstat in some, but not all cases. This means even after doing a fan out, this could be zero.

In most wasm compilers, this isn't a problem. Those that need the data can backfill with host calls to lstat. For example, dirents returned without inodes are visible in TinyGo, Zig, Rust, and C. In wasi-libc, this is backfilled as needed with host calls to lstat. Specs didn't say much about this topic, until wasip2 (wasi-filesystem)
* wasip2 has the inode as optional, with a note about a possible stat when missing.
* wasip1 didn't indicate whether inode should be there or not.

Go recently began implementing `GOOS=wasp1` and used an old heuristic unlike the other compilers. Instead of doing an lstat fan out, it simply [drops any dirent missing one](https://github.com/golang/go/blob/66cac9e1e4877ac7e66f888b0599a7a4a5787b76/src/os/dir_unix.go#L92-L94). This is a problem for those using `fs.FS` on windows, but not those using our real FS support. It is a show stopper for virtual files until our `fsapi` package is exposed. I personally think this is extreme even if there's some non-wasi related precedent around Linux getdents. @achille-roussel opened https://go-review.googlesource.com/c/go/+/507915 to fix this and hopefully it will.

Regardless of the problem in the pending Go 1.21 release, people may still prefer the backend do something different. For example, they may want to materialize fake inodes on virtualized files to avoid perf impact of an lstat fan-out. They may also want to [mask real inodes](https://github.com/WebAssembly/wasi-filesystem/pull/81) as discussed in wasi-filesystem.

**Describe the solution you'd like**

We should expose fsapi and allow users to control everything including inodes.
 * should have a default in-memory filesystem which reliably handles inodes.
 * users could decide to do anything including things that won't work for everyone, like returning -1
 * users could also drop entries or do anything to manipulate the result of Readdir

**Describe alternatives you've considered**

* add something like FSConfig.StatIno to force a stat fan-out on zero
  * this will fix windows but not virtual fs.File implementations
* add an inode virtualizer for user-provided fs.FS
  * https://github.com/tetratelabs/wazero/pull/1555 started on this
  * it is hard to guess the right impl
* add a tentative function to fs.File users that can return an inode portably until we expose fsapi.
  * returning something like -1 will stop real inode fetching from working on compilers that already do this.
* drop all entries without inodes
  * this will break most users except those who use real filesystems for reasons

**Additional context**

* Lots of stuff in RATIONALE.md
* notes https://github.com/tetratelabs/wazero/pull/1555#issuecomment-1620907197
* fs wrapping issues https://github.com/tetratelabs/wazero/pull/1558

**Comment by codefromthecrypt** [comment]
I will raise a PR tomorrow to expose fsapi.Stat_t experimental instead of blocking this on the while package. This will allow someone to customize extended stat by returning it from fs.FileInfo.Sys.

**Comment by ncruces** [comment]
> I will raise a PR tomorrow to expose fsapi.Stat_t experimental instead of blocking this on the while package. This will allow someone to customize extended stat by returning it from fs.FileInfo.Sys.

From my limited understanding, this seems like a great way to fix this.

**Comment by codefromthecrypt** [comment]
centralizing notes from the last 2 days here https://github.com/tetratelabs/wazero/pull/1560

**Comment by codefromthecrypt** [comment]
opened https://github.com/tetratelabs/wazero/pull/1567 to maybe close this out

**Comment by codefromthecrypt** [comment]
Current approach is to return `info.Sys().(*sys.Stat_t)` from anything wazero uses `fs.FileInfo` from. This includes `Stat` on `fs.File` and `Readdir` on something that might wrap `*os.File`.

Next step is to expose the full filesystem, which is likely to start as an experimental feature of wazero 1.4 (not 1.3)

**Comment by codefromthecrypt** [comment]
Future work will happen in #1013, so closing until now. If folks feel strongly about this issue please re-open or ask!
