### ISSUE TITLE
How to pass structs to Wasm by TinyGo

### ISSUE THREAD

**Issue by carryxyh** [tetratelabs/wazero#1583]
**Describe the bug**
create a function and export it like this:
```
//export print
func print(p *domain.Person) *domain.Person {
	fmt.Println(p.Id)
	fmt.Println(p.Name)
	return p
}
```

**To Reproduce**
```
package domain

type Person struct {
	Id   int64
	Name string
}
```

I modify the example/basic/add.go:
```
func main() {
	// Parse positional arguments.
	flag.Parse()

	// Choose the context to use for function calls.
	ctx := context.Background()

	// Create a new WebAssembly Runtime.
	r := wazero.NewRuntime(ctx)
	defer r.Close(ctx) // This closes everything this Runtime created.

	// Instantiate WASI, which implements host functions needed for TinyGo to
	// implement `panic`.
	wasi_snapshot_preview1.MustInstantiate(ctx, r)

	// Instantiate the guest Wasm into the same runtime. It exports the `add`
	// function, implemented in WebAssembly.
	mod, err := r.Instantiate(ctx, addWasm)
	if err != nil {
		log.Panicf("failed to instantiate module: %v", err)
	}

	// Read two args to add.
	x, y, err := readTwoArgs("1", "2")
	if err != nil {
		log.Panicf("failed to read arguments: %v", err)
	}

	// Call the `add` function and print the results to the console.
	add := mod.ExportedFunction("add")
	results, err := add.Call(ctx, x, y)
	if err != nil {
		log.Panicf("failed to call add: %v", err)
	}

	fmt.Printf("%d + %d = %d\n", x, y, results[0])

	p := mod.ExportedFunction("print")
	person := domain.Person{
		Id:   int64(10),
		Name: "abc",
	}

	ptrPerson := api.EncodeExternref(uintptr(unsafe.Pointer(&person)))
	result, err := p.Call(ctx, ptrPerson)
	fmt.Println(err)
	fmt.Println(result)

	//deRef := api.DecodeExternref(result[0])
	//dePerson := (*domain.Person)(unsafe.Pointer(deRef))
	//fmt.Println(dePerson)
}
```

**Expected behavior**
print the input person's filed, like id and name

**Environment (please complete the relevant information):**
- Go version: [e.g. 1.18.1]
- wazero Version: [master]

**Additional context**
By the way, is there an example to show that how to input a struct and return a struct from wasi's function?

**Comment by carryxyh** [comment]
when called `	result, err := p.Call(ctx, ptrPerson)`, will return a error:
```
wasm error: out of bounds memory access
wasm stack trace:
        .print(i32) i32
                0x24caa: /Users/daemonxiu/github/wazero/examples/basic/testdata/add.go:19:14 (inlined)

```

**Comment by ncruces** [comment]
I think this is a question more appropriate for the wazero users Slack [channel](https://gophers.slack.com/archives/C040AKTNTE0).

In any event, WASM only really supports 32 and 64-bit ints and floats as arguments and return values.

So this is really a TinyGo question about TinyGo's calling convention (which might not even be stable between TinyGo versions).

[Plugin](https://wazero.io/community/users/#general-purpose-plugins) systems/libraries/packages solve this with (un)marshaling structs in both directions.

I don't think there's anything actionable here?

**Comment by carryxyh** [comment]
Thanks for replying.

`[Plugin](https://wazero.io/community/users/#general-purpose-plugins) systems/libraries/packages solve this with (un)marshaling structs in both directions.`

This might give me an answer.

**Comment by ncruces** [comment]
Yeah.

That said, I'd missed this part, I don't think TinyGo uses `externref` yet, so this was definitely not the way:
https://github.com/tinygo-org/tinygo/issues/2702

**Comment by carryxyh** [comment]
Check out the implementation of go-plugin. Now I understand how to use wasm, thank you for the reminder, it is very important. :)
