### ISSUE TITLE
1.3.1 release was not completed?

### ISSUE THREAD

**Issue by chenrui333** [tetratelabs/wazero#1592]
👋 it looks like 1.3.1 release was not completed, i.e. it did not get marked as latest release. Thanks!

relates to https://github.com/Homebrew/homebrew-core/pull/137295

**Comment by mathetake** [comment]
hi @chenrui333, @evacchi is now writing the release note, and we expect we can release it within a day! Thank you for your patience!

**Comment by chenrui333** [comment]
np, thanks for confirming it!

**Comment by evacchi** [comment]
it's published now :) https://github.com/tetratelabs/wazero/releases/tag/v1.3.1

**Comment by chenrui333** [comment]
Thanks folks!
