### ISSUE TITLE
amd64 BrIf incorrect machine code in fallback case

### ISSUE THREAD

**Issue by rockwotj** [tetratelabs/wazero#1595]
**Describe the bug**

I believe the following line contains a bug:

https://github.com/tetratelabs/wazero/blob/6b4328c66e4104f9b0db303d6cf450cde468dc24/internal/engine/compiler/impl_amd64.go#L587C33-L587C33

`test <reg> <reg>` should always set the zero flag to 1, I think you want to compare to an immediate of zero instead. Also I don't know if you want `testq` or `testl`, after validation there should only be a 32bit value on the stack, but I don't know the rest of the compiler details well enough to know if the upper 32 bits of the register will always be cleared so testq is functionally the same as testl

**Comment by rockwotj** [comment]
NVM I'm very wrong, sorry for the noise :)

**Comment by mathetake** [comment]
yeah `test rn, rm` sets ZF flag if and only if `rn & rm = 0`
