### ISSUE TITLE
Flakey test: Test_poll/should_wait_for_the_given_duration

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#1601]
We should probably look out for interrupt and make sure the godoc declares it.

```
--- FAIL: Test_poll (0.00s)
    --- FAIL: Test_poll/should_wait_for_the_given_duration (0.00s)
        require.go:331: expected Errno 0x0(success), but was 0x6(interrupted function)
            /home/runner/work/wazero/wazero/internal/sysfs/poll_test.go:30
FAIL
```

failed on scratch Go 1.21rc3

https://github.com/tetratelabs/wazero/actions/runs/5703851221/job/15456906175?pr=1599

**Comment by evacchi** [comment]
ha, used to be like that with Select https://github.com/tetratelabs/wazero/blob/1e0c73d5692a33645e8b4164277154720fc693e1/internal/sysfs/select_test.go#L14-L27 it looked like it was not necessary with Poll and I just assumed... wrongly 😅

**Comment by evacchi** [comment]
some tests on Windows are failing too now 🤔  they are time-sensitive, but it never happened before... https://github.com/tetratelabs/wazero/actions/runs/5705107259/job/15459405932 

```
--- FAIL: TestPoll_Windows (3.21s)
    --- FAIL: TestPoll_Windows/poll_should_timeout_after_the_given_duration (0.55s)
        require.go:331: expected 1, but was 0
            D:/a/wazero/wazero/internal/sysfs/poll_windows_test.go:238
    --- FAIL: TestPoll_Windows/poll_should_return_when_a_write_occurs_before_the_given_duration (0.67s)
        require.go:331: expected 0, but was 1
            D:/a/wazero/wazero/internal/sysfs/poll_windows_test.go:255
```
