### ISSUE TITLE
`WithFSConfig` runtime panic [path naming edge case]

### ISSUE THREAD

**Issue by LukaGiorgadze** [tetratelabs/wazero#1679]
**Describe the bug**
I get runtime panic `slice out of range` if the guest path and Go reading dir in the module are exactly the same and trying to read dir.

**To Reproduce**

**Directory hierarchy:**
- /test
-- main.go - *Instantiate wazero*
-- /module
---- module.go[.wasm]
-- /dir
---- /testdir
------ testfile.txt
1. Register runtime with CompileModule;
2. Configure fs: `WithFSConfig(wazero.NewFSConfig().WithDirMount("./dir", "/testdir/"))`;
3. Write simple guest func to read all files inside dir;
4. Invoke guest func on the host.
```go
//...
dirname := "/testdir/"
files, _ := os.ReadDir(dirname)

for _, file := range files {
	filename := dirname + file.Name()
	data, _ := os.ReadFile(filename)
	
	fmt.Print(string(data))
}
```

**Expected behavior**
I guess I should get an error from `files, err := os.ReadDir("/testdir/")` something like `open /testdir/: errno 76`, but wazero panics.
**If I remove the slash at the and of the dir, it works as expected. e.g.
this works fine:
`files, err := os.ReadDir("/testdir")`
this not:
`files, err := os.ReadDir("/testdir/")`**

**Screenshots**
<img width="316" alt="Screenshot 2023-09-03 at 15 25 23" src="https://github.com/tetratelabs/wazero/assets/6573695/c258d88b-b7da-4dce-b998-9ed7a215f4e9">

```
wasm error: unreachable
wasm stack trace:
	.runtime.runtimePanicAt(i32,i32)
		0xf51e: /opt/homebrew/Cellar/tinygo/0.29.0/src/runtime/runtime_tinygowasm.go:70:6
	.runtime.slicePanic()
		0x74a6: /opt/homebrew/Cellar/tinygo/0.29.0/src/runtime/panic.go:149:16
	.greet()
2023/09/05 13:11:50 ERROR can't call guest function
wasm error: unreachable
wasm stack trace:
	.runtime.runtimePanicAt(i32,i32)
		0xf51e: /opt/homebrew/Cellar/tinygo/0.29.0/src/runtime/runtime_tinygowasm.go:70:6
	.runtime.slicePanic()
		0x74a6: /opt/homebrew/Cellar/tinygo/0.29.0/src/runtime/panic.go:149:16
	.greet()
```

**Environment (please complete the relevant information):**
- Go version: v1.21
- wazero Version: v1.5.0
- Host architecture: Apple M2
- Runtime mode: Compiler
- TinyGo v0.29.0

**Comment by achille-roussel** [comment]
Thanks for reporting @LukaGiorgadze, this definitely doesn't seem like a good cause for panic.

Would you be able to share the stack trace that you got from wazero when it panicked?

**Comment by LukaGiorgadze** [comment]
```go
wasm stack trace:
	.runtime.runtimePanicAt(i32,i32)
		0xf51e: /opt/homebrew/Cellar/tinygo/0.29.0/src/runtime/runtime_tinygowasm.go:70:6
	.runtime.slicePanic()
		0x74a6: /opt/homebrew/Cellar/tinygo/0.29.0/src/runtime/panic.go:149:16
	.greet()
```

Honestly, I just noticed TinyGo panic, but this is something worth investigating.

**Comment by mathetake** [comment]
then I don't think this is an issue of wazero, but it seems TinyGo, no?

**Comment by mathetake** [comment]
If you call an exported function from TinyGo, are you sure that you called _start function before calling any exports, and make sure that passing `-scheduler=none`? Exported functions do not work properly with scheduler and that's extremely well known and frequently encountered/asked issue

**Comment by LukaGiorgadze** [comment]
@mathetake 
>  are you sure that you called _start function before calling any exports

Yes, I use the default config of `WithStartFunctions`, which calls`_start`  by default.

> make sure that passing -scheduler=none

Yes, this is correct as well.

> but it seems TinyGo, no?

From the last output, I think so. Okay, let me address this issue with TinyGo community.

Thank you! Let's keep this issue open for a while before I talk with them and I'll close it later if you don't mind.
