### ISSUE TITLE
invalid function[322]: invalid instruction 0xfe

### ISSUE THREAD

**Issue by mr-tron** [tetratelabs/wazero#1737]
**Describe the bug**
I tried to instantiate a module https://github.com/ton-community/func-js-bin/raw/main/src/funcfiftlib.wasm and get error ` invalid instruction 0xfe`
**To Reproduce**
```
package main

import (
	"context"
	_ "embed"
	"github.com/tetratelabs/wazero"
	"log"
)

//go:embed funcfiftlib.wasm
var wasmBinary []byte

func main() {
	ctx := context.Background()
	r := wazero.NewRuntime(ctx)
	_, err := r.Instantiate(ctx, wasmBinary)
	if err != nil {
		log.Panicln(err)
	}
}

```

**Environment (please complete the relevant information):**
- Go version: 1.20.2
- wazero Version: v1.5.1-0.20230925231903-ed8566988007
- Host architecture: amd64

**Comment by ncruces** [comment]
That WASM was likely compiled with [threads](https://github.com/WebAssembly/threads) proposal, which is not finalized ([stage 3](https://github.com/WebAssembly/proposals)) and is not supported by wazero.

**Comment by mr-tron** [comment]
thank you. I suspected something like this.

**Comment by agnivade** [comment]
Threads and multi-memory were moved to Stage 4 recently: https://github.com/WebAssembly/proposals/pull/176. 

I am wondering if there are any plans to implement it? I am trying to use wazero to run whisper transcription and it would help greatly if wazero had threading support.
