### ISSUE TITLE
time library not working in tinygo

### ISSUE THREAD

**Issue by zetaab** [tetratelabs/wazero#1819]
**Describe the bug**

I am trying to develop http-wasm modules and I was wondering why time.Now() does not work correctly. It will always return 2022-01-01 timestamp. So I first opened issue to http-wasm https://github.com/http-wasm/http-wasm-guest-tinygo/issues/33 but seems that its not correct repository for the bug. My use case is for instance measure how much function call x does inside wasm. So I need time.Now() and time.Since() functions to work properly.

However, now I am trying to find which component is causing this and I am pretty sure that this is coming from wazero.

time.Now() prints always something like `2022-01-01 00:00:00.002 +0000 UTC m=+1640995200.002000001`

**To Reproduce**
See https://github.com/zetaab/wazero-demo it contains wazero example "greet" with time.Now()

**Expected behavior**
I expect that time.Now() should return correct values. Now it looks like every time call it is just increased with 1ms? It would be nice to have support as nanosecond level

**Environment (please complete the relevant information):**
- Go version: 1.21.3
- wazero Version: master
- Host architecture: arm64 (but wasm was tested also with amd64, the problem existed there as well)
- Runtime mode: 

**Additional context**

**Comment by ncruces** [comment]
This is likely a sandbox/configuration issue.

Are you using [`ModuleConfig`](https://pkg.go.dev/github.com/tetratelabs/wazero#ModuleConfig)? Specifically, `WithSysWalltime()`?

**Comment by zetaab** [comment]
@ncruces the code is available in https://github.com/zetaab/traefik-wasm-demo/tree/main/server and the wasm part is located in root of that repository

**Comment by ncruces** [comment]
Then, you need to read the documentation. What you reported is the expected behavior.

**Comment by zetaab** [comment]
Ok thanks, i did not know that.
