### ISSUE TITLE
More non-trivial examples

### ISSUE THREAD

**Issue by james-lawrence** [tetratelabs/wazero#1848]
most of the examples currently are either) specific to the compiler (tinygo, rust, zig) and don't work with golang 1.21 or are so trivial to be essentially useless (add).

add examples that show the following:
- returning dynamically sized bytes/strings from a host function.
- sending/returning arrays of strings and bytes.
- returning multiple of the above.
- reading/writing files (file created by guest, written to from host and the reverse)

currently its hard to mplement dynamic data from the host and none of it is well documented. only successful method I'd managed so far is to pre-allocate a buffer in the guest and use that which sucks since it needs to be sized large enough to hold any possible return data.

reading/writing files are not documented and don't work via the FD.

having working examples of these would ensure that at least normal usage of wazero is documented and working.

**Comment by ncruces** [comment]
> only successful method I'd managed so far is to pre-allocate a buffer in the guest and use that which sucks since it needs to be sized large enough to hold any possible return data.

This really depends on your guest environment, which is why good samples are hard to come by.

But generally, guests manage linear memory, so you need to export a function that allocates memory on demand, and have the host call it. If your guest can't export a function (like Go wasip1) that's really a guest limitation; there's no getting around that.

**Comment by james-lawrence** [comment]
@ncruces has wazero brought this to the attention of golang's implementation of wasip1? (note: golang potential limitation here isn't really relevant to the overall lack of good example code it doesn't exist for tinygo/rust/zig etc)

**Comment by ncruces** [comment]
The Go team is [aware](https://github.com/golang/go/issues/42372) of this limitation. The semantics are complicated.

W.r.t. samples in other languages, this is precisely what the [allocation](https://github.com/tetratelabs/wazero/tree/main/examples/allocation) examples want to convey.

The WASM ABI forces you to design a C like API, where you have to decide things like who allocs memory (the caller/callee). A [well designed](https://github.com/ncruces/go-sqlite3) C API is _“easy”_ to wrap, even if arbitrarily complex. If you want a more streamlined experience, something like [go-plugin](https://github.com/knqyf263/go-plugin) may be what you're after.

Having said that, we can always improve documentation and examples; I'd add that this is precisely the kind of area where new contributors can help the most.
