### ISSUE TITLE
Dynamically load WASM files

### ISSUE THREAD

**Issue by nkev** [tetratelabs/wazero#1861]
All the examples embed the WASM file(s). If you want to change the WASM code, you have to recompile the whole host app too. This is not convenient in production. I would like to see an example that loads the WASM file dynamically at runtime, and even reloads it automatically if the WASM file changes. Is this possible?

I guess what I'm asking is can I dynamically load a WASM plugin like [this](https://github.com/tetratelabs/wazero/blob/main/experimental/gojs/example/cat.go#L21-L38) but with GOOS=WASI

**Comment by mathetake** [comment]
it should be possible to just modify the existing examples to do so, your question seems more of a general Go question.
