### ISSUE TITLE
` fd_fdstat_set_flags` truncates file

### ISSUE THREAD

**Issue by yagehu** [tetratelabs/wazero#1862]
**Describe the bug**
If a file is opened with [`oflags::trunc`](https://github.com/WebAssembly/WASI/blob/main/legacy/preview1/docs.md#-oflags-record), a call to [`fd_fdstat_set_flags`](https://github.com/WebAssembly/WASI/blob/main/legacy/preview1/docs.md#-fd_fdstat_set_flagsfd-fd-flags-fdflags---result-errno) will truncate the file.

**To Reproduce**

Compile this snippet with [`wasi-sdk`](https://github.com/WebAssembly/wasi-sdk) and run it:

```bash
clang wazero-write.c
mkdir -p tmp
wazero run -mount tmp a.out
stat tmp/a 
```

```c
#include <fcntl.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>

int main(void) {
  int fd = open("tmp/a", O_RDWR | O_CREAT | O_TRUNC);
  if (fd == -1) {
    perror("open");
    return 1;
  }

  char * buf = "abc";

  int written = write(fd, buf, 3);

  printf("written %d\n", written);

  int fcntl_ret = fcntl(fd, F_SETFL, 0);
  if (fcntl_ret != 0) {
    perror("fcntl");
    return 1;
  }

  return 0;
}
```

**Expected behavior**
The file should be size 3 because we wrote 3 bytes to it. But it is size 0.

**Environment (please complete the relevant information):**
- Go version: 1.21.4
- wazero Version: `5796897f37852bf2042cd63959ce4ff673c4366e`
- Host architecture: amd64
- Runtime mode: compiler

**Additional context**
Compiling the same snippet with native clang or gcc and running it will produce a 3-byte file as expected.

**Comment by evacchi** [comment]
confirmed that even with other runtimes the byte size is still 3 after stat
