### ISSUE TITLE
[WASI] `fd_fdstat_set_flags` with `fdflags::append` resets fd offset

### ISSUE THREAD

**Issue by yagehu** [tetratelabs/wazero#1865]
**Describe the bug**
Calling `fd_fdstat_set_flags` with `fdflags::append` resets the fd offset such that calling `fd_tell` will always return 0.

**To Reproduce**

```bash
clang wazero-tell.c
mkdir -p tmp
wazero run -mount tmp a.out
```

```c
#include <fcntl.h>
#include <string.h>
#include <stdio.h>
#include <unistd.h>

int main(void) {
  int fd = open("tmp/a", O_CREAT | O_RDWR);
  if (fd == -1) {
    perror("open");
    return 1;
  }

  char * buf = "abc";

  int written = write(fd, buf, 3);
  printf("written %d bytes\n", written);

  int ret = fcntl(fd, F_SETFL, O_APPEND);
  if (ret == -1) {
    perror("fcntl");
    return 1;
  }

  off_t pos = lseek(fd, 0, SEEK_CUR);
  printf("offset %lld\n", pos);
}
```

**Expected behavior**
This should print `offset 3` since the snippet writes 3 bytes.  This is the case with other runtimes (Wasmtime, WasmEdge, WAMR) and native.  However, Wazero prints `offset 0`.

**Environment (please complete the relevant information):**
- Go version: 1.21.4
- wazero Version: 99ededcefd564ff52255fd25cedb014c83860f23
- Host architecture: amd64
- Runtime mode: compiler

**Comment by mathetake** [comment]
by #1866
