### ISSUE TITLE
Inaccurate clock resolution in WASI `clock_res_get`

### ISSUE THREAD

**Issue by yagehu** [tetratelabs/wazero#1874]
**Describe the bug**
`clock_res_get` on the system clock always returns 1000 ns.  On Linux this should be 1 ns and on Windows it should be [either 55 ms or 10 ms](https://devblogs.microsoft.com/oldnewthing/20170921-00/?p=97057).

**To Reproduce**
```bash
clang wazero-time-res.c
wazero run a.out
```

```c
#include <time.h>
#include <stdio.h>

int main(void) {
  struct timespec res;

  int ret = clock_getres(CLOCK_REALTIME, &res);
  if (ret != 0) {
    perror("clock_getres");
    return 1;
  }

  printf("clock resolution %lld sec %ld nsec\n", res.tv_sec, res.tv_nsec);

  return 0;
}
```

**Expected behavior**
Expected on Linux:

> clock resolution 0 sec 1 nsec

Actual on Linux:

> clock resolution 0 sec 1000 nsec

**Environment (please complete the relevant information):**
- Go version: 1.24.1
- wazero Version: 656d872980d0a0491c8a7a612bafa153196fda18
- Host architecture: amd64
- Runtime mode: compiler

**Comment by mathetake** [comment]
```
Expected behavior
Expected on Linux:

clock resolution 0 sec 1 nsec

Actual on Linux:

clock resolution 0 sec 1000 nsec
```

No I  don't think this is really expected or bug at all. The whole point of WASI is isolation and if you make this happen, then you leak the host information into the Wasm guest, which basically breaks the sandbox. Why do you want to make this flux depending on the underlying OS? Ack this is not written in the WASI spec at all.

**Comment by mathetake** [comment]
just FYI, wazero CLI is fixed to use WithSysWalltime API, and you can see what's expected there regarding resolutin:

```go
	// WithSysWalltime uses time.Now for sys.Walltime with a resolution of 1us
	// (1000ns).
	//
	// See WithWalltime
	WithSysWalltime() ModuleConfig
```

**Comment by yagehu** [comment]
Just want to highlight that leaking host information is not unique to clock resolution. Wazero already leaks filesystem host information like most other Wasi runtimes (Wasmtime, WasmEdge, etc.), e.g. `filestat::dev`, `filestat::ino`. I think it's reasonable to expect a call to `clock_res_get` return an accurate clock resolution, especially when the current Wazero `clock_time_get` is passed through the Go runtime to call the corresponding OS `clock_gettime`.

In any case, even if complete portability is desired for `clock_res_get`, I propose setting it to a lowest common denominator, say 55 ms, instead of an arbitrary value.
