### ISSUE TITLE
Issue with reloading compiled module

### ISSUE THREAD

**Issue by mattjohnsonpint** [tetratelabs/wazero#1913]
**Describe the bug**

Not sure if this is a bug or my misunderstanding, but I have an issue with instantiating a new version of a previously compiled module.

I'm using `CompileModule` and `InstantiateModule` separately, because my use case requires many separate instantiations of the same module.  But occasionally, the module might be updated, and thus I need to re-compile it before the next instantiation.  This works fine - except that I _think_ I should be calling `.Close()` on the old version of the compiled module to unload it from the runtime.  If I do that, I can't instantiate the _new_ version of the module.  I get an error:

> _source module must be compiled before instantiation_

... even though the module is indeed compiled.

**To Reproduce**

Here's a minimal repro.  For clarity, I've discarded all errors except the one that is giving the actual problem.

```go
package main

import (
	"context"
	"fmt"
	"io"
	"net/http"

	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/imports/wasi_snapshot_preview1"
)

func main() {

	ctx := context.Background()
	r := wazero.NewRuntime(ctx)
	defer r.Close(ctx)

	wasi_snapshot_preview1.MustInstantiate(ctx, r)

	// Works first time no problem
	c1 := getCompiledModule(ctx, r)
	doAdd(ctx, r, c1)

	// Fails second time because first module is closed - why?
	c2 := getCompiledModule(ctx, r)
	c1.Close(ctx) // I want to close c1, but keep c2 ready for use
	doAdd(ctx, r, c2)
}

func getCompiledModule(ctx context.Context, r wazero.Runtime) wazero.CompiledModule {
	resp, _ := http.Get("https://github.com/tetratelabs/wazero/raw/main/examples/basic/testdata/add.wasm")
	wasm, _ := io.ReadAll(resp.Body)
	cm, _ := r.CompileModule(ctx, wasm)
	return cm
}

func doAdd(ctx context.Context, r wazero.Runtime, cm wazero.CompiledModule) {
	cfg := wazero.NewModuleConfig()
	mod, err := r.InstantiateModule(ctx, cm, cfg)
	if err != nil {
		// On second call, panics here with "source module must be compiled before instantiation"
		// Why? The module is indeed compiled.
		panic(err)
	}

	x := uint64(10)
	y := uint64(20)
	res, _ := mod.ExportedFunction("add").Call(ctx, x, y)
	fmt.Printf("%d + %d = %d\n", x, y, res[0])
}
```

**Expected behavior**

I expect that after calling `c1.Close()` that I can no longer instantiate `c1` but I should still be able to instantiate `c2`.

Note, if I remove the `c1.Close()` call, then both invocations work fine.  I'm just unsure what state that leaves the runtime in with regard to `c1`.  I don't want to leak memory, etc.

**Environment:**
- Go version: 1.21.3
- wazero Version: 1.6.0
- Host architecture: darwin/arm64
- Runtime mode: compiler
 
Thank you.

**Comment by mattjohnsonpint** [comment]
Also note that if instead of:

```go
c2 := getCompiledModule(ctx, r)
c1.Close(ctx)
doAdd(ctx, r, c2)
```

I change the order and do this:

```go
c1.Close(ctx)
c2 := getCompiledModule(ctx, r)
doAdd(ctx, r, c2)
```

Then it works - but there's a problem with that approach.  In my real app I have these compiled modules saved in a map and accessed by an independent goroutine.  So between closing c1 and loading c2, there's no compiled module ready to instantiate.

I think perhaps something in the runtime instance is stateful with regard to all modules?  Thinking it might be the module name, I tried giving them different module names in their configurations - but with the same results.

**Comment by evacchi** [comment]
the underlying issue is that both compiled modules resolve to the same hash

https://github.com/tetratelabs/wazero/blob/5c70d8bbcc1ed7cc691f5785861965bef59f4f7a/internal/wasm/module.go#L168-L170

so when you close the first we are also deleting the cache entry:

https://github.com/tetratelabs/wazero/blob/99c057bcb5f3f4311815c884ba7113c8d52b3316/internal/engine/compiler/engine_cache.go#L18-L26

a workaround is setting up a disk cache, this way when the key is deleted from the in-memory cache we will reload it from disk; e.g.:

```
	ctx := context.Background()
	cc, _ := wazero.NewCompilationCacheWithDir("/tmp/wazerocache")

	r := wazero.NewRuntimeWithConfig(ctx,
		wazero.NewRuntimeConfig().WithCompilationCache(cc))
```

this only occurs when you are closing and reloading a module with the same hash; if the module has been actually updated, then the hash should change, and deletion should not affect its cache entry.

**Comment by mathetake** [comment]
```
	// Works first time no problem
	c1 := getCompiledModule(ctx, r)
	doAdd(ctx, r, c1)

	// Fails second time because first module is closed - why?
	c2 := getCompiledModule(ctx, r)
	c1.Close(ctx) // I want to close c1, but keep c2 ready for use
```

yeah this patter simply doesn't make sense - why when the binary if the same you want to close the previous one? basically the variable c1 and c2 points to exactly the same objects and you essentially closed the compiled object.

**Comment by varkey98** [comment]
Understand this is an anti-pattern, but I tried @evacchi 's workaround and that too is not working for me.
Code I used:
```
package main

import (
	"context"
	"fmt"
	"io"
	"net/http"

	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/imports/wasi_snapshot_preview1"
)

func main() {

	ctx := context.Background()
	cc, _ := wazero.NewCompilationCacheWithDir("/Users/varkeychanjacob/Projects/wasm-example-v2/wazerocache")
	r := wazero.NewRuntimeWithConfig(ctx, wazero.NewRuntimeConfig().WithCompilationCache(cc))
	defer r.Close(ctx)

	wasi_snapshot_preview1.MustInstantiate(ctx, r)

	// Works first time no problem
	c1 := getCompiledModule(ctx, r)
	doAdd(ctx, r, c1)

	// Fails second time because first module is closed - why?
	c2 := getCompiledModule(ctx, r)
	c1.Close(ctx) // I want to close c1, but keep c2 ready for use
	doAdd(ctx, r, c2)
}

func getCompiledModule(ctx context.Context, r wazero.Runtime) wazero.CompiledModule {
	resp, _ := http.Get("https://github.com/tetratelabs/wazero/raw/main/examples/basic/testdata/add.wasm")
	wasm, _ := io.ReadAll(resp.Body)
	cm, _ := r.CompileModule(ctx, wasm)
	return cm
}

func doAdd(ctx context.Context, r wazero.Runtime, cm wazero.CompiledModule) {
	cfg := wazero.NewModuleConfig()
	mod, err := r.InstantiateModule(ctx, cm, cfg)
	if err != nil {
		// On second call, panics here with "source module must be compiled before instantiation"
		// Why? The module is indeed compiled.
		panic(err)
	}

	x := uint64(10)
	y := uint64(20)
	res, _ := mod.ExportedFunction("add").Call(ctx, x, y)
	fmt.Printf("%d + %d = %d\n", x, y, res[0])
}
```
