### ISSUE TITLE
Host functions called from another host function cannot know the right MemoryInstance

### ISSUE THREAD

**Issue by nullpo-head** [tetratelabs/wazero#195]
In the current implementation, host functions try to get the `MemoryInstance` of `HostFunctionCallContext` from `<function>.ModuleInstance.Memory` of the parent stack's (in interpreter) or of the function itself (in jit).
However, a host function doesn't have associated `MemoryInstance` nor wasm modules in the first place. So, a host function only finds `nil` as `MemoryInstance` when it's called from another host function. 

FYI, it looks wasmtime also doesn't provide the access to memory instances when a host function is called from another host function because there's no caller context in that case, but let me check.

https://github.com/tetratelabs/wazero/blob/a6cd1549ba093e35d09fe07cd1a049b70e798185/wasm/interpreter/interpreter.go#L516
https://github.com/tetratelabs/wazero/blob/a6cd1549ba093e35d09fe07cd1a049b70e798185/wasm/jit/engine.go#L390

This also prevents the WASI implementation from testing APIs by "import-and-exported-back" style, where tests call each WASI API by having a wasm module import a WASI API and re-export it to the host.

**Comment by codefromthecrypt** [comment]
I was thinking in the PR maybe we can default to a zero length constant Memory or initialize an empty one if we are afraid some code might mutate it.

```
zero := uint32(0)
noMemory := &MemoryInstance{Min: 0, Max: &zero, Buffer: []byte{}}
```

Meanwhile these safety issues keep coming up which casts doubt on the idea that exposing the memory buffer directly is a good idea. At some point we may want to use an interface to centralize all the bug handling and make it less easy to make them

**Comment by mathetake** [comment]
I think this is something unspecified so I just passes the memory instance from the module on this host function is initialized currently if it is directly called by other host funcs, but year we should check how other runtimes do..

**Comment by codefromthecrypt** [comment]
for this one, please use the available memory (if someone forgot to add a memory, we can treat nil as zero max). I don't think there's a reasonable alternative as WebAssembly 1.0 (MVP) can have at most 1 memory. If we later find some new information, we can revise, but meanwhile not crash
