### ISSUE TITLE
Complex Types using WIT Supported 

### ISSUE THREAD

**Issue by bubbajoe** [tetratelabs/wazero#2061]
Hello,

I am wondering if it's possible to pass more complex types into WASM exported functions. Like structs or even nested structs from Go.

If this is supported i think this would make for a nice example.

**Comment by evacchi** [comment]
At the moment, the way to pass-in complex data is to serialize it to the linear memory from the host and then read it back from the guest. Essentially you will still pass in integer pairs <index, len> to the guest code, and then decode it from there. There are a few projects that you can pick to do that for you; from the top of my head https://github.com/loopholelabs/polyglot and https://wapc.io/

**Comment by mathetake** [comment]
yeah currently the only/best way is to do serde just like in https://github.com/tetratelabs/wazero/tree/main/examples/allocation
