### ISSUE TITLE
backfill a common documentation interface for jit compiler

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#207]
Right now, there are lack of overview comments on compiler methods and if we did, they would need to be copy/pasta'd and drift. Moreover, the compilers don't need to be exposed publicly as they can be hidden internally and where needed only an entry point exposed public. If we had all these things internal, we could make a documentation-only interface (with a test compile check) that has overview notes on for example, what `compileUnreachable` should do in abstract (ex any wasm opcodes or whatever). Then, the precise implementations can re-use those docs, like

```
// compileUnreachable implements Compiler.compileUnreachable for the arm64 (s390x risc-v etc) architecture.
//
// Specifically, this does blah blah and blah because blah
```

Note: this is documentation-only, meaning we can still use structs, this just allows us to ensure we have minimally documented things with no repetition and also we can easily identify what isn't common (ex. if compileXXX is specific only to one arch, we would see no `compileXXX implements Compiler. compileXXX` in the doc

**Comment by codefromthecrypt** [comment]
Ps I notice `jit.compiler`, and if we want to use this for the same purpose, let's add the docs then backfill the `compileXXX implements compiler.compileXXX` before people end up copy/pasting functions without any docs

**Comment by mathetake** [comment]
> Ps I notice jit.compiler, and if we want to use this for the same purpose, let's add the docs then backfill the compileXXX implements compiler.compileXXX before people end up copy/pasting functions without any docs

I will follow this path for now rather than digging internal package as we certainly end up cycle imports in tests (decoupling engine from assembler logics is really hard by design). In anyway we won't export any compiler methods/consts/etc so that's fine for user-facing concerns.

**Comment by codefromthecrypt** [comment]
SGTM thanks!
