### ISSUE TITLE
compiler(arm64) overflow in call relocations

### ISSUE THREAD

**Issue by davidmdm** [tetratelabs/wazero#2158]
**Describe the bug**

A wasm module that was being compiled and instantiated with wazero 1.6.0 successfully now segfaults with version 1.7.0.

**To Reproduce**
I am building my own experimental tool that embeds wazero for supporting wasm. Here is a link to the wasm file I was testing with:
https://github.com/davidmdm/flights/releases/download/v0.0.0-yokecd-test/pg.wasm

This module is an executable that should output some JSON to stdout.

This is the code I use to intantiate it:

```go
package wasi

import (
	"bytes"
	"context"
	"crypto/rand"
	"fmt"
	"io"

	"github.com/tetratelabs/wazero"
	"github.com/tetratelabs/wazero/imports/wasi_snapshot_preview1"

	"github.com/davidmdm/x/xerr"
)

func Execute(ctx context.Context, wasm []byte, release string, stdin io.Reader, args ...string) (output []byte, err error) {
	cfg := wazero.
		NewRuntimeConfig().
		WithCloseOnContextDone(true)

	// Create a new WebAssembly Runtime.
	wasi := wazero.NewRuntimeWithConfig(ctx, cfg)
	defer func() {
		err = xerr.MultiErrFrom("", err, wasi.Close(ctx))
	}()

	wasi_snapshot_preview1.MustInstantiate(ctx, wasi)

	// Because we are running a binary directly rather than embedding in an application,
	// we default to wiring up commonly used OS functionality.
	mod, err := wasi.CompileModule(ctx, wasm)
	if err != nil {
		return nil, fmt.Errorf("failed to compile module: %w", err)
	}

	var (
		stdout bytes.Buffer
		stderr bytes.Buffer
	)

	moduleCfg := wazero.
		NewModuleConfig().
		WithStdout(&stdout).
		WithStderr(&stderr).
		WithRandSource(rand.Reader).
		WithSysNanosleep().
		WithSysNanotime().
		WithSysWalltime().
		WithArgs(append([]string{release}, args...)...)

	if stdin != nil {
		moduleCfg = moduleCfg.WithStdin(stdin)
	}

	if _, err := wasi.InstantiateModule(ctx, mod, moduleCfg); err != nil {
		details := stderr.String()
		if details == "" {
			details = "(no output captured on stderr)"
		}
		return nil, fmt.Errorf("failed to instantiate module: %w: stderr: %s", err, details)
	}

	return stdout.Bytes(), nil
}
```

**Expected behavior**

I expect the wasm file to be executed without segfaults, and to produce the same output as wazero 1.6.0

**Screenshots**
<img width="1014" alt="image" src="https://github.com/tetratelabs/wazero/assets/12768642/aec4eb60-ab67-43b8-add2-115df4ca8811">

**Environment (please complete the relevant information):**
- go version go1.22.1 darwin/arm64
- wazero Version: 1.7.0
- Host architecture: arm64

**Additional context**

**Comment by davidmdm** [comment]
I've fixed this issue for myself by switching to using the interpreter which may in fact be more appropriate for my use-case overall since startup time is more important to me than execution time.

However will leave this up, and will answer any questions. I want to mention that I love wazero and think it is an understated contribution to the Go-Ecosystem. Well done team!

**Comment by evacchi** [comment]
Hi, can you share the faulty module so we can inspect it?

**Comment by evacchi** [comment]
- for reference, just running through `wazero run pg.wasm` shows the same behavior (no need for the wrapping script).
- Also, `GOARCH=amd64 wazero run pg.wasm` crashes just the same, which is likely to mean a bug in the front-end (i.e. it is not a bug in the machine-specific codegen)
- finally, some experimental "fix" that I am working on for a different bug in the front-end (re: bound check elimination) causes the hard crash to turn into a wasm stack trace; it might not be related and just be a bug on top of another bug 😬 

```
error instantiating wasm binary: module[] function[_start] failed: wasm error: out of bounds memory access
wasm stack trace:
	.k8s.io_api_apps_v1beta2.__DeploymentList_.DeepCopyInto(i32) i32
	.runtime.doInit1(i32) i32
	.runtime.main(i32) i32
	.wasm_pc_f_loop()
	._rt0_wasm_wasip1()
```

**Comment by davidmdm** [comment]
@evacchi

The binary was produced via the Go Toolchain:
```bash
GOOS=wasip1 GOARCH=wasm go build -o pg.wasm ./cmd/pg
```

I tried running wazero directly against an equivalent pg.wasm and got the same thing you did:

```bash
wazero run pg.wasm 
error instantiating wasm binary: module[] function[_start] failed: wasm error: out of bounds memory access
wasm stack trace:
        .k8s.io_api_apps_v1beta2.__DeploymentList_.DeepCopyInto(i32) i32
        .runtime.doInit1(i32) i32
        .runtime.main(i32) i32
        .wasm_pc_f_loop()
        ._rt0_wasm_wasip1()
```

I then tried it on a "more manageable" hello-world version of a kubernetes resource but still compiling the kubernerte's client-go packages:

```go
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"

	appsv1 "k8s.io/client-go/applyconfigurations/apps/v1"
	corev1 "k8s.io/client-go/applyconfigurations/core/v1"
	metav1 "k8s.io/client-go/applyconfigurations/meta/v1"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
}

func run() error {
	name := os.Args[0] + "-sample-app"
	labels := map[string]string{"app": name}

	replicas := flag.Int("replicas", 2, "desired replica count for deployment")

	flag.Parse()

	dep := appsv1.Deployment(name, "").
		WithLabels(labels).
		WithSpec(
			appsv1.DeploymentSpec().
				WithReplicas(int32(*replicas)).
				WithSelector(metav1.LabelSelector().WithMatchLabels(labels)).
				WithTemplate(
					corev1.PodTemplateSpec().
						WithLabels(labels).
						WithSpec(
							corev1.PodSpec().WithContainers(
								corev1.Container().
									WithName(name).
									WithImage("alpine:latest").
									WithCommand("watch", "echo", "hello", "world"),
							)),
				),
		)

	return json.NewEncoder(os.Stdout).Encode(dep)
}
```

and although it didn't crash with a stack trace, no output is rendered with `v1.7.0`, but it works successfully with `v1.6.0` using `wazero run` on the wasm outputted via `GOOS=wasip1 GOARCH=wasm go build`

**Comment by evacchi** [comment]
hah, I thought `pg` had something to do with postgres, but even this smaller example produces a 69meg binary :D so it really has to do with instantiating these huge protos. See e.g. 

```
package main

import (
	corev1 "k8s.io/client-go/applyconfigurations/core/v1"
)

func main() {
	c := corev1.Container().
		WithName("hello").
		WithImage("alpine:latest").
		WithCommand("watch", "echo", "hello", "world")

	println(c)
}
```

**Comment by davidmdm** [comment]
Pg does have something to do with postgres, but regardless of what I am deploying/generating, I am generating kubernetes manifests from K8 client libraries via the magic of wazero! I've switched to using the interpreter for now since its a good fit for my use-case, but it's good you've managed to find a more minimalistic way to reproduce the issue!

**Comment by evacchi** [comment]
so just to give you some feedback, I've been looking into this. The bad news is that I am still figuring it out, the somewhat good news is that this bug is limited to arm64. With shorter examples; e.g.

```
	c := v1.ContainerPort()
	fmt.Printf("%v", c)
```

I can get a stack trace similar to the one you show:

```
error instantiating wasm binary: module[] function[_start] failed: wasm error: out of bounds memory access
wasm stack trace:
	.github.com_google_gnostic_models_openapiv2.__Any_.ProtoReflect(i32) i32
	.runtime.doInit1(i32) i32
	.runtime.main(i32) i32
	.wasm_pc_f_loop()
	._rt0_wasm_wasip1()
```

in general it looks like something funky is going on in the `init()` phase.

This won't happen either with the interpreter or GOARCH=amd64

**Comment by evacchi** [comment]
@davidmdm in case you didn't see this yet, I have a WIP PR addressing your issue #2169
