### ISSUE TITLE
GOOS=wasip1 embedding wazero succeeds with wasmtime but fails with wazero on arm64

### ISSUE THREAD

**Issue by anuraaga** [tetratelabs/wazero#2179]
**Describe the bug**

I have a small Wasm binary compiled from Go using `GOOS=wasip1` that includes wazero in it. It runs with wasmtime but crashes with wazero, which I assume isn't expected.

```
runtime: g 1: unexpected return pc for runtime.sigpanic called from 0x10d6aebfc
stack: frame={sp:0x140000ad480, fp:0x140000ad4e0} stack=[0x1400002c000,0x14000030000)

fatal error: unknown caller pc

runtime stack:
runtime.throw({0x104c7866d?, 0x104a7a488?})
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/runtime/panic.go:1023 +0x40 fp=0x16f3fadc0 sp=0x16f3fad90 pc=0x104a885b0
runtime.(*unwinder).next(0x16f3fae90)
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/runtime/traceback.go:469 +0x2c8 fp=0x16f3fae50 sp=0x16f3fadc0 pc=0x104ab1658
runtime.(*_panic).nextFrame.func1()
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/runtime/panic.go:938 +0x8c fp=0x16f3faf10 sp=0x16f3fae50 pc=0x104a881dc
runtime.systemstack(0x803000)
	/opt/homebrew/Cellar/go/1.22.2/libexec/src/runtime/asm_arm64.s:243 +0x6c fp=0x16f3faf20 sp=0x16f3faf10 pc=0x104abc82c
```

**To Reproduce**
Description of the host and wasm code that reproduces the behavior.
Smoothest debugging will be if you can share a repository with the
actual code.

```
git clone github.com/wasilibs/go-re2
cd go-re2
mkdir -p build
GOARCH=wasm GOOS=wasip1 go build -o build/test.wasm ./internal/e2e
go run github.com/tetratelabs/wazero/cmd/wazero@v1.7.0 run build/test.wasm
```

The compiled program is here:

https://github.com/wasilibs/go-re2/blob/main/internal/e2e/main.go#L6

**Expected behavior**

Completes with no error.

**Environment (please complete the relevant information):**
- Go version: 1.22.2 (both for compiling wasm and executing wazero)
- wazero Version: v1.7.0 (also tried with c6a907bb9d6c4605355562859e7cd2fae67fd246)
- Host architecture: arm64
- Runtime mode: compiler (CLI defaults)

**Additional context**

**Comment by mathetake** [comment]
how small is that? I think this is the same as #2158 and only limited to arm64. maybe try https://github.com/tetratelabs/wazero/pull/2169 ?

**Comment by mathetake** [comment]
`GOARCH=amd64 go install ./cmd/wazero` can be used to see whether it works on amd64 or not

**Comment by anuraaga** [comment]
@mathetake Thanks for the tip! Forgot to check with 1.6.0. Indeed it seems likely to be related to that issue.

Can confirm 1.6.0 works, and GOARCH=amd64 and Rosetta works on my Mac. The binary is 6.5MB, while not insane, does seem pretty big.

Unfortunately, that PR doesn't seem to fix it here /cc @evacchi Maybe a useful test case to help

` go run github.com/tetratelabs/wazero/cmd/wazero@b1494160650adc3cd2961787fb788068508271c2 run build/test.wasm`

If its seems likely the same as that issue, let's close this one.

**Comment by mathetake** [comment]
I tried locally, but seems like this is a different issue as the assertion added in https://github.com/tetratelabs/wazero/pull/2167 didn't hit. But anyway this is arm64 specific yeah

**Comment by mathetake** [comment]
stripped down to 4mb binary, but still no clue 😉
