### ISSUE TITLE
Support dialing sockets, udp, tcp, unix.

### ISSUE THREAD

**Issue by james-lawrence** [tetratelabs/wazero#2187]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to make network request from within a guest runtime.

**Describe the solution you'd like**
use standard golang net package for dialing sockets.

**Describe alternatives you've considered**
we've had to switch to using stealthrockets implementation for the wasip1 runtime.

**Comment by james-lawrence** [comment]
As in never planned to be supported by wazero?

**Comment by mathetake** [comment]
if this is the one defined in the specifications either wasip1 or the future wasi v1.0, yes possible in the future. But that is not the case right, now and you can implement whatever you want just like https://github.com/dispatchrun/net

**Comment by james-lawrence** [comment]
i was looking at implementing it at somepoint this (hopefully, life etc) summer/fall and the tracking the progress here. I know it wouldnt be merged until the spec standardized. And was hoping this could be a coordination point for others who are interested in the space. Are you against that as well?

**Comment by labulakalia** [comment]
you can try this open source project,it base on host func
https://github.com/labulakalia/wazero_net
