### ISSUE TITLE
Race condition during module compilation  engine

### ISSUE THREAD

**Issue by martinlakov** [tetratelabs/wazero#2190]
**Describe the bug**

In the `wazevo` engine implementation there're multiple places where Go maps are used (not sync.Map). When trying to run modules in parallel (different runtime instances, shared cache) - race conditions occur and execution is aborted with `fatal error: concurrent map read and map write`

**To Reproduce**

Try and run the same command module in a for loop, creating a new runtime for each iteration. Delegate load & execution to a new Go routine for each execution attempt.

**Expected behavior**

No race condition / panics shall occur when running modules in parallel with a common/shared cache.

**Screenshots**

N/A

**Environment (please complete the relevant information):**

- Go version: 1.22.1
- wazero Version: v1.7.1
- Host architecture: amd64
- Runtime mode: compiler

**Additional context**

N/A

**Comment by mathetake** [comment]
please provide the reproducer, otherwise we can't verify

**Comment by mathetake** [comment]
closing until you give us the minimal repro. Note that executing a module instance concurrently is inherently unsafe and not possible unless you use the threading proposal enabled + your binary is compiled in that way.

**Comment by martinlakov** [comment]
As described in [this comment](https://github.com/tetratelabs/wazero/blob/main/cache.go#L57) - a compilation engine is getting re-used/shared between runtimes.

The `wazevo` engine comes with an internal map named `compiledModules`. When creating runtimes & compiling modules happens concurrently - a race condition occurs with accessing the said map. This happens [in here](https://github.com/tetratelabs/wazero/blob/main/internal/engine/wazevo/engine.go#L574)

**Comment by martinlakov** [comment]
I'd be glad to provide example(s), propose a fix etc. Just want to see this one getting resolved 😊

**Comment by martinlakov** [comment]
A bit of background to the story - issue has been observed while working on a high-level library that steps on top of `wazero` and takes care to hide away complexity associated with working with the linear memory etc. This one - we plan to open-source as soon we have the APIs somewhat final.

**Comment by martinlakov** [comment]
@mathetake - update of my previous comment (was on my phone, on my way to work)

As described in [this comment](https://github.com/tetratelabs/wazero/blob/main/cache.go#L57) - a compilation engine is getting re-used/shared between runtimes.

The `wazevo` engine comes with an internal map named `compiledModules`. When creating runtimes & compiling modules happens concurrently - a race condition occurs with accessing the said map. This happens like so:

- [in here](https://github.com/tetratelabs/wazero/blob/main/internal/engine/wazevo/engine.go#L574)
- [invoked from](https://github.com/tetratelabs/wazero/blob/main/internal/wasm/store.go#L350) which is in turn being invoked [in here]
- [invoked from](https://github.com/tetratelabs/wazero/blob/main/internal/wasm/store.go#L326)
- [invoked from](https://github.com/tetratelabs/wazero/blob/main/runtime.go#L312)

As the "callstack" suggests - there's no logic to govern access to the said map and the said map is not thread-safe. As a result - a race condition occurs as soon as you try and use a single cache instance among multiple runtime instances and you try to load/execute modules concurrently. 

It is evident that we're talking about a bug in here. If you take a look at the implementation of `CompiledModuleCount` for `wazevo` (see: [here](https://github.com/tetratelabs/wazero/blob/main/internal/engine/wazevo/engine.go#L501)) - read-only access to the said map is governed appropriately.

**Comment by martinlakov** [comment]
A potential fix for the problem is to create a "private" function to check if a module has been compiled already. Something like:

```
func (e *engine) isCompiled(m *wasm.Module) bool {
	e.mux.RLock()
	defer e.mux.RUnlock()

	_, ok := e.compiledModules[m.ID]
	return ok
}
```

and replace the direct access to the map [in here](https://github.com/tetratelabs/wazero/blob/main/internal/engine/wazevo/engine.go#L574) with calling the said function.
