### ISSUE TITLE
`wazero.NewCompilationCache` creates a `CompilationCache` instance that's not really caching anything

### ISSUE THREAD

**Issue by martinlakov** [tetratelabs/wazero#2191]
**Describe the bug**

Using `wazero.NewCompilationCache` a `CompilationCache` is created that in fact never caches anything. The `wazevo` engine only caches compiled modules in case it is supplied with a `filecache.Cache` instance. The said dependency is always `nil` for `CompilationCache` instances created using `wazero.NewCompilationCache` (see: [here](https://github.com/tetratelabs/wazero/blob/main/internal/engine/wazevo/engine_cache.go#L40) & [here](https://github.com/tetratelabs/wazero/blob/main/internal/engine/wazevo/engine_cache.go#L98)). This behavior is highly confusing, especially when looking at [this comment](https://github.com/tetratelabs/wazero/blob/main/cache.go#L32).

**To Reproduce**

Try and execute the same command modules using two compiler runtimes that share an in-memory cache. Observe that compilation is performed before each module run.

**Expected behavior**

In-memory cache shall in fact be able to cache module compilation artifacts and be shareable between different runtimes.

**Screenshots**

N/A

**Environment (please complete the relevant information):**

- Go version: `1.22.1`
- wazero Version:` v1.7.1`
- Host architecture: `amd64`
- Runtime mode: `compiler`

**Additional context**

N/A

**Comment by evacchi** [comment]
When an in-memory cache is configured, compilation does not _actually_ occur for real, even though we do invoke `compileModule` internally.

https://github.com/tetratelabs/wazero/blob/350e81e632f9e70f4f21eb3fa2da9bf8c5e5c26e/cache_test.go#L137-L142

What really happens is that if there is a hit at `getCompiledModuleFromMemory()` then we return early with the pre-compiled module.

e.g. see 

https://github.com/tetratelabs/wazero/blob/1b2fd85012fafc1aa3bf6498173d4cbc71a48913/internal/engine/wazevo/engine_cache.go#L46-L50

you can verify this easily if you try to compile a large module (which would take a sensible time compiling twice)

**Comment by martinlakov** [comment]
@mathetake - As explained in the description - problem is observed when running the same module twice, using two runtime instances that share an in-memory cache. The module is then compiled every single time and no caching occurs. 

This, to me, is a bug. Considering [the already referenced comment](https://github.com/tetratelabs/wazero/blob/main/cache.go#L32) - this is not the desired behavior too.

**Comment by ncruces** [comment]
Did you share a reproducer for this one?

**Comment by martinlakov** [comment]
@ncruces, @evacchi, @mathetake - after a bit of play with the debugger - I've come across the root cause for the problem. When using `Instantiate` or `InstantiateWithConfig` (implicit module compilation) - the flag `closeWithModule` on the compiled module is being raised. As a result of that - after module instantiation is complete - the compiled module is being closed (hence removed from the in-memory cache).

One can say - this is a problem with the documentation and yes - docs would definitely appreciate a bit of love here. However - considering that caching is at play - my honest suggestion is that the flag `closeWithModule` should only be respected **_if no cache instance is configured_** for the said runtime.

**Comment by evacchi** [comment]
ah I see, we stumbled upon this behavior while solving a different issue. In this case it is safer to `Compile` separately than `Instantiate`ing, this way the flag `closeWithModule` won't be set implicitly

**Comment by martinlakov** [comment]
@evacchi - this behavior is bith inconsistent & poorly documented. My humble proposal still stands - `closeWithModule` should only happen when no cache is configured for the runtime.

**Comment by martinlakov** [comment]
@evacchi - thank you!
