### ISSUE TITLE
Race condition during module interpretation with `interpreter` engine

### ISSUE THREAD

**Issue by martinlakov** [tetratelabs/wazero#2192]
**Describe the bug**

In the `interpreter` engine implementation a race condition occurs when trying to run modules in parallel (different runtime instances, shared cache). As a result execution is aborted with `[fatal error: concurrent map read and map write](panic: runtime error: index out of range [2] with length 0)`

```
panic: runtime error: index out of range [2] with length 0

goroutine 8 [running]:
github.com/tetratelabs/wazero/internal/engine/interpreter.(*engine).setLabelAddress(...)
	/<project-path>/vendor/github.com/tetratelabs/wazero/internal/engine/interpreter/interpreter.go:488
github.com/tetratelabs/wazero/internal/engine/interpreter.(*engine).lowerIR(0xc000092090, 0xc0020a6078, 0xc00bb038a0)
	/<project-path>/vendor/github.com/tetratelabs/wazero/internal/engine/interpreter/interpreter.go:466 +0x3d2
github.com/tetratelabs/wazero/internal/engine/interpreter.(*engine).CompileModule(0xc000092090, {0xc003b46000?, 0x305e2b?}, 0xc000501dc0, {0x0, 0x0, 0xc00019bc38?}, 0x0)
	/<project-path>/vendor/github.com/tetratelabs/wazero/internal/engine/interpreter/interpreter.go:386 +0x21e
github.com/tetratelabs/wazero.(*runtime).CompileModule(0xc0003a6b40, {0x7aef78, 0xa19960}, {0xc003b46000, 0x305e2b, 0x306000})
	/<project-path>/vendor/github.com/tetratelabs/wazero/runtime.go:237 +0x206
github.com/tetratelabs/wazero.(*runtime).InstantiateWithConfig(0xc0003a6b40, {0x7aef78, 0xa19960}, {0xc003b46000?, 0x305e2b?, 0x306000?}, {0x7b2cf8, 0xc00095c3c0})
	/<project-path>/vendor/github.com/tetratelabs/wazero/runtime.go:273 +0x38
...
exit status 2
```

**To Reproduce**

Try and run the same command module in a for loop, creating a new runtime for each iteration. Delegate load & execution to a new Go routine for each execution attempt.

**Expected behavior**

No race condition / panics shall occur when running modules in parallel with a common/shared cache.

**Screenshots**

N/A

**Environment (please complete the relevant information):**

- Go version: `1.22.1`
- wazero Version: `v1.7.1`
- Host architecture: `amd64`
- Runtime mode: `interpreter`

**Additional context**

N/A

**Comment by mathetake** [comment]
dup https://github.com/tetratelabs/wazero/issues/2190
