### ISSUE TITLE
wasm debug build crashes

### ISSUE THREAD

**Issue by mark-pictor-csec** [tetratelabs/wazero#2205]
## Describe the bug
The wasm module exits with a stack trace

This is an _attempt_ to reproduce a crash I've seen, but seems to be a different crash. The original crash only happened on `1.7.{0,1}`, not the other wazero versions I've tested (`1.2.1`, `1.6.0`); this crashes on all of those versions of wazero.

**Note:** it's possible this is a bug in my reproducer's code rather than in wazero, though the native version runs without problems.

## To Reproduce
optional: install rust `v1.78.0` and rust's `wasm32-wasi` target, i.e. `rustup target add wasm32-wasi`

[wazero_crash.tgz](https://github.com/tetratelabs/wazero/files/15253720/wazero_crash.tgz)

Unpack the above tarball and run the below command - this runs the wasm with wazero 1.7.1.

There shouldn't be anything special about how I'm running the wasm, but for your convenience I included some go code to invoke the function through wazero.
```sh
go run ./cmd -skipbuild
```
The wasm will crash when `regex()` is called - see `main.rs:22` for the full stack trace

If you run with `go run ./cmd -release -skipbuild`, it does not crash.

### Build locally

If you have the above rust version installed, you can omit `-skipbuild` to build the wasm locally. Alternately, `cargo build --target=wasm32-wasi`, adding `--release` for a release build.

See `README.md` for more info.

## Expected behavior

Calling `regex()` in the wasm does not result in a crash.

Alternately: running `go run ./cmd`, with or without `-release`, does not crash.

## Screenshots

N/A

## Environment
- Go version: 1.22.0
- wazero Version: 1.7.1, 1.7.0, 1.6.0, 1.2.1
- Host architecture: amd64
- Runtime mode: compiler

## Additional context
There is a [slack discussion](https://gophers.slack.com/archives/C040AKTNTE0/p1714767322054749) but it is a somewhat different bug: that crash only happens with wazero v1.7.x, on both amd64 and arm64. I have not tried running this on arm64.

**Comment by mathetake** [comment]
Sorry this didn't reproduce, and not sure why you meant by "crash".

```
mathetake@lima-default:/Users/mathetake/wazero/wazero_crash$ go run ./cmd -release -skipbuild
2024/05/09 11:57:09 6 funcs exported:
2024/05/09 11:57:09   deallocate: 2 params
2024/05/09 11:57:09   _start: 0 params
2024/05/09 11:57:09   __main_void: 0 params
2024/05/09 11:57:09   regex: 2 params
2024/05/09 11:57:09   ac: 2 params
2024/05/09 11:57:09   allocate: 1 params
2024/05/09 11:57:09 [1]
2024/05/09 11:57:09 [1]
mathetake@lima-default:/Users/mathetake/wazero/wazero_crash$ echo $?
0
mathetake@lima-default:/Users/mathetake/wazero/wazero_crash$ go run ./cmd -skipbuild
2024/05/09 11:57:17 6 funcs exported:
2024/05/09 11:57:17   __main_void: 0 params
2024/05/09 11:57:17   regex: 2 params
2024/05/09 11:57:17   ac: 2 params
2024/05/09 11:57:17   allocate: 1 params
2024/05/09 11:57:17   deallocate: 2 params
2024/05/09 11:57:17   _start: 0 params
2024/05/09 11:57:17 [1]
2024/05/09 11:57:17 [1]
mathetake@lima-default:/Users/mathetake/wazero/wazero_crash$ echo $?
0
```

**Comment by mathetake** [comment]
if you still believe it "crashes", I would appreciate it if you setup the repository and give us the failing github action job.

**Comment by mark-pictor-csec** [comment]
Well that's unfortunate. Thanks for taking a look.

> setup the repository and give us the failing github action job.

I'm guessing you mean clone the repo, enable ci, add test, etc?

**Comment by ncruces** [comment]
It doesn't need to be a fork of this repo. Just your repo, with your code, that depends on wazero, and an action that shows your crash. That would be incredibly helpful.

**Comment by mark-pictor-csec** [comment]
@mathetake @ncruces 
I finally found time to work on this more. See the `run wasm debug` step [in the failed action](https://github.com/mark-pictor-csec/wazero_rust_crash/actions/runs/9133849827/job/25118191937#step:14:17).
```
call regex(): wasm error: unreachable
wasm stack trace:
	wazero_crash_lib-4cb0c7a6ebcbc518.wasm.abort()
	wazero_crash_lib-4cb0c7a6ebcbc518.wasm._ZN3std3sys3pal4wasi7helpers14abort_internal[17](https://github.com/mark-pictor-csec/wazero_rust_crash/actions/runs/9133849827/job/25118191937#step:14:18)h05344e3339eea616E()
		0x353f05: /rustc/9b00956e56009bab2aa15d7bff10916599e3d6d6/library/std/src/sys/pal/wasi/helpers.rs:107:14
        [ ... ]
```

**Comment by mathetake** [comment]
great, thank you for your time. I see it only reaches unreachable with debug build. Does that happen with interpreter? Also, could you update to 1.7.2 and see if it is fixed or not?

**Comment by mathetake** [comment]
I am sorry this happens for all amd64, arm64 and interpreter and don't think this is a bug of wazero. 99% sure that your bug existing in https://github.com/mark-pictor-csec/wazero_rust_crash/blob/main/cmd/main.go#L113-L140 

how can you be sure that the pointer escaped in the `cleanup` closure  is alive until the end? That's where debug vs release difference creeps in i thinl.

**Comment by mark-pictor-csec** [comment]
I don't think the pointer's liveness could have any effect here. The error comes from `(api.Function).Call()`, before the deferred cleanup could run. Note the first line printed in the error:
```
call regex(): wasm error: unreachable
```
matching the log statement in [main.go:L120..L123](https://github.com/mark-pictor-csec/wazero_rust_crash/blob/main/cmd/main.go#L120..L123):
```go
	res, err := m.Call(ctx, ptr, uint64(len(s)))
	if err != nil {
		log.Fatalf("call regex(): %s", err)
	}
```

**Comment by mark-pictor-csec** [comment]
ugh... found a mistake in my code. I'll fix it and get back to you
