### ISSUE TITLE
performance issue in browser environment

### ISSUE THREAD

**Issue by storybehind** [tetratelabs/wazero#2207]
**Statement**

I did a cross-compilation of Rust code to wasm and embedded into my Go application. After compiling my Go application with env `GOOS=js` & `GOARCH=wasm` and executing in browser environment, much slower performance is observed compared to my local environment.

**Description**

Please find the complete source code here: [demo.zip](https://github.com/tetratelabs/wazero/files/15325997/demo.zip)

1) demo.go - `ImageRs.Convert()` resizes an image by calling exported function in wasm using the runtime.

```
var (
	//go:embed image_rs.wasm
	imageWasm []byte

)

type ImageRs struct {
	ctx              context.Context
	runtime          wazero.Runtime
	compiledMod      wazero.CompiledModule
}

func (i *ImageRs) Convert(img []byte, width, height int) ([]byte, error) {
        ...
}
```

2) main.go - provides js wrapper

```
func thumbnailWrapper() js.Func {
       ...
}

func main() {
	js.Global().Set("thumbnail", thumbnailWrapper())
	<-make(chan struct{})
}
```

3) `demo.wasm` is produced on executing `CGO_ENABLED=0 GOOS=js GOARCH=wasm go build -o demo.wasm .` in root folder of the project.

 4) On opening `demo.html` instantiates `demo.wasm`.

**Screenshots**

Benchmark shows it takes less than a second to execute in my local env while it takes minutes in browser environment.

<img width="498" alt="benchmark-go" src="https://github.com/tetratelabs/wazero/assets/25722614/b7581f97-06e2-4162-81a1-e990090fe43f">

<img width="548" alt="demo-browser" src="https://github.com/tetratelabs/wazero/assets/25722614/bc9430bd-ce59-408b-927b-74b6cba9f0a1">

**Environment (please complete the relevant information):**
- Go version: [1.22.0]
- wazero Version: [1.7.2]
- Host architecture: [amd64]
- Runtime mode: [compiler]

**Comment by ncruces** [comment]
You're comparing running (a small Rust) Wasm binary by:
1. using wazero to _compile_ it to native amd64 assembly and running _that_;
2. running the entire Go runtime, plus the wazero Wasm _interpreter_, inside _another_ Wasm runtime.

Running a Wasm interpreter inside Wasm is slow.

Why do you want to do that?

**Comment by storybehind** [comment]
> Why do you want to do that?

This is part of SDK which is cross-compiled for use in few platforms including web. Due to limited support for the required functionality in Go, SDK uses wasm compiled from rust library and wazero runtime. 

It seems like I'm complicating. Is there an alternate way that would work?

**Comment by mathetake** [comment]
Sorry, essentially this is the issue with interpreter performance which is not the scope of the project.
