### ISSUE TITLE
[Question] Compilation cache over different versions

### ISSUE THREAD

**Issue by ayuhito** [tetratelabs/wazero#2209]
> The contents written into dirname are wazero-version specific, meaning different versions of wazero will duplicate entries for the same input wasm. 

[Reference](https://pkg.go.dev/github.com/tetratelabs/wazero#NewCompilationCacheWithDir)

Just for clarification. Does this mean different Wazero versions will overwrite these caches for the same input WASM or it is the developer's responsibility to clear the cache before running when the version is changed? I'm building a CLI tool that is a version manager so caches might get invalidated quite frequently in this case.

**Comment by ncruces** [comment]
A new (sub-)directory is created for every wazero version:
https://github.com/tetratelabs/wazero/blob/48f702e154b5727bfb3ef734f7fe1f90631b3509/cache.go#L95

Within that folder, each module is keyed by a sha256 hash of the Wasm and some other stuff.

You may want to eventually cleanup old directories and/or modules.
