### ISSUE TITLE
`unreachable` error and stack trace if compiled and extra memory, not otherwise

### ISSUE THREAD

**Issue by mark-pictor-csec** [tetratelabs/wazero#2215]
**Describe the bug**
Follow-on to #2205 . This is the original bug; in 2205, I was trying to repro this with code I could share. I've given up on that, and this just has the (proprietary) wasm blob.

See [workflow run, step 7](https://github.com/mark-pictor-csec/wazero_rust_crash/actions/runs/9227266843/job/25388831318#step:7:11)

Calling `init()` in the wasm results in an `unreachable` error and a stack trace, provided
* extra memory is allocated, and
* mode is compilation, not interpretation

If either of those is false the function returns without error (see preceding two steps in the worflow run).

**To Reproduce**

Clone [the repo](https://github.com/mark-pictor-csec/wazero_rust_crash/tree/main) and run the commands listed in the README.
Alternately, run the github workflow. @ncruces and @mathetake I believe you'll have sufficient rights to do so, and I could add other wazero contributors if desired. 

**Expected behavior**
`init()` runs successfully, even compiled mode + extra memory

**Screenshots**
N/A

**Environment (please complete the relevant information):**
- Go version: 1.22.0
- wazero Version: 1.7.2
- Host architecture: amd64
- Runtime mode: compiler
  - bug not hit in interpreter mode
- Instance memory expanded to 8 MB 
  - other amounts untested, but bug not hit with default mem amount

**Additional context**
Unfortunately I cannot provide source for the wasm binary.

I tried to copy out the source relevant to the stack trace but wasn't getting the error. It seems that either I missed something, or the code `rustc` produces is influenced by things that don't show up in the stack trace.

**Comment by mathetake** [comment]
sorry, it's impossible to debug without having the code. Feel free to reopen until you got it.

**Comment by mathetake** [comment]
one thing is that you SHOULD NOT grow the memory by yourself, it's one way to destroy the language runtime (this case Rust's allocator). The runtime is NOT aware of the growth, so anything can happen.

**Comment by mark-pictor-csec** [comment]
Awesome, this fixes the issue I'd hit.
TYVM!
🙇
