### ISSUE TITLE
Clarification on concurrency semantics for invocations

### ISSUE THREAD

**Issue by purplefox** [tetratelabs/wazero#2217]
Hello All,

Thank you for a great library - it is proving very useful so far :)

I have a question on the concurrency semantics for invocations on a module instance (an instance of api.Module).

I have multiple Function instances that invoke a function on the same instance using Call(...). The documentation seems to imply that this is ok, as I am using different Function instances:

```
// Call is not goroutine-safe, therefore it is recommended to create
// another Function if you want to invoke the same function concurrently.
// On the other hand, sequential invocations of Call is allowed.
// However, this should not be called multiple times until the previous Call returns.
```
However, when running test with the golang race detector enabled I see race conditions reported, e.g.:

This goroutine is calling a WASM function and the engine is trying to allocate some memory

```
WARNING: DATA RACE
Read at 0x00c030f8d2d0 by goroutine 62472:
  runtime.growslice()
      /usr/local/go/src/runtime/slice.go:157 +0x0
  github.com/tetratelabs/wazero/internal/wasm.(*MemoryInstance).Grow()
      /Users/tim/go/pkg/mod/github.com/tetratelabs/wazero@v1.7.1/internal/wasm/memory.go:255 +0x300
  github.com/tetratelabs/wazero/internal/engine/wazevo.(*callEngine).callWithStack()
      /Users/tim/go/pkg/mod/github.com/tetratelabs/wazero@v1.7.1/internal/engine/wazevo/call_engine.go:309 +0x51c
  github.com/tetratelabs/wazero/internal/engine/wazevo.(*callEngine).Call()
      /Users/tim/go/pkg/mod/github.com/tetratelabs/wazero@v1.7.1/internal/engine/wazevo/call_engine.go:142 +0xf4
  github.com/spirit-labs/tektite/wasm.(*Invoker).Invoke()
  ...

This goroutine is calling another exported WASM function (malloc) which attempts to allocate memory.

Previous write at 0x00c030f8d2d0 by goroutine 62479:
  runtime.slicecopy()
      /usr/local/go/src/runtime/slice.go:310 +0x0
  github.com/tetratelabs/wazero/internal/wasm.(*MemoryInstance).Write()
      /Users/tim/go/pkg/mod/github.com/tetratelabs/wazero@v1.7.1/internal/wasm/memory.go:206 +0xa4
  github.com/spirit-labs/tektite/wasm.(*Invoker).prepareBytesArg()
      /Users/tim/Development/tektite/wasm/mgr.go:530 +0x108
  github.com/spirit-labs/tektite/wasm.(*Invoker).Invoke()
  ...
```

Note, I am not calling concurrently on the same Function instance. It seems to me that the underlying module instance (in particular the memory management) is not safe for concurrent calls?

Is my understanding correct? I can fix this by locking all calls to the same module with my own mutex and maintain my own pool of module instances to avoid too much contention, but I wanted to check what the expected semantics are?

Please note my WASM function itself is stateless.

**Comment by anuraaga** [comment]
Hi @purplefox - indeed, most WebAssembly modules are not safe for concurrent invocation, if nothing else, `malloc` generally would not be safe. While it is possible to have a concurrent-safe module (and hence, the concurrency note on `Function` coming into play) using the WebAssembly threads proposal, usually with a compiler target such as `wasm32-wasip1-threads or similar, it is still bleading edge support and I wouldn't recommend it generally, especially for a stateless function.

A `mutex` would be one option, if you imagine needing some concurrency for performance reasons, a `sync.Pool` of instantiated modules can also work well for stateless functions. Here's one example

https://github.com/wasilibs/go-libinjection/blob/main/libinjection_wazero.go#L97

**Comment by purplefox** [comment]
Thanks for the clarification!
