### ISSUE TITLE
Add lint configuration to prevent `import "C"`

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#227]
wazero is by nature a tool that should never include `import "C"`. When code accidentally includes this, it causes mysterious build failures. There's probably a linter that can fail the build on `import "C"` either by import name or preventing CGO another way.

Ex https://github.com/tetratelabs/wazero/actions/runs/1832310806
```
Run go list ./... | xargs -Ipkg go test pkg -c
  go list ./... | xargs -Ipkg go test pkg -c
  shell: /usr/bin/bash -e {0}
  env:
    GO_VERSION: 1.17
    GOROOT: /opt/hostedtoolcache/go/1.17.6/x64
    GOARCH: arm64
go: downloading github.com/twitchyliquid64/golang-asm v0.15.1
# github.com/tetratelabs/wazero/wasm/text
Error: wasm/text/abbreviation_parser.go:48:60: undefined: callbackPosition
Error: wasm/text/abbreviation_parser.go:78:6: undefined: parserPosition
Error: wasm/text/abbreviation_parser.go:106:9: undefined: callbackPositionUnhandledToken
Error: wasm/text/abbreviation_parser.go:107:10: undefined: positionInitial
Error: wasm/text/abbreviation_parser.go:287:38: undefined: callbackPosition
```

**Comment by codefromthecrypt** [comment]
this was due to a spurious `import "C"` on my branch.

**Comment by codefromthecrypt** [comment]
changed the title/desc. thanks for the look @mathetake!

**Comment by mathetake** [comment]
Just curious how one would end up importing "C" accidentally :D

**Comment by codefromthecrypt** [comment]
dude no idea, gremlins maybe

**Comment by codefromthecrypt** [comment]
good point though. even if someone had a spurious "C" and managed to bomb CI, we'd quickly catch it in a code review. probably not worth finding lint over!
