### ISSUE TITLE
Standard `os` package test for Go 1.23rc1 is failing on Windows

### ISSUE THREAD

**Issue by mathetake** [tetratelabs/wazero#2280]
This is a blocker for the next wazero release
https://github.com/tetratelabs/wazero/actions/runs/9767159219/job/26961798739?pr=2277

**Comment by evacchi** [comment]
so it looks like this is -- big surprise -- an issue with FS handling. `TestCopyFS` is the failing test, and you can see it does some special handling in the case of Windows, which means that the FS abstraction is leaky:

https://github.com/golang/go/blob/release-branch.go1.23/src/os/os_test.go#L3372-L3445

This is not the first case when we skip a test on Windows, so I think we can skip this test here 

https://github.com/tetratelabs/wazero/blob/main/internal/integration_test/stdlibs/bench_test.go#L103-L107

```diff
				args = append(args,
					"-test.skip=TestRenameCaseDifference/dir|"+
						"TestDirFSPathsValid|TestDirFS|TestDevNullFile|"+
-						"TestOpenError|TestSymlinkWithTrailingSlash")
+						"TestOpenError|TestSymlinkWithTrailingSlash|TestCopyFS")
```

this makes all the rest of the suite pass; see this test run on my branch https://github.com/evacchi/wazero/actions/runs/9827533698/job/27130327321?pr=57

**Comment by mathetake** [comment]
Good catch Edo!

**Comment by evacchi** [comment]
I still got it 😎
