### ISSUE TITLE
How to use HostFunctionBuilder with multiple goroutines?

### ISSUE THREAD

**Issue by varkey98** [tetratelabs/wazero#2292]
I have a struct which has the following signature
```
type temp struct {
  a int
}

func(t *temp) set(b int) {
  t.a = b
}
```

Now I want to use the wasm module from multiple go routines, so I thought I can precompile the module and function similiar to this
```
// do at init of my program
compiled, _ := r.NewHostModuleBuilder("env").
	NewFunctionBuilder().WithFunc(set).Export("set").
	Compile(ctx)
```

```
// on each go routine, do an instantiation like this
env1, _ := r.InstantiateModule(ctx, compiled, wazero.NewModuleConfig().WithName("env.1"))
env2, _ := r.InstantiateModule(ctx, compiled, wazero.NewModuleConfig().WithName("env.2"))
```

But the above code wont work because `set` is bound to an instance of struct `temp`. How can I make this work?

Edit: complete code
```
package main

import (
	"context"
	_ "embed"
	"fmt"
	"github.com/tetratelabs/wazero"
	"log"
	"sync"
)

// addWasm was generated by the following:
//
//	wasm-tools parse testdata/add.wat -o testdata/add.wasm
//
//go:embed testdata/add.wasm
var addWasm []byte

type temp struct {
	a int
}

func (t *temp) set(a int) {
	t.a = a
}

func main() {
	// Choose the context to use for function calls.
	ctx := context.Background()

	// Create a new WebAssembly Runtime.
	r := wazero.NewRuntime(ctx)
	defer r.Close(ctx) // This closes everything this Runtime created.

	mod, err := r.NewHostModuleBuilder("env").
		NewFunctionBuilder().
		WithFunc(temp.set).
		Export("set").
		Compile(ctx)
	// Compile the Wasm binary once so that we can skip the entire compilation time during instantiation.
	compiledWasm, err := r.CompileModule(ctx, addWasm)
	if err != nil {
		log.Panicf("failed to compile Wasm binary: %v", err)
	}

	var wg sync.WaitGroup
	const goroutines = 50
	wg.Add(goroutines)

	// Instantiate the Wasm module from `compiledWsam`, and invoke the exported "add" function concurrently.
	for i := 0; i < goroutines; i++ {
		go func(i int) {
			defer wg.Done()

			tmp := &temp{}
			// What I'd like to do here would to pass an object reference so that when my wasm code calls 'set',
			// it'd be equivalent to a method call (like somehow pass tmp.set()
			_, err = r.InstantiateModule(ctx, mod, wazero.NewModuleConfig().WithName(""))
			instance, err := r.InstantiateModule(ctx, compiledWasm, wazero.NewModuleConfig().WithName(""))
			if err != nil {
				log.Panicf("[%d] failed to instantiate %v", i, err)
			}

			// Calculates "i + i" by invoking the exported "add" function.
			result, err := instance.ExportedFunction("add").Call(ctx, uint64(i), uint64(i))
			if err != nil {
				log.Panicf("[%d] failed to invoke \"add\": %v", i, err)
			}
			
			// and here, the tmp.a would be set from wasm module
			fmt.Println(tmp.a)

			// Ensure the addition "i + i" is actually calculated.
			expected := uint64(i * 2)
			if result[0] != expected {
				log.Panicf("expected %d, but got %d", expected, result[0])
			}

			// Logs the result.
			fmt.Println(expected)
		}(i)
	}

	wg.Wait()
}
```

**Comment by varkey98** [comment]
Is the  only option to do a recompilation of the function again and again?

**Comment by ncruces** [comment]
Your chances of getting useful help will increase significantly if you post a more complete example of what you're trying to do.

Code for the host (the thing that uses wazero to load a Wasm module) and for the guest (the thing the Wasm module is built from).

That said…

`WithFunc` takes a function, not a method, so yeah, that's not going to work; `instance.env` is a for an instance you created is a function, though.

I don't see any goroutines, so I have no idea how goroutines relate to any of this.

**Comment by varkey98** [comment]
Sorry for the trouble, added my complete main function

**Comment by mathetake** [comment]
For this exact situation you can use the context parameter so you don't need to create multiple host modules

**Comment by varkey98** [comment]
How do I use the context parameter? I dont see any examples where the exported/imported functions using context. Idea is that I can set the value to context and later read from that right?

**Comment by ncruces** [comment]
Again, `WithFunc(temp.set)` is a compile error, because you're referencing a method, which you can't. To transform method into a function closure, you'd need `tmp.set`, on the `tmp := &temp{}`.

That said, going back to the `context` parameter, please read the `WithFunc` [docs](https://pkg.go.dev/github.com/tetratelabs/wazero#HostFunctionBuilder), to see that the function gets a `context.Context` parameter.

Now try this:
```go
	mod, err := r.NewHostModuleBuilder("env").
		NewFunctionBuilder().
		WithFunc(func(ctx context.Context, b int64) {
			tmp := ctx.Value("key").(*temp)
			tmp.set(int(b))
		}).
		Export("set").
		Compile(ctx)
```

And this:
```go
	tmp := &temp{}
	ctx := context.WithValue(context.Background(), "key", tmp)
	...
```

**Comment by varkey98** [comment]
Thanks a lot. Let me try this out and I think an example like this also should be added to the examples directory, will try to raise a pr myself once I get it working

**Comment by varkey98** [comment]
I tried some benchmarking tests on parallel, when instantiating the function module again and again I get an error stating the module with name env has already been initialised and without any name it's complaining about module:env not found. I thought each go routine should initialise it's own module from this [example](https://github.com/tetratelabs/wazero/blob/main/examples/concurrent-instantiation/main.go), but just moving this line outside the loop solves the crash and the benchmark test executes without any problem
```
_, err = r.InstantiateModule(ctx, mod, wazero.NewModuleConfig().WithName("")) 
```

**Comment by varkey98** [comment]
Judging by this [issue](https://github.com/tetratelabs/wazero/issues/2083) as well, I'd guess its not safe for multiple routines to call into a common functions module, right? In which case how can I solve the above problem, where it complains that `module:env` is not found?

**Comment by varkey98** [comment]
Also I use tinygo for now and how do I use this module as well incase of multiple go routines
```
// Note: testdata/greet.go doesn't use WASI, but TinyGo needs it to
// implement functions such as panic.
wasi_snapshot_preview1.MustInstantiate(ctx, r)
```

**Comment by varkey98** [comment]
Added a complete example [here](https://github.com/varkey98/wasm-example/tree/main). The code runs without any errors, but the output is erroneous, probably owing to concurrency issues related to my module instantiation. @ncruces @mathetake  can you please give me some guidance here?
