### ISSUE TITLE
Instantiate emscripten wasm failed

### ISSUE THREAD

**Issue by zyjblockchain** [tetratelabs/wazero#2300]
**Describe the bug**
instantiate emscripten wasm failed.

**Screenshots**
<img width="807" alt="image" src="https://github.com/user-attachments/assets/b2ec30e2-1a1c-47a7-a779-f750d33f01f1">

**Environment (please complete the relevant information):**
- Go version: v.1.21.1
- wazero Version: latest
- macos m1

wasm file:   
https://2t3uejrf4e22p2jfxpbpvshrle3y3tnx7vb7ix2q3m6oazrihzwq.arweave.net/1PdCJiXhNafpJbvC-sjxWTeNzbf9Q_RfUNs84GYoPm0

**Comment by mathetake** [comment]
see the error which says you are trying to import a module "a". That's you have to deal with by instantiating in that way.

**Comment by zyjblockchain** [comment]
> see the error which says you are trying to import a module "a". That's you have to deal with by instantiating in that way.

Sorry, I didn't understand the error, is it wrong to load the wasm the way I did?

**Comment by ncruces** [comment]
Your Wasm file depends on a module named "a". It imports something - functions? - from module "a". You have not provided this module. You either need to figure out a way not to depend on module "a", or provide module "a".

**Comment by zyjblockchain** [comment]
> Your Wasm file depends on a module named "a". It imports something - functions? - from module "a". You have not provided this module. You either need to figure out a way not to depend on module "a", or provide module "a".

OK thanks
