### ISSUE TITLE
How to reuse memory？

### ISSUE THREAD

**Issue by pandaWall** [tetratelabs/wazero#2303]
My logic now is that every call to the exported function will buf := make(p[]byte,4096) memory, although every call buf = nil, but I find that wazero keeps calling Grow() to expand the memory, causing my process memory to keep increasing.
I want to ask how to reuse memory?

wasm:
`
func payload(d []byte) ([]byte, error){
      buf := make([]byte, 4096)
      fmt.Println(buf)
      buf  = nil
}
`
Host:
wasm.instance.Invoke("payload")

wazero:
func (m *MemoryInstance) WriteString(offset uint32, val string) bool {
	if !m.hasSize(offset, uint64(len(val))) {
		return false
	}
	copy(m.Buffer[offset:], val)
	return true
}

**Comment by pandaWall** [comment]
It seems that only the Grow interface is provided, and no interface for reducing memory is provided。

**Comment by ncruces** [comment]
If you want better help, you need to give us more info into what you're doing, how you're doing it, etc. Like, what do you use to compile Wasm: TinyGo, Go…?

But still, yes, Wasm memory only grows, never shrinks. That's how it is.

Whatever is running inside the Wasm (TinyGo, Go…) should eventually free the memory you're allocating, and start reusing the freed memory. wazero's memory usage won't decrease, but should stabilize.

If you want to be sure you reuse the buffer, though, the easiest way is to keep it in a global variable.
