### ISSUE TITLE
Running into `wasm error: indirect call type mismatch` when using the compiler backend, but not the interpreter

### ISSUE THREAD

**Issue by zshipko** [tetratelabs/wazero#2313]
**Describe the bug**
I am running a wasm module that uses `call_indirect` - when using the interpreter it runs successfully, but when using the compiler it fails with `wasm error: indirect call type mismatch` - it also runs successfully on wasmtime, so I think this could be a compiler bug.

**To Reproduce**
I've uploaded the wasm here: [wasm.zip](https://github.com/user-attachments/files/16985989/wasm.zip)

Then using the extism CLI: https://github.com/extism/cli/ (can be installed by cloning the repo and running `go install ./extism` from the root of the repo)
```
EXTISM_ENABLE_WASI_OUTPUT=1 extism call ./plugin.wasm req --allow-host '*' --input "https://extism.org" --wasi --link import_module=import_module.wasm --log-level info
```

Note: the current CLI uses wazero 1.7, but I've also tested using the latest code on `main` with the same result.

**Expected behavior**
The call should return successfully instead of throwing the type mismatch error

**Environment (please complete the relevant information):**
- Go version: 1.22.6
- wazero Version:tested on 1.7 and the latest main (`58488880a334e8bda5be0d715a24d8ddeb34c725`)
- Host architecture: amd64
- Runtime mode: compiler

**Additional context**
If I comment out lines 3558-3581 in `internal/engine/wazevo/frontend/lower.go` it works as expected.

**Comment by mathetake** [comment]
looks like a bug - do you happen to have arm64 machine and being able to check if this happens on arm64 as well or not?

**Comment by zshipko** [comment]
I can run this on an arm64 mac later this evening and will let you know how it goes

**Comment by mathetake** [comment]
sg, thank you!

**Comment by zshipko** [comment]
Just ran it on arm64 macos and got the same result: 

```
Error: wasm error: indirect call type mismatch
wasm stack trace:
	.$11042(i32,i64) i64
	.$131(i32,i32,i32,i32)
	.$74(i32) i32
	.$130(i32,i32,i32) i32
	.$1576(i32,i32,i32) i32
	.$251(i32,i32,i32,i32) i32
	.$252(i32,i32,i32) i32
	.$2875(i32,i32,i32) i32
	.$816(i32,i32,i32) i32
	.$2872(i32,i32,i32,i32,i32,i32) i32
	.$254(i32,i32,i32,i32) i32
	.$247(i32,i32,i32,i32,i32) i32
	.$251(i32,i32,i32,i32) i32
	.$252(i32,i32,i32) i32
	.$2875(i32,i32,i32) i32
	.$816(i32,i32,i32) i32
	.$2872(i32,i32,i32,i32,i32,i32) i32
	.$254(i32,i32,i32,i32) i32
	.$247(i32,i32,i32,i32,i32) i32
	.$251(i32,i32,i32,i32) i32
	.$252(i32,i32,i32) i32
	.$10591(i32,i32,i32)
	.$11031(i32) i32
	.$11051() i32
```

**Comment by mathetake** [comment]
thanks, that helps - meaning i think this is not really a compiler but seems more of a "compiler engine" bug

**Comment by mathetake** [comment]
curious about old compiler with amd64...

**Comment by evacchi** [comment]
looks like it's working there as well (still investigating...)

**Comment by evacchi** [comment]
humm, no luck so far, I turned the UDFs into BRKs, it's definitely loading 0x2, but the offsets seem ok to me, so I wonder if the table has been filled incorrectly.


```
->  0x129ecbbc0: ldur   x8, [x8]
    0x129ecbbc4: lsl    w9, w2, #3
    0x129ecbbc8: mov    w9, w9
    0x129ecbbcc: add    x8, x8, x9
Target 0: (extism-cli) stopped.
(lldb) reg r x8
      x8 = 0x0000014006a580c0
(lldb) expr *reinterpret_cast<long*>($x8+16)
(long) $32 = 1
(lldb) reg r x2
      x2 = 0x0000000000000000
```
0x0000014007c5db10

**Comment by evacchi** [comment]
ok I should have a proper PR tomorrow with tests etc., the typeIDs would be propagated from the import signature, after verification

**Comment by mathetake** [comment]
Good
