### ISSUE TITLE
emscripten_stack_get_current not exported (recovered by wazero)

### ISSUE THREAD

**Issue by 88250** [tetratelabs/wazero#2317]
**Describe the bug**

Can't parse the file.

[sample.pdf](https://github.com/user-attachments/files/17077585/sample.pdf)

```
[emscripten_stack_get_current not exported (recovered by wazero)
wasm stack trace:
	env.invoke_iii(i32,i32,i32) i32
	.$1954(i32,i32,i32,i32,i32) i32
	.$1568(i32,i32,i32,i32,i32) i32
	.$1508(i32,i32,i32,i32,i32,i32,i32) i32
	.$2306(i32,i32,i32,i32) i32
	.$2350(i32,i32,i32,i64) i32
	.$2433(i32,i32)
	.$2404(i32) i32
	.$2411(i32) i32
	.$2436(i32,i32,i32) i32
	.$3919(i32,i32) i32
	.$3819(i32,i32) i32
	.$3818(i32)
	.$3875(i32,i32)
	.$3575(i32)
	.$5025(i32,i32) i32]
```

**To Reproduce**

https://github.com/siyuan-note/siyuan/blob/3eec016723f52f3a679fb99854ae33e8fe20e42a/kernel/model/asset_content.go#L883

**Expected behavior**

Parse sucesses.

**Screenshots**

**Environment (please complete the relevant information):**
- Go version: go1.23.1
- wazero Version: 1.8.0
- Host architecture: amd64
- Runtime mode: 

**Additional context**

**Comment by mathetake** [comment]
Use the latest emscripten https://github.com/tetratelabs/wazero/pull/2290

**Comment by 88250** [comment]
Hello, can you give me more detailed instructions? I have never manually installed emscripten.

**Comment by ncruces** [comment]
Your asking for free tech support at this point.

You seem to be using `github.com/klippa-app/go-pdfium`. They use [wazero 1.7.3](https://github.com/klippa-app/go-pdfium/blob/999a43a90b467d46e0d5a2c2cda5876cc1167b37/go.mod#L13), you upgraded to v1.8.0. don't do that. Wait for them to upgrade.

**Comment by 88250** [comment]
It is indeed a version mismatch problem, thank you very much for your help!
