### ISSUE TITLE
JIT: replace golang-asm with a thread-safe one (from scratch)

### ISSUE THREAD

**Issue by mathetake** [tetratelabs/wazero#233]
In aarch64, golang-asm is not thread-safe, and [the multi-goroutine engine test case](https://github.com/tetratelabs/wazero/blob/0186e41b27e572964e9f018cd9cd8a655eb6d3f8/tests/engine/adhoc_test.go#L67-L87) actually fails if gorutine num > 1.

We could introduce a mutex in engine.Compile and lock the golang-asm usage, then the test passes, but it's not ideal.

Instead, we should replace golang-asm with a thread-safe, but there's not alternative out there. 

That means we have to implement an assembler from scratch.

**Comment by mathetake** [comment]
In anyway, removing golang-asm dependency is good and well aligned with our main goal "zero dependency".

**Comment by codefromthecrypt** [comment]
FWIW I totally agree with this change

**Comment by codefromthecrypt** [comment]
please make it internal though :) I don't expect we need to support this api for third party use

**Comment by mathetake** [comment]
done with amd64.. now is the time to enjoy arm64!
