### ISSUE TITLE
Support Using `experimental.ImportResolver` with host modules

### ISSUE THREAD

**Issue by clarkmcc** [tetratelabs/wazero#2330]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to provide different sets of host functions to each instantiated module.

**Describe the solution you'd like**
Wazero currently has experimental support for an [import resolver](https://github.com/tetratelabs/wazero/blob/main/experimental/importresolver_example_test.go). I'd like to be able to use this with host modules, but host modules are not allowed to be anonymously named.

https://github.com/tetratelabs/wazero/blob/6016a705fa6077f517731d4ce148a82968de02dd/runtime.go#L84

**Additional Context**
[Slack thread](https://gophers.slack.com/archives/C040AKTNTE0/p1728321421330809) that led up to this request.

**Comment by mathetake** [comment]
> I'd like to be able to provide different sets of host functions to each instantiated module.

You should be achieve this without the importResolve - just use the context and switch the behavior based on the context. That way, there's no need to "swap" host functions.

**Comment by clarkmcc** [comment]
@mathetake worked perfect, thanks!
