### ISSUE TITLE
Allow wazero to build Wasm modules via code

### ISSUE THREAD

**Issue by judah-caruso** [tetratelabs/wazero#2351]
**Is your feature request related to a problem? Please describe.**

There's a niche that hasn't been met with Go libraries to programmatically generate and validate Wasm modules. I think wazero has most of the tools necessary to accommodate this and would make it the only pure Go library to allow building *and* executing Wasm.

**Describe the solution you'd like**

Functions to build a Wasm module via code (WAT and Binary, similar to Binaryen). Additionally, validation to ensure the generated Wasm doesn't have malformed instructions, incorrectly typed/out-of-bounds locals, missing imports, etc. 

I don't believe wazero needs provide the ability to optimize modules.

A pseudo code example of how this could look:
```go
func main() {
  mod := wazero.NewModuleBuilderWithConfig(wazero.ModuleBuilderConfig{
    Features: // large memory, simd, etc. (only needs to be features wazero supports)
  })

  // generate the function: $_main(i64, i64) i64
  params := mod.NewType(wazero.TypeI64, wazero.TypeI64) // tuple of (i64, i64)
  results := wazero.TypeI64

  block := mod.NewBlock(
    // return type of block
    wazero.TypeI64,
    
    // block instructions:
    // $0 = $0 + $1
    mod.LocalSet(0,
      mod.Binary(i64.Add,
        mod.LocalGet(0, wazero.TypeI64),
        mod.LocalGet(1, wazero.TypeI64))),

    // return $0
    mod.Return(mod.LocalGet(0, wazero.TypeI64)),
  )

  mod.AddFunction("_main", params, results, block)
  mod.SetStart("_main")
  
  // Ensure module is valid before building:
  if err := mod.Validate(); err != nil {
    log.Fatal(err)
  }
  
  wat, err := mod.BuildWat() // Returns s-expression WAT module as a string
  bin, err := mod.BuildBinary() // Returns Wasm binary module as []byte

  // Now the module can be executed by wazero, put through wasm-opt, etc.
}
```

**Describe alternatives you've considered**

In the past I've created bindings for Binaryen and wrote a wrapper that looked similar to the example given. However, this required CGo or [purego](https://github.com/ebitengine/purego) which made the library much more difficult/impossible to use as it requires libstdc++ and can't be properly linked on Windows.

**Additional context**

I believe this feature opens up many interesting possibilities for wazero and would allow full Wasm toolchains to be built in Go.

**Comment by ncruces** [comment]
Things that (widely!) expand the scope of the project are very unlikely to gain traction. L

Is there any reason you can't do that on top of wazero in your own repo?

Or as a segway to what you said, can't you compile binaryen to Wasm (e.g. with `wasi-sdk`), and make a nice Go API to wrap it using wazero?

The [users page](https://wazero.io/community/users/) has about a dozen examples of C/C++ libraries wrapped using wazero.

**Comment by mathetake** [comment]
sorry, out of the scope!
