### ISSUE TITLE
run wasm failed use tinygo 0.35

### ISSUE THREAD

**Issue by labulakalia** [tetratelabs/wazero#2352]
**Describe the bug**
```
// dir wazero/examples/basic
// use tinygo 0.35 rebuild add.go to add.wasm
tinygo version
tinygo version 0.35.0 darwin/amd64 (using go version go1.23.4 and LLVM version 18.1.2)
tinygo build -o add.wasm -scheduler=none --no-debug --target=wasi add.go

go run add.go 7 9
2024/12/22 13:37:44 failed to call add: module closed with exit_code(0)
panic: failed to call add: module closed with exit_code(0)

goroutine 1 [running]:
log.Panicf({0x9ccae0a?, 0x9d99850?}, {0xc00002ff28?, 0xc000090f50?, 0x25ab?})
        /Users/labulakalia/sdk/go/src/log/log.go:439 +0x65
main.main()
        /Users/labulakalia/workerspace/wazero/examples/basic/add.go:60 +0x2f9
exit status 2
```
**To Reproduce**
Description of the host and wasm code that reproduces the behavior.
Smoothest debugging will be if you can share a repository with the
actual code.

**Expected behavior**

**Screenshots**

**Environment (please complete the relevant information):**
- Go version: go version go1.23.4 darwin/amd64
- wazero Version: master
- Host architecture: amd64
- Runtime mode: [e.g. interpreter or compiler]

**Additional context**

**Comment by mathetake** [comment]
It's not a bug - see the error message saying your module exited with zero.
