### ISSUE TITLE
Support MMap on Windows for JIT engine

### ISSUE THREAD

**Issue by MutatePat** [tetratelabs/wazero#269]
An issue in using the JIT engine on Windows, is the lack of support of MMap, after looking at MSDN and GitHub, we can support MMap in the same fashion as this portable library - https://github.com/edsrzf/mmap-go/blob/main/mmap_windows.go

We can either introduce the portable mmap library as a dependency, or reimplement the features.

**Comment by codefromthecrypt** [comment]
thanks for the background! I poked around and found another one from @hslam

https://github.com/hslam/mmap/blob/master/mmap_windows.go

I'll mark this one help-wanted as personally my windows laptop isn't near enough for the next few days

**Comment by codefromthecrypt** [comment]
seems like there are a lot of these things out there :D

https://github.com/prometheus/prometheus/blob/main/tsdb/fileutil/mmap_windows.go
https://github.com/oschwald/maxminddb-golang/blob/main/mmap_windows.go
https://github.com/dgraph-io/ristretto/blob/master/z/mmap_windows.go
https://github.com/Darksidis/skyton/blob/master/rclone/lib/mmap/mmap_windows.go
https://cs.opensource.google/go/x/exp/+/master:mmap/mmap_windows.go

**Comment by codefromthecrypt** [comment]
Thanks for the advice @MutatePat! Personally, I would probably not copy any of these, but review all of them for homework and make new impl here including tests. This also helps as many times projects get abandoned or pinned to go versions etc and we wouldn't add that liability for a small amount of code. We have other projects that have windows hooks (ex func-e) so it isn't the first time either.

On CI, I think one PR can and should solve both as the test dimension isn't technically difficult either. Regardless, we won't drop this and thanks for paying attention! If no-one adds this by Friday, I can get my laptop and look into it then.

**Comment by codefromthecrypt** [comment]
incidentally, the first suggestion is the most maintained option and more than others I found later. They also have a unit test for anonymous mmap, which is iiuc what we need https://github.com/edsrzf/mmap-go/blob/main/mmap_test.go#L154-L173

**Comment by codefromthecrypt** [comment]
I'm going to wait until #293 is complete before implementing windows as how code regions are handled might change between now and then.
