### ISSUE TITLE
Support deinstantiation (mod.Close)

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#293]
We need to eventually handle long lived processes, and graceful shutdown. If we had a way to deinstantiate a module, I think we can also handle a WASI quit signal scoped to module instead of the host process (#290)

I think we should make a new type that implements ModuleExports called `wazero.InstantiatedModule` (we maybe need this for host also, but let's start with normal modules). The only additional function there would be .Close and this would have the following effects.

* set a goroutine visible status on the internal moduleInstance  `closeCalled`
  * this may need to be an array of length one to ensure visibility across goroutines, and 1 means closeCalled
* make shared implementations err if they see this status which will cause existing functions to exit
  * make engine.call implementations check this status prior to invoking new functions and return an error (I think this handles table also as table is only call_indirect and not exposed otherwise)
  * make memory, global implementations check this status before read/write and return an error
* ensure calls begin with a `CancelContext` added to the callEngine, and invoke that hook so that any host functions doing I/O finish.
  * this could possibly be limited to wrapping the context in `wazero.StartWASICommand` as maybe non-wasi shouldn't be doing I/O anyway
* remove all the references for this module in Store added by instantiate
  * ensure nice errors when calling an imported function, memory, table or global that was removed

**Comment by codefromthecrypt** [comment]
This would also be needed for wapc-go (cc @pkedy) because it is otherwise a memory leak. For example, modules are instantiated with instance counters, which I assume would eventually run out of memory depending on the scope and frequency of creation (remember memory is required by WASI and minimum memory is 64KB).

```
// Instantiate creates a single instance of the module with its own memory.
func (m *Module) Instantiate() (wapc.Instance, error) {
	moduleName := fmt.Sprintf("%d", atomic.AddUint64(&m.instanceCounter, 1))
```

**Comment by codefromthecrypt** [comment]
There's a not really documented thing in AssemblyScript that would also needs this for abort handling. If someone can find docs on it please do!

```go
// envAbort is the AssemblyScript abort handler.
// Ex in WebAssembly 1.0 (MVP) Text Format:
//	(import "env" "abort" (func $~lib/builtins/abort (param i32 i32 i32 i32)))
func (t *thing) envAbort(ctx wasm.ModuleContext, messageOffset, fileOffset, line, col uint32) {
	t.module.Close()
}
```

Note: AssemblyScript maybe maps this function to WASI sigabrt ...

**Comment by mathetake** [comment]
yeah we also tweak Engine interface so that we can unmap the MMapped memory regions

**Comment by mathetake** [comment]
so the preliminary work #294 has just landed, so the next is to make store goroutine-safe
