### ISSUE TITLE
use  go get github.com/tetratelabs/wazero  error

### ISSUE THREAD

**Issue by diwuwudi123** [tetratelabs/wazero#350]
>go get github.com/tetratelabs/wazero
go: downloading github.com/tetratelabs/wazero v0.0.0-20220309023913-50d9fa58a177
//go:build comment without // +build comment
data/gopath/pkg/mod/github.com/tetratelabs/wazero@v0.0.0-20220309023913-50d9fa58a177/internal/wasm/interpreter/interpreter.go:15:2: //go:build comment without // +build comment
data/gopath/pkg/mod/github.com/tetratelabs/wazero@v0.0.0-20220309023913-50d9fa58a177/config.go:8:2: //go:build comment without // +build comment

What is this problem?

**Comment by mathetake** [comment]
This means you are using older go versions. We are not supporting Go older than 1.16(#317). So could you upgrade your Go and try again? Thanks!
