### ISSUE TITLE
wasi: recommended usage for module re-use

### ISSUE THREAD

**Issue by pims** [tetratelabs/wazero#364]
Hi 👋 ,

The wazero public interface has been going through major improvements recently, and before it gets finalized, I was wondering if you could shed some light on how how to re-use a "wasi module ".

Note: if this use-case is not something you'd want to support, I fully understand, I'm just trying to make sure I'm not missing anything obvious.

```go
r := wazero.NewRuntimeWithConfig(cfg)
decoded,  := r.CompileModule(source) // source parsed only once 


// this configuration is unique to each invocation based on message content
wasiConfig := &wazero.WASIConfig{
		Stdin:  stdinBuf,
		Stdout: stdoutBuf,
		Stderr: stderrBuf,
		Args:   []string{"rotate", "angle=90", "dir=cw"}, // <-- this comes from the body of the message received.
	}

if _, err := r.InstantiateModule(wazero.WASISnapshotPreview1WithConfig(wasiConfig)); err != nil {
		log.Fatal(err) // 👈🏼 this fails for the second r. r.InstantiateModule  call with `module wasi_snapshot_preview1 has already been instantiated`
	}
if _, err := wazero.StartWASICommand(r, decoded); err != nil {
		log.Fatal(err)
}
```

I can't really change the module name since it's required for wasi support.
```
(import "wasi_snapshot_preview1" "args_get" (func $fimport$1.linked.1052 (param i32 i32) (result i32)))
```

I understand how to achieve this with a regular (non wasi) wasm module, but I was hoping to not have to marshal strings via wasm memory.

One viable avenue is to wrap `WASIConfig` into a message/context aware struct and replacing the static args/env values.
Is that what you'd recommend?

Thanks!

**Comment by codefromthecrypt** [comment]
Agree and this is the right time to fix this. The config for env/arg isn't at the right scope indeed. It should be a function of the importing module (possibly its memory), as global only makes sense with one module

**Comment by codefromthecrypt** [comment]
this outta do it https://github.com/tetratelabs/wazero/pull/367
