### ISSUE TITLE
Add CI for the "FROM scratch" platform

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#385]
Per https://github.com/tetratelabs/wazero/pull/384 wazero supports scratch. scratch is different than "distroless" as the latter still includes an operating system (albeit slim, often debian). We should be able to add a `scratch` platform to our CI dimensions that run spec tests, and verify that on the same archs as ubuntu.

one way is to build a docker image `FROM scratch` during CI, which copies the spec binary and sets the entrypoint to run it. Another way could be to have a standing `FROM scratch` image with a volume mount which would house the test binary. Other ways are possible too. Regardless, it would be best to run this like a normal OS dimension even if it relies on Docker, so that the CI output looks the same as an OS.

**Comment by mathetake** [comment]
So I was looking at how we can combine separate prebuilt multiple test binaries into one single executable (as each package tests are compiled to separate binary with `go test -c`) in order to avoid installing like `sh` on SCRACH, but I can't think of the better solution now.

**Comment by codefromthecrypt** [comment]
could we mount the directory as a volume and overwrite the entrypoint shell-side? (ex a loop in the GH action for I in *.o; do docker run --entrypoint $I...

**Comment by mathetake** [comment]
oh that's good
