### ISSUE TITLE
Possible to override resolver behaviour?

### ISSUE THREAD

**Issue by neilalexander** [tetratelabs/wazero#39]
... so that instead of having to call `AddGlobal`, `AddHostFunction` etc for everything that we want to inject, that we can instead set callbacks which return function pointers, allowing us to resolve missing functions, missing globals etc?

**Comment by codefromthecrypt** [comment]
would you mind giving a before and after code snippet for what motivated you to raise the issue? I bet you felt annoyed at a call site you'd love to have better. can you give an example of that?

(ps you can also ignore my feedback, I'm just trying to learn how people are using this, so would appreciate it)

**Comment by mathetake** [comment]
Thanks @neilalexander. That kind of API sounds great, but I would like to better understand your usecase and API you have in your mind. Then we could come up with the concrete API before we merge in.

**Comment by neilalexander** [comment]
I have a project which has a runtime where ideally we'd be able to control which functions and globals are available at runtime based on permissions/capabilities (which can change during execution). 

Right now we only have `Add` functions and no ability to `Remove` them later, and even if we did have `Remove` functions, it would turn into a bit of a nightmare tracking which things have been exported and removed from a given VM safely.

I don't have a *specific* API shape in mind here, but being able to pass in a callback which gets notified when resolving a function or global hasn't already been `Add`ed so that we can call custom functions and/or return custom values would be *amazing*.

**Comment by mathetake** [comment]
Hi @neilalexander, I just forgot to reply here.. we are planning to refactor the API in anyway https://github.com/tetratelabs/wazero/issues/170, so we will revisit this issue after that. I will keep you posted! Thank you!

**Comment by neilalexander** [comment]
Thanks so much for the update, I shall stay tuned!

**Comment by codefromthecrypt** [comment]
I think this is a relic as the API is wildly different since this was opened. Please open a new issue for any features you need!
