### ISSUE TITLE
Add option to define maximum memory/cpu 

### ISSUE THREAD

**Issue by inkeliz** [tetratelabs/wazero#417]
Currently, seems that any code can increase the memory without any soft-limit. That means that one WASM with `for { r = append(r, make([]byte, 10_000)...) }` will run and will take, eventually, all the memory available.

I would like to limit each runtime/wasm to have ~10MB, for example. Then the wasm must panic/crash due to "Out-Of-Memory" and the `grow` call must fail. 

_Also, would be interesting to limit the CPU usage, but I think it's hard to track the CPU usage, that could be more useful when WASM supports thread directly._

**Comment by codefromthecrypt** [comment]
I suspect that growing to memory.max (pages aka 64KB/page) is enforced per module. So, I suppose what you mean is to have a runtime config for a max for any instantiated module. Since memory so often leaves max undefined[1], it may be the case that this has to fail at runtime instead of instantiation time. Do I understand correctly?

[1] https://www.w3.org/TR/wasm-core-1/#memory-types%E2%91%A0

**Comment by codefromthecrypt** [comment]
Another way, if you aren't using multiple modules per runtime, is to allow a configuration of memory.max when it wasn't set by the source wasm. This would be simpler and have the same effect.

**Comment by codefromthecrypt** [comment]
ex.

```go
m, err := r.CompileModule(source)
m.WithMemoryMax(5) // 5*64KiB max unless the existing max was less.
```

**Comment by inkeliz** [comment]
> I suspect that growing to memory.max (pages aka 64KB/page) is enforced per module. So, I suppose what you mean is to have a runtime config for a max for any instantiated module. Since memory so often leaves max undefined[1], it may be the case that this has to fail at runtime instead of instantiation time. Do I understand correctly?
> 
> [1] https://www.w3.org/TR/wasm-core-1/#memory-types%E2%91%A0

I think you get the idea. I would like to enforce that any code can only take ~10MB, for example. It either crashes on `initialization` (when the minimum memory is larger than the maximum) or during runtime (when calling `grow`).

----------

I did one test modifying the `internal/wasm/memory`:

https://github.com/tetratelabs/wazero/blob/40c09b832fbf6f0bde73cb4736244a231ca3027b/internal/wasm/memory.go#L15

Modifying to  `MemoryMaxPages = uint32(192)` seems to force my wasm to crash when using ~8MB, which is expected. So, it seems to work. However, that package is private.

**Comment by codefromthecrypt** [comment]
So, the limit is applied per-memory and since there can only be one memory per module, the simplest and cheapest way is to limit this per module. I'll raise a configuration to backfill memory.max via runtimeconfig with notes on this later today. thanks for the elaboration!

**Comment by codefromthecrypt** [comment]
https://github.com/tetratelabs/wazero/pull/419
