### ISSUE TITLE
Implement JIT to improve performance

### ISSUE THREAD

**Issue by pozen** [tetratelabs/wazero#42]
Currently, wazero runs in an interpreted mode. This is not as fast as JIT. We should implement JIT and benchmark performance.

**Comment by mathetake** [comment]
Hi @pozen, thank you for playing with this project. And yes, there's currently no optimization done yet and must admit it is slow. But as I put in [README](https://github.com/mathetake/gasm#background), we are planning to optimize towards performance now, given that the implementation is 100% compatible Wasm specification while having no dependency. Thank you!

**Comment by pozen** [comment]
@mathetake Thanks for your reply. I'm looking forward to seeing your results. 

Before this, we picked yaegi to make our plugin system.
