### ISSUE TITLE
add VS test for image size delta

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#424]
As of latest commit, wazero adds <1.5MB to the size of a static compiled amd64 binary. This is incredible considering most alternatives are larger, depend on even larger shared libraries, and depend on an even larger base OS image.

We should be able to have a "VS" test that compares the actual image size without using docker. One way is to compile and execute a 1+1=2 wasm go app, fork and exec it, then look at the memory size of the process. Assuming the memory size includes the size of shared libraries, we should be able to get an honest comparison of base image overhead from this.

**Comment by codefromthecrypt** [comment]
@wuhuizuo I know you have a repo comparing runtimes. Any ideas on this part? It is a big factor when comparing alternatives.

**Comment by wuhuizuo** [comment]
- Memory usage compare can be done with benchmark test, but the tests should be sufficient.
- wasm runtime compiled runner compiled binnary size comparing can be done with example host call wasm example.
 
But I think *it is not meaningful to compare with other runtime implements*, the fllowing factors:
- core implementing lang may be different.
- implemented features may be different.

The runtime size is sensitive? I think the wasm app size is more important. recently I try rust and tinygo to compile wasm32-wasi, rust wasm file size is several times larger than tinygo wasm file size.

Maybe users care more on wasm app size in host run env.

@codefromthecrypt

**Comment by codefromthecrypt** [comment]
interesting points and made me think of things to comment:

### Runtime size in abstract may only matter when it is huge:

One thing about runtime size is for example I've seen base images with one runtime being 170MB significantly larger than for example a slim java image. I think the base binary/image size matters in extreme cases more than when they aren't extreme, or small in comparison to the wasm itself.

### Runtime size matters a lot considering how often host functions are used

Since so little implementation is handled by wasm itself (ex only core functions), the runtime has to embed other features. Even if it only supposed WASI, for example, bugs require rebuilding or redeploying the runtime. While I haven't seen too many go projects, every one I have seen uses host functions, which means they need to be redeployed. If the runtime is linked to shared libraries these are not only more bytes to move around, but also more base image sensitive.

### Wasm size maybe isn't discussed enough

Great point about wasm size for seemingly equivalent functions. It can be staggering and people should be aware of it as that's likely moved around more often than the runtime. While this can be trimmed down with optimization tools, it is easy for one wasm binary to be larger than the runtime (at least ours).


What do you think?

**Comment by codefromthecrypt** [comment]
closing from lack of interest
