### ISSUE TITLE
Add example for how to do multiple returns with "result parameters"

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#433]
WebAssembly 1.0 restricts results to a single value. The secret way people get around this is by passing a "result parameter" which is a memory offset to write the Nth return value. As this is easier to do than say, we need to add an example so we can use it to help instruct people.

**Comment by pretty66** [comment]
Great, I desperately need this example, when can I see it

**Comment by codefromthecrypt** [comment]
@pretty66 Here's an example from WASI, for now. I'll start on an end-to-end in the examples directory tomorrow.

```go
// this function passes 3 parameters and returns 1. the 3rd parameter is where to write the second
// result (first result is the real result: errno aka uint32)
func (a *wasiAPI) ClockTimeGet(m api.Module, id uint32, precision uint64, resultTimestamp uint32) Errno {
	// The caller passes an offset in memory to write the timestamp and know that
	// it will be 8 bytes. Remember host functions use the memory from the calling
	// module.
	if !m.Memory().WriteUint64Le(resultTimestamp, a.timeNowUnixNano()) {
		return ErrnoFault
	}
	return ErrnoSuccess // actual returned result, note: success is zero!
}
```

**Comment by codefromthecrypt** [comment]
another thing that might be helpful is a while back I annotated this text format example, as I often got my eyes crossed on how return parameters work https://github.com/tetratelabs/wazero/blob/main/wasi/testdata/wasi_arg.wat

**Comment by codefromthecrypt** [comment]
cc @neilalexander as you had asked about multiple returns.

**Comment by codefromthecrypt** [comment]
haven't forgotten about this, just got stuck in a rut luckily out of. should be able to get this done in next day or two

**Comment by codefromthecrypt** [comment]
OK for general wasm programming (including string manip), I've updated the art of wasm repo here as that's how I learned it and it is too much content to do here https://github.com/summerwind/the-art-of-webassembly-go/pull/2

I still owe multiple returns and error handling here, as it isn't covered in the book!

**Comment by codefromthecrypt** [comment]
I will add opt-in support for the "multi-value" post 1.0 feature ahead of documenting this as many implementations support it. https://github.com/WebAssembly/proposals/blob/main/finished-proposals.md

**Comment by codefromthecrypt** [comment]
WIP eta tomorrow https://github.com/tetratelabs/wazero/pull/446

**Comment by codefromthecrypt** [comment]
update: will be another day as there are many tests to complete.

**Comment by codefromthecrypt** [comment]
ok complete with example, merging after any more review feedback https://github.com/tetratelabs/wazero/pull/446

**Comment by codefromthecrypt** [comment]
https://github.com/tetratelabs/wazero/blob/main/examples/results_test.go
