### ISSUE TITLE
Use Option pattern for configuration (e.g., RuntimeConfig)

### ISSUE THREAD

**Issue by anuraaga** [tetratelabs/wazero#480]
Currently `RuntimeConfig` uses a fluent builder pattern. I have seen many Go projects use an Option pattern where all the options are passed into the factory

https://github.com/openzipkin/zipkin-go/blob/master/tracer_options.go#L42

I guess this is is fairly idiomatic. I think this is because it allows returning an error for bad parameters.

```go
r, err := wazero.NewRuntime(
  wazero.WithInterceptor(...),
  wazero.WithCompilationCache("/tmp/wazero/cache")
)
if err != nil {
  return fmt.Errorf("did I forget to set cache directory to writable: %w", err)
}
```

The only way to do any parameter validation with fluent is to basically lose fluentness
```go
r, err := wazero.NewRuntime()
r, err = r.WithInterceptor(...)
if err != nil {}
r, err = r.WithCompilationCache(...)
if err != nil {}
```

The mid ground of only returning `(RuntimeConfig, error)` on specific methods that have possible errors is probably even worse for losing symmetry.

Currently, none of the configuration seems to really need validation but I propose switching to the Option pattern now to allow adding options that deserve validation in the future.

**Comment by codefromthecrypt** [comment]
FWIW, we were aware of the option pattern (and removed it) before doing this. The reason was indeed about errors and how you need to break many lines and a railroad of `if err` doing that, even if there is no error likely.

Right now, errors are deferred to evaluation time, and documented as such. For example, things that can cause a compile error err on compile. This is important to know because error evaluation is often not possible at the time you  assign config, nor is it a good idea to eagerly materialize it just to force an error.

**Comment by codefromthecrypt** [comment]
there were several issues on config types in the past, and deferring error returns until the error would be relevant. This is one of them https://github.com/tetratelabs/wazero/pull/280

I just looked at RATIONALE.md and I think we should keep this issue open until I raise a PR consolidating the major points. Ex we already have rationale about not doing some other old go norms like exporting everything. We don't have one on the Option type thing, and there are some fairly significant reasons why that doesn't exist. My bad for not adding it to the doc. Will do!

**Comment by anuraaga** [comment]
My understanding is that the main entry point is less `NewEngine` and more `InitializeModule`, so it's simpler to keep errors in the latter where we have more context such as the module itself. Makes sense, especially since on a second thought, an up front error could still be added to NewEngine, not NewConfig, without changing fluent config if we wanted to later, oops.

**Comment by codefromthecrypt** [comment]
So the public type you are referring to would be NewRuntime. Typically we don't return errors on constructors, and there's currently no reason to either. Forcing an error there would make the code unnecessarily hard to use iotw and the potential error cases (currently zero) will still mean most are deferred to the functions on runtime which already err.

**Comment by codefromthecrypt** [comment]
One of the more important points is that we added "CompileModule" used to be "ValidateModule" which allows the largest amount of errors to be known before use. Most errors have to do with the code being decompiled and they are indeed runtime dependent. I think the docs on that already describe that those who want to be extra safe should use that as it materializes all sorts of different errors you can catch up front. I'll add this to the RATIONALE also as without this function things would be worse for sure.
