### ISSUE TITLE
Is it possible to grow api.Memory programmatically?

### ISSUE THREAD

**Issue by danielpacak** [tetratelabs/wazero#483]
There are scenarios where we may grow shared memory programmatically:

```go
module, _ := v.runtime.InstantiateModuleFromCode(ctx, policy)
module.Memory().Grow(1) // error: unresolved reference 'Grow'
```

However, the `Grow` method is not defined on the `api.Memory` interface. It's only defined on the internal `MemoryInstance` struct:

```go
func (m *MemoryInstance) Grow(newPages uint32) (result uint32) {
	// [...]
}
```

Is it intentionally designed like that, or there is another API to grow shared memory?

**Comment by codefromthecrypt** [comment]
memory.grow is an instruction supported in wasm, just we haven't exported it into the host api.

Generally, we try to keep the API relevant by waiting for people to ask for things that aren't obvious. Can you mention the specific use cases you have in mind (curious)?

@mathetake is there anything tracking memory in JIT that exposing this as a host api would endanger? I guess the main thing is that if we put it in the host api it could be called outside the scope of a function..

**Comment by codefromthecrypt** [comment]
ps the current workaround would be to make a function defined in %.wat that does memory.grow and export that, you could then call that from your host function. That said, I think we'll likely be able to add this, just need a second brain on if out-of-function scope will be a problem or not.

**Comment by mathetake** [comment]
no, this isn't about how we implement, but growing memory must only be done by Wasm's memory.grow instruction. For example, otherwise language runtime won't be able to track the current number of pages in memory.

For example, in tinygo https://github.com/tinygo-org/tinygo/blob/3883550c446fc8b14115366284316290f3d3c4b1/src/runtime/arch_tinygowasm.go#L55 runtime's `growMemory()` is the only callsite of memory.grow instruction and the runtime tracks the current pages size there. If the pages size was changed by host, TinyGo's runtime can't know the current pages and won't be able to do allocation correctly. 


That said, growing memory in host API should't be allowed IMO.

**Comment by codefromthecrypt** [comment]
@mathetake interesting points. So, I guess one issue is if you don't have a runtime, then there isn't a problem per-se (%.wat), it is mainly that if there is an allocation library (rust or tinygo), you should defer to that for memory.grow. In other words export an allocation function and use that instead of manually growing pages? Do I get it right?

**Comment by mathetake** [comment]
yep, but even if there's no runtime issue, I can't find any rationale for host function being allowed to grow memory in the specification. looks like growing memory is only described with `memory.grow`.

**Comment by mathetake** [comment]
anyway I would like to know the use case beforehand even if we decide here to expose the API as this comes with a bit of tweak in JIT as well.

**Comment by codefromthecrypt** [comment]
ps I added this issue to tinygo as I think while it is nice for us to be a center of knowledge in tinygo it would be even better if TinyGo's docs could give more direction on things like this https://github.com/tinygo-org/tinygo/issues/2787

**Comment by danielpacak** [comment]
Thank you for the feedback @codefromthecrypt and @mathetake .

My primary use case is based on WASM engine implemented by Open Policy Agent that relies on wasmtime-go in https://github.com/open-policy-agent/opa/blob/v0.39.0/internal/wasm/sdk/internal/wasm/vm.go#L179.

What I'm trying to do is evaluate Rego policy compiled to WASM using wazero instead of wasmtime-go. This is where I bumped into the `Grow` method https://github.com/danielpacak/webassembly-cookery-book/blob/fdd24eb911a55ba0be65547cb2c46710a6456809/anti-debugging-sig-wazero/vm.go#L195

In other words, the WASM module compiled by OPA requires a shared memory buffer named `env.memory` that may grow based on user input. However, when I look back at OPA code, host instantiates memory with max size of 65536 bytes so I'm wondering if growing it beyond max makes any sense.

```go
env, err := runtime.NewModuleBuilder("env").
	ExportFunction("opa_abort", func(uint32) {}).
	ExportFunction("opa_builtin0", func(uint32, uint32) uint32 { return 0 }).
	ExportFunction("opa_builtin1", func(uint32, uint32, uint32) uint32 { return 0 }).
	ExportFunction("opa_builtin2", func(uint32, uint32, uint32, uint32) uint32 { return 0 }).
	ExportFunction("opa_builtin3", func(uint32, uint32, uint32, uint32, uint32) uint32 { return 0 }).
	ExportFunction("opa_builtin4", func(uint32, uint32, uint32, uint32, uint32, uint32) uint32 { return 0 }).
	ExportMemoryWithMax("memory", 16, 65536).
	Instantiate(ctx)
if err != nil {
	return nil, err
}
defer env.Close()
```

**Comment by codefromthecrypt** [comment]
ps that max is in pages, so you need to multiply by 64K!

**Comment by codefromthecrypt** [comment]
oh nevermind you said host side.. yeah that's odd. it would be a noop indeed.

**Comment by codefromthecrypt** [comment]
@danielpacak I'll try to make you a workaround for this. Especially as it is unlikely to be called a workaround might be ok until we figure out the impact on JIT.

**Comment by codefromthecrypt** [comment]
hopefully this workaround will help. Note the main change here is just ensuring it works in our built-in text compiler, which is more convenient than using wat2wasm offline. You should be already able to do this the other way. https://github.com/tetratelabs/wazero/pull/489

**Comment by codefromthecrypt** [comment]
ps looking at your code it is possible you'll need to replace imports to get memory and functions defined where they need to be, yet have exports appear as "env" to the opa code. wazero has functionality to remap things like this.

See https://github.com/tetratelabs/wazero/blob/main/examples/replace-import/replace-import.go
See https://github.com/summerwind/the-art-of-webassembly-go/blob/ff172474c06330df04a0950c3a5092ee28274011/chapter3/table/table.go

NEXT STEP:
See what's possible wrt to adding Grow to the api.Memory API, ex if where that's safe and any dependencies needed to make it work safely.

**Comment by danielpacak** [comment]
Thank you @codefromthecrypt for memory examples. I'll try them out.

BTW, I've seen that WebAssembly.Memory object defines the [grow()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/Memory/grow) method as well.

**Comment by codefromthecrypt** [comment]
@danielpacak we'll defer this until done bulk-memory unless you scream that the workaround isn't enough. Appreciate your trying things out!

**Comment by codefromthecrypt** [comment]
ps one reason why it is simple in other impls is that none of them are thread/goroutine safe, at least not that I've found, yet.

After thinking a while, once #502 is in place I'm confident we can expose Memory.Grow, but the existing views of memory won't be updated as that requires some scary mutability.

Ex.
```go
if updated, ok := mem.Grow(x); ok {
  mem = updated
} else {
   // unsupported, disallowed or otherwise didn't change
}
```

So, on success, updated and any subsequent function calls will be able to see the update. No promises one way or another on existing objects created from `Module.Memory()`

**Comment by codefromthecrypt** [comment]
done. enjoy!
