### ISSUE TITLE
Add option to change Memory capacity

### ISSUE THREAD

**Issue by inkeliz** [tetratelabs/wazero#500]
That is similar to https://github.com/tetratelabs/wazero/issues/483, but it's capacity, not length.

It's possible to define a maximum memory, https://github.com/tetratelabs/wazero/pull/419, however, each `grow` function can potentially cause reallocs on the host-side/wazero. It puts more pressure on GC and makes things slower, since allocs are expensive.

-----------

I'm using the following code:

```
	rConfig := wazero.NewRuntimeConfigJIT()
	rConfig.WithMemoryMaxPages(10_485_760 / 65_536)
```

The memory limit is ~10MB. So, I would also like to set:

```
	rConfig.WithMemoryCapacity(10_485_760)  // Bad naming
```

Internally, Wazero should do: `make([]byte, MemorySector.Mininum, 10_485_760)`. In that case, the wasm program can call `grow` without creating new allocs, since all the space available is already allocated and reserved.

**Comment by codefromthecrypt** [comment]
Thanks for the idea! This is a lot simpler to do than #483 as it is constant. I suspect it would need to be in pages for parity with both the max and also https://www.w3.org/TR/2019/REC-wasm-core-1-20191205/#grow-mem

one thing I'm curious about is about why not set min to this amount? is it because you can't modify the wasm? If you could externally, would you prefer doing that? A little explanation on this could help share your experience.

**Comment by inkeliz** [comment]
> one thing I'm curious about is about why not set min to this amount?

I just want to mitigate allocs on the host, but doesn't change anything on wasm. In the end, that is a very small optimization, to make `grow` a little bit faster. 

I would like to know the size, so changing it may cause it to be "misleading".  If we change the minimum memory (not just capacity), then the `Memory.Size()` will return "10MB", which "is not true". While all programs have 10MB allocated, not every wasm is using it. 

I'm looking to have something reporting the memory like: "Memory: 2MB/10MB". So, if you are the developer of such wasm, you know how much memory your wasm is consuming, and you can fix or improve it. But, if I change the size to 10MB, then it will be always 10MB.

Maybe both methods can exists: change capacity and change minimum memory.

**Comment by codefromthecrypt** [comment]
cool one last question, just for kicks.. how are you planning to track this m/M memory usage? I guess the host has a metrics integration where it looks at Memory.Size on occasion? or is it something else?

**Comment by inkeliz** [comment]
I'm calling one exported function, such as `Update` when there's something to do, so that is where most of work should be done. My idea is to "track the memory usage" after each `Update`.

Something like:

```
fn := m.ExportedFunction("Update")

for evt := <- event {
fn.Call(context.Background())
memorySize = m.Memory().Size()
}
```

As I said, that is usefull just to "profiling", also to verify if 10MB is enough or not, of instance. If many modules is taking ~8MB, even without crash, we know that 10MB is too small. 

----------

Also, I'm using Wazero for testings. Like `main_wasi_test.go`. The test compiles the program using TinyGo and then uses the Golang's Testing system. That is great, because it's a single Test, pure Go. The memory consumption is also important to prevent leaking or detect allocs. 

I have some code like:

```
func BenchmarkDecodeSumVec3(b *testing.B) {
        // ...
        m := initWasm(b, "BenchmarkDecodeSumVec3")
        	
        b.ResetTimer()
	b.ReportAllocs()
	initMemory := m.m.Memory().Size()
	for i := 0; i < b.N; i++ {
		if !m.Write(encoded) {
			b.Fatal("invalid memory ptr")
		}
		sum, err := m.Run()
		if err != nil {
			b.Error(err)
		}
		if sum[0] != expectResult {
			b.Error("wrong result")
		}
		if initMemory != m.m.Memory().Size() {
			b.Error("allocation detected")
		}
	}
}
```

Of course, in that case change the `capacity` is not so useful, but the `Memory().Size()` is useful. ;)

**Comment by codefromthecrypt** [comment]
@inkeliz perfect context. I'm pretty sure we can do this and not yank it from you later. One last check and I'll raise the PR.

@mathetake I think we're done the "actual bulk memory" part of the bulk memory spec now, right? (the spec was merged co-dependent on some parts of reference types and bulk table ops). IIRC from looking at the code, there's nothing that impacts us in terms of how we manage size vs capacity right?

**Comment by mathetake** [comment]
yep I don't see any problem for passing capacity here https://github.com/tetratelabs/wazero/blob/main/internal/wasm/module.go#L530

**Comment by codefromthecrypt** [comment]
I will land this tomorrow morning (asia time)

**Comment by codefromthecrypt** [comment]
https://github.com/tetratelabs/wazero/pull/514 should do it

**Comment by codefromthecrypt** [comment]
fyi this was revisited with the new CompileConfig (which also allows overriding the max memory)

```go
limitPages := 4
compileConfig := wazero.NewCompileConfig().
	WithMemorySizer(func(minPages uint32, maxPages *uint32) (min, capacity, max uint32) {
		if maxPages != nil {
			limit := uint32(math.Max(limitPages, float64(*maxPages)))
			return minPages, limit, limit
		}
		return minPages, limitPages, limitPages
	})
```
