### ISSUE TITLE
Consider not returning api.Module when instantiating wasi

### ISSUE THREAD

**Issue by anuraaga** [tetratelabs/wazero#551]
I noticed that the module returned from wasi instantiation isn't usable as a normal module - notably it doesn't have `Memory` or `Sys`, so trying to call exported functions doesn't work. wasi module is meant to be a supporting module imported by another wasm module. `Module` is likely returned to allow `Close` - now that we have `Runtime.Close` we could consider not returning a module when initializing wasi to prevent users (like me :-) ) from trying to use it as a normal module. It does mean that `Runtime.Close` stops being an alternative to closing modules but is required when using wasi - this may be natural because people often call `Close` anytime there is a `Close` method I guess.

It could also be ok to leave behavior as is if there is a reasonable runtime message. Unfortunately, wasi functions often requiring the host to write into `Memory` before calling. This means that the error can easily be a nil reference exception in the user code when trying to use `Memory`, without a good error message.

**Comment by codefromthecrypt** [comment]
I understand what you are saying, but calling Runtime.Close() is optional. We could instead return a Close function that matches the signature (if preventing API misuse is the key thing). would that work?

**Comment by anuraaga** [comment]
Yeah returning something that only has a Close would work well too

**Comment by codefromthecrypt** [comment]
one thing to remember is that while our examples always use WASI in the same main runner. It is entirely possible and likely when WASI 2 comes out that this will end up scoped with the module that uses it vs the runtime. This would result in closing WASI alongside the module, while keeping the runtime open.
