### ISSUE TITLE
People want to see performance results. How should we present them?

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#576]
**Is your feature request related to a problem? Please describe.**

For a while, we've had people either make calls based on us not publishing numbers or asking us to publish numbers. We hadn't because it is thrashy on README, but maybe there's a better way.

**Describe the solution you'd like**
Maybe a GH Action can publish formatted results on cron, to somewhere netlify can serve them on wazero.io

**Describe alternatives you've considered**
We usually point people to our benchmarks in the test action, but as it is embedded in the test action, it is hard to see. We could extract the benchmark into its own action, but then still it won't be obvious until someone clicks into it.

**Additional context**

Motivational issues

https://github.com/mosn/proxy-wasm-go-host/issues/15#issuecomment-1091144508
https://news.ycombinator.com/item?id=31415317
https://news.ycombinator.com/item?id=31411470

**Comment by evacchi** [comment]
as a source of inspiration, I just love how the Flix language has a *dashboard* where they track perf regressions in their compiler https://flix.dev/documentation/
