### ISSUE TITLE
Calling a function without access to malloc

### ISSUE THREAD

**Issue by F21** [tetratelabs/wazero#591]
I am using [Shopify/javy](https://github.com/Shopify/javy) to compile javascript functions to wasm,

This is the function that I am using:
```js
function foo(input) {
    return { foo: input.n + 1, newBar: input.bar + "!" };
}

Shopify = {
    main: foo,
};
```
This is then compiled to wasm using `./javy shopify.js -o shopify.wasm`.

I can then call `main` using wasmser in my cli: `echo '{ "n": 2, "bar": "baz" }' | wasmer shopify.wasm`

I now want to do the same using wazero, however, looking at the examples, it seems that I need access to malloc: https://github.com/tetratelabs/wazero/blob/main/examples/allocation/tinygo/greet.go#L57

If I inspect `shopify.wasm` using wasmer, it doesn't have `malloc` or `free` as exported functions:
```
Type: wasm
Size: 999.3 KB
Imports:
  Functions:
    "wasi_snapshot_preview1"."fd_write": [I32, I32, I32, I32] -> [I32]
    "wasi_snapshot_preview1"."fd_read": [I32, I32, I32, I32] -> [I32]
    "wasi_snapshot_preview1"."clock_time_get": [I32, I64, I32] -> [I32]
    "wasi_snapshot_preview1"."proc_exit": [I32] -> []
    "wasi_snapshot_preview1"."environ_sizes_get": [I32, I32] -> [I32]
    "wasi_snapshot_preview1"."environ_get": [I32, I32] -> [I32]
    "wasi_snapshot_preview1"."fd_seek": [I32, I64, I32, I32] -> [I32]
    "wasi_snapshot_preview1"."fd_close": [I32] -> [I32]
    "wasi_snapshot_preview1"."fd_fdstat_get": [I32, I32] -> [I32]
  Memories:
  Tables:
  Globals:
Exports:
  Functions:
    "_start": [] -> []
    "main": [I32, I32] -> [I32]
  Memories:
    "memory": not shared (22 pages..)
  Tables:
  Globals:
    "__heap_base": I32 (constant)
    "__data_end": I32 (constant)
```
How do I write to memory in this situation? How is wasmer able to write to memory to pass the string in when the compiled wasm does not have malloc or free?

Edit: This should not be tagged with the bug label.

**Comment by mathetake** [comment]
why do you need to access malloc and frees as I see your code doesn't use the heap at all. 
As you can see these examples are designed for the usage where Wasm modules need to allocate complex data structure in and out between Wasm VM and host and that's why these examples are using language specific malloc and free functions for rust and tinygo (since allocation semantics are different on each language runtimes).

The example you want to look at is https://github.com/tetratelabs/wazero/blob/main/examples/basic/add.go where you just call `main` instead of `add` int the code. Thanks!

**Comment by F21** [comment]
@mathetake Thanks for your help. I did look at that example but it seems to be calling the function with 2 integers. How do I call a function with a string (in my case some json)?

**Comment by mathetake** [comment]
then we need to do the similar things as we did Rust and TinyGo in the examples. But I'm not sure about the runtime semantics of Javy at all, so I think we need to have time to investigate it.

**Comment by F21** [comment]
Right, so that means the javy compiler should also export equivalent `malloc` and `free` functions?

Given that the wasm file did not have any `malloc` or `free` functions, I am not sure how wamser is able to execute the function with a string: `echo '{ "n": 2, "bar": "baz" }' | wasmer shopify.wasm`

**Comment by mathetake** [comment]
Oh I see the signature of `main` becomes `"main": [I32, I32] -> [I32]` ... maybe this means that we can pass string as `main(pointer, len)` where pointer is the memory location while len is the length of string

This makes me feel like weird as this way Javy's GC seems not able to track the memory allocation at all. But anyway this seems how it works

**Comment by mathetake** [comment]
Anyway opened an issue for example addition with javy, though not sure if we could prioritize it. Thank you for playing with wazero anyway!
