### ISSUE TITLE
Add a Javy example

### ISSUE THREAD

**Issue by mathetake** [tetratelabs/wazero#592]
As requested by https://github.com/tetratelabs/wazero/issues/591#issuecomment-1136536077

**Comment by codefromthecrypt** [comment]
I switched the title as this isn't about allocation the same way as others are thinking. If there is demand, we could add a Javy example anyway, for example, showing how to communicate with stdin/stdout as opposed to via memory regions. cc @saulecabrera @F21

https://github.com/Shopify/javy/issues/111

**Comment by codefromthecrypt** [comment]
note: WASI also allows one-way input via args (or env), which some of our examples already do. stdin/stdout would be another way (conversation)

**Comment by F21** [comment]
I've been testing sending input to the javy-compiled wasm via stdin and receiving output on stdout.

Currently I am doing something like this (abridged):
```go
config := wazero.NewModuleConfig().WithStdout(os.Stdout)
data := bytes.NewBufferString(`.......some data`)

_, err = r.InstantiateModule(ctx, code, config.WithName("main").WithStdin(data))
```

Is `InstantiateModule` the only way to pass input to the module using stdin? Does it have any performance disadvantages compared to using `myFunction.Call()`?

I am more than happy to contribute an example for this, but would like to know if this is the best way.

**Comment by codefromthecrypt** [comment]
The main question I have is if making repeated function calls in Javy is even supported (per the other thread). If not, and the only way is using WASI (`_start` function automatically called on `InstantiateModule`), then it is likely a moot point, isn't it?

Maybe you can share a sample project that is calling a function multiple times in the same memory space?

**Comment by F21** [comment]
Here's a quick example I created: https://github.com/F21/javy-wazero

Calling `InstantiateModule` multiple times panics as expected. Not sure how we can call the module multiple times without recompiling at the moment.

**Comment by codefromthecrypt** [comment]
thanks. I'll follow up on that repo and keep this issue open meanwhile.

**Comment by F21** [comment]
Quick update: I was able to remove the need for an entirely new runtime on each instantiation by instantiating each module with a  unique name and closing the module after it's been called.

**Comment by codefromthecrypt** [comment]
for now I will help/watch https://github.com/F21/javy-wazero similar to how I do with https://github.com/birros/wazero-demo  I kindof prefer when community members take stake with others learning things.

we can re-open this issue if something changes.

**Comment by F21** [comment]
For those interested in using Wazero with Javy, I've published an example implemented using Shopify's Javy and Suborbital's Javy fork here: https://github.com/F21/javy-wazero
