### ISSUE TITLE
Rust/WASI example

### ISSUE THREAD

**Issue by clarkmcc** [tetratelabs/wazero#619]
**Is your feature request related to a problem? Please describe.**
I've copied the WASI example nearly exactly but I can't seem to get it to work with a Rust guest, for example, my scripts panic when I try to use `time::Instant`, and the `.WithArgs` aren't available when calling `std::env::args()`. Is there an example or anything special I need to do to get it working? If I were just shooting in the dark, I'd say that Rust just isn't expecting those host functions to go into the `wasi_snapshot_preview1` module name, but again, I'm just spitballing.

**Describe the solution you'd like**
An example of using Rust and WASI.

**Comment by codefromthecrypt** [comment]
I shot around in the dark too. The main thing is TinyGo builds in support for WASI and rust doesn't. That said, I agree this is time well spent to add something however it can be achieved.

**Comment by clarkmcc** [comment]
I'm wondering if we could piggy back off of this. https://github.com/bytecodealliance/wasi/blob/main/src/lib_generated.rs

**Comment by codefromthecrypt** [comment]
looks fine.. seems to have no dependency on wasmtime at the moment https://crates.io/crates/wasi/0.11.0+wasi-snapshot-preview1/dependencies

If you'd like to give this a go, mainly just follow the structure of the allocation example and make a new directory with the same ("ish") code for rust that's done in tinygo?

**Comment by clarkmcc** [comment]
Ah, silly me. Rust already has a WASI implementation and toolchain. I can still work on getting a complete example created if that would be helpful.
     
    cargo build --target wasm32-wasi

More details are available [here](https://github.com/bytecodealliance/wasmtime/blob/main/docs/WASI-tutorial.md#from-rust) and 

https://github.com/bytecodealliance/wasi/blob/9ec04a7d8ebb1bbb9e3291503425cee1ec38a560/README.md?plain=1#L19-L21

**Comment by codefromthecrypt** [comment]
silly me, too, then :)

I think it would be worth doing one if you have time. try to lift the same templating from the allocation example, though I think you won't actually need the allocator in order to do the cat example.

If you run out of time, you can still push an incomplete PR up and it would help vs starting from scratch!

**Comment by codefromthecrypt** [comment]
I'll add it to the README. good idea

**Comment by codefromthecrypt** [comment]
sorry I meant to say I'll add a how to into the README as I think primarily pointers were missing in how to find rust stuff. Rust is the most over served language in WebAssembly, most maintained, most docs, most control, most people working on it.

Basically, I think with pointers to rust projects and also to our other rust example, should be good enough, especially with WASI as it *should* act the same regardless of toolchain. I don't really want to special-case a generation step over this, but that doesn't mean eliminate pointers to where to go in other words.

**Comment by codefromthecrypt** [comment]
Actually the release build using `cargo wasi build --release` isn't looking so bad. If this ends up <100k and still works, I'll add it in and say that this is an optimized version of `cargo build --release --target wasm32-wasi`

**Comment by codefromthecrypt** [comment]
okie dokie.. better late than never @clarkmcc! https://github.com/tetratelabs/wazero/pull/676

**Comment by clarkmcc** [comment]
@codefromthecrypt thanks! Sorry for not getting around to rolling an example. Things got chaotic on my side, as always 🙄.
