### ISSUE TITLE
interpreter: bug with CallIndirect when using FunctionListener

### ISSUE THREAD

**Issue by ajwerner** [tetratelabs/wazero#633]
**Describe the bug**
I've got a wasm program which runs great with the interpreter and the compiler, but if I inject a no-op FunctionListener, it infinite loops. It seems that the wrong function is being called.

I'm pretty sure the problem is here, where I think the argument should be `tf` instead of `f`.  
https://github.com/tetratelabs/wazero/blob/30be6a8e2a4927a629ce7f568af398aa1c41e78e/internal/engine/interpreter/interpreter.go#L906

However, it's not that simple because `peekValue` panics pulling the params.

**To Reproduce**

I have a repro I can post if it's useful, but I think it should be easy enough to add a test with an indirect call. 

**Expected behavior**
The `FunctionListener` wouldn't lead to an incorrect execution of the program.

**Comment by codefromthecrypt** [comment]
I think there's something wrong here also, I thought it might be call_indirect related, but not sure yet. Thanks for raising.

**Comment by codefromthecrypt** [comment]
sorry it took me so long, call-indirect was a red-herring, the bug was about the initial function signature.  #640
