### ISSUE TITLE
Expose more information from CompiledModule

### ISSUE THREAD

**Issue by prep** [tetratelabs/wazero#637]
**Is your feature request related to a problem? Please describe.**
After having created a `CompiledModule`, I'd like to infer some information from it. For example, I'd like to know what type of functions it wants imported and what kind of functions it is exporting, amongst other things.

**Describe the solution you'd like**
`CompiledModule` (or actually, it's underlaying struct `compiledModule{}`) seems to embed `internal/wasm.Module{}` which appears to hold that information. Perhaps we could bubble up that information to the public API?

**Describe alternatives you've considered**
What I can do right now is create an instance from the `CompiledModule` and offer it all the imports available to me in the hope that it satisfies what the module needs. Then I can poke around with functions like `ExportedFunction()` and poll for information.

Obviously, this is not a great solution and this solution doesn't help me figure out what imports a module needs.

**Comment by codefromthecrypt** [comment]
Thanks for asking. I think exposing the externtypes in an immutable way would make sense and not add too much surface area. Would that work? (ex import/export).

I had also planned to add name section data at some point, but type info would be a simpler start.

**Comment by codefromthecrypt** [comment]
@prep also if you can mention the specific use cases you are trying to solve? if this is about wasmexec, you can discuss the design there first with me if you want, as there are a number of things go specific needed (ex custom section) hence adding things internal here vs exposing everything.

**Comment by prep** [comment]
What you suggested would work for me indeed 👍 This is not directly related to wasmexec, though, but it could serve as an example.

A TinyGo wasm module as a `_start` function and a Go wasm module has a `run` function to start the program off. A TinyGo wasm module (targeted for WASI) wants WASI imports and a Go wasm module wants the wasmexec imports.

Right now, I cannot know this beforehand when I get handed a wasm module so I have to offer all the imports and after instantiation have to check for the availability of a `_start` and `run` function to call. Getting this information beforehand via `CompiledModule` allows me to split this functionality off in their own struct definitions.

Separate structs for handling a TinyGo module vs a Go module allows for a nice separation of logic. Does this make sense or is the use case too vague?

**Comment by codefromthecrypt** [comment]
Thanks, I think this summarizes as heuristic identification of the compiler. Ex wapc-go lacking this imports both assemblyscript and wasi imports just in case they are needed. It could be tightened up similarly. Did I get it right? cc @pkedy

**Comment by prep** [comment]
Yes, sounds about right. I also seem to remember your doc about integrating a wasmexec-like functionality in wazero that depends on checking if the binary has markers that are unique to a Go wasm module. Unless you were going to use the internal API to do that, I'd imagine exposing information about the module helps with that.

**Comment by codefromthecrypt** [comment]
yeah actually I think we can add some utilities for built-in host modules, to detect signature for assemblyscript, wasi (snapshot-01) and go. The latter is more interesting as we can vary even on version ;)

**Comment by codefromthecrypt** [comment]
This can also help in error checking. Ex if CompiledModule exposes which functions it exports, you aren't going to get nil for that post-instantiation.

**Comment by codefromthecrypt** [comment]
This will add even more data, particularly import info, which is available both before and after instantiation https://github.com/tetratelabs/wazero/pull/686

**Comment by codefromthecrypt** [comment]
FYI here's an example of checking things before you instantiate cc @prep

```go
	exportedFunctions := compiled.ExportedFunctions()

	for _, fn := range []string{wasmFuncMalloc, wasmFuncFree, wasmFuncRewrite} {
		if _, ok := exportedFunctions[fn]; !ok {
			return fmt.Errorf("module[%s] didn't export function[%s]", compiled.Name(), fn)
		}
	}

	return nil

```

**Comment by prep** [comment]
Awesome! Thanks for this @codefromthecrypt ❤️ I'll have a look at this in the upcoming week.
