### ISSUE TITLE
Add support for sign-extension instructions (post MVP feature)

### ISSUE THREAD

**Issue by achille-roussel** [tetratelabs/wazero#66]
Hello,

I'm opening this issue to report an error I ran into where it appeared wazero was unable to instantiate an AssemblyScript program compiled with asc.

Here is the error I got:
```
functions: invalid function at index 106/280: invalid instruction
```

Tools like `wasm2wat` are able to read through the file without issues, so it appears correct tho I do not know whether they perform checks similar to those in wazero.

I'm attaching the program that triggered the error:
[test.wasm.gz](https://github.com/tetratelabs/wazero/files/7674600/test.wasm.gz)

Let me know if you need any other information.

**Comment by mathetake** [comment]
Hi, thank you for reporting. This looks like the binary contains the new Wasm instructions beyond w3c 1.0 WebAsssembly Specification. Notably I can see the binary uses, for example, `i64.extend_i32_u` which is newly introduced in 1.1 specification, but the versions is not formally released under w3c.

We definitely would like to support the wider instructions vs we want to wait for this library AND WebAssembly spec to reach some maturity before we move onto these new features.

In the meantime, I guess asc should be able to limit these new features and produce Wasm 1.0 spec comatible binary.  Could you try that mode?

Thank you!

**Comment by mathetake** [comment]
What confuses me though is that the binary header says it is 1.0 version binary. 

In any case, `*.extend_*` instructions are pretty simple to support in wazero, so maybe we could have support for them, but I would like to carefully choose what to support and what not to among these new features as this project is in its early stage. @codefromthecrypt thoughts?

**Comment by achille-roussel** [comment]
Thanks for the quick and useful reply!

Adding `--disable sign-extension` to the `asc` command invocation produced a wasm program that wazero has no trouble reading 👍

**Comment by MaxGraey** [comment]
> What confuses me though is that the binary header says it is 1.0 version binary.

1.1 is spec version only. Binary header even with recently standardized post-MVP features like sign-extension, multi-values and etc should still use version with number `1` (not `1.1`). See reference encoder / decoder for example:
https://github.com/WebAssembly/spec/blob/main/interpreter/binary/encode.ml#L3

**Comment by mathetake** [comment]
> > What confuses me though is that the binary header says it is 1.0 version binary.
> 
> 1.1 is a spec edition. Binary header even with recently standardized post-MVP features like sign-extension, multi-values and etc should use version with number `1` (not `1.1` or something else). See reference encoder / decoder for example: https://github.com/WebAssembly/spec/blob/main/interpreter/binary/encode.ml#L3
> 
> Instead WebAssembly use special optional feature section for detect post-MVP features

Thanks @MaxGraey, your comment really is helpful to us. Could you give me any pointer to `Instead WebAssembly use special optional feature section for detect post-MVP features`? Doc or something?

**Comment by codefromthecrypt** [comment]
We are pending work to clarify the API interfaces of the project, as well harden things around spec versions.

While it is common for some projects to mix and match specs with draft features, our first goal is to implement the actual specification (w3c https://www.w3.org/TR/wasm-core-1/), not a draft or something on github.

Layering on complexity of proposed features or tracking 1.1 drift prior to a solid 1.0 is a non-goal. We should report things that feel like bugs, such as using the same version encoding for 1.0 and 1.1 features when incompatible. Since there is a version encoding, it seems odd to conflate like that. Maybe no-one raised an issue, yet. 

Anyway, the main point is that we should get 1.0 fully working and in good shape, watch out for anything we can with regards to future versions, including good error reporting and also raising bugs on https://github.com/WebAssembly/spec/ when we notice compatibility problems (such as version conflation in encoding)

**Comment by codefromthecrypt** [comment]
concretely, I think we'll do a lot better with error reporting and this is a good example of it. Knowing people are mixing and matching spec with pre-spec features, we can add some nice error handling to tell people what's going on (ex this is not yet supported) vs a cryptic error.

Once we get 1.0 working and enough hands to do the vastly larger feature set of 1.1, we can start implementing those things.

**Comment by MaxGraey** [comment]
@mathetake It's not yet standardized but LLVM for example may emit it:
https://github.com/LEA0317/llvm9-half/blob/626b2ae86adca116d2e49871e8a3cb9b106fd5db/llvm9.0.1/llvm/lib/Object/WasmObjectFile.cpp#L720

Which I guess usually locate in custom section and may be stripped. So it is best and most reliable to simply detect features during decoding encountering one or the other operation related to according feature.

**Comment by nullpo-head** [comment]
Apps written in Grain language also requires this sign-extension feature.  JFYI cc @pims

**Comment by codefromthecrypt** [comment]
so if I understand correctly, this feature doesn't introduce new datatypes. This would require a new feature flag for `sign-extension-ops` which guards parsing the 5 new opcodes. Of course, they would need to be implemented in JIT and the interpreter.

https://github.com/WebAssembly/spec/commit/e308ca2ae04d5083414782e842a81f931138cf2e
https://github.com/WebAssembly/spec/blob/main/proposals/sign-extension-ops/Overview.md

**Comment by codefromthecrypt** [comment]
@pims do you mind testing latest commit with GrainLang? You'll have to disable bulk memory with `--no-bulk-memory` until #321 and use this to initialize wazero:

```
r := wazero.NewRuntimeWithConfig(wazero.NewRuntimeConfig().WithFeatureSignExtensionOps(true))
```

**Comment by pims** [comment]
Will do.

**Comment by codefromthecrypt** [comment]
ps haven't forgotten about this, just swamped with other things. I'll update by Weds or nag me!
