### ISSUE TITLE
Add Zig example

### ISSUE THREAD

**Issue by knqyf263** [tetratelabs/wazero#738]
Do you think it would be worthwhile to maintain an example of Zig in the wazero repository? I extended the allocation example for Zig. I can open a PR if you have an interest. Please feel free to close the issue if it is not the case.
https://github.com/knqyf263/zig-wasm-example

**Comment by codefromthecrypt** [comment]
I think so. I've also at times ad-hoc defined a zig project.

Please raise a PR and also don't forget to update the GitHub examples workflow and the Makefile accordingly!

**Comment by knqyf263** [comment]
Thanks for confirming. I opened #741.
