### ISSUE TITLE
some example show calling wasm written with go office

### ISSUE THREAD

**Issue by wuhuizuo** [tetratelabs/wazero#74]
1. wasm source example with go office.
2. tests call go office wasm binnay with wazero.

**Comment by codefromthecrypt** [comment]
Hi, and sorry we missed this. Is this the example you are interested in? https://github.com/wuhuizuo/go-wasm-go

It seems you want to have an example where wazero loads a wasm binary that calls a go function. Correct? 

This example calls a host function: https://github.com/tetratelabs/wazero/blob/main/examples/host_func_test.go#L27

Another more simpler is this, but note the text format is incomplete, so changing the source will not likely work, yet. See #59 for progress: https://github.com/tetratelabs/wazero/blob/main/examples/simple_test.go

**Comment by wuhuizuo** [comment]
> 嗨，很抱歉我们错过了这个。这是您感兴趣的示例吗？https://github.com/wuhuizuo/go-wasm-go
> 
> 似乎您想要一个示例，其中 wazero 加载调用 go 函数的 wasm 二进制文件。正确的？
> 
> 这个例子调用了一个主机函数：[https ://github.com/tetratelabs/wazero/blob/main/examples/host_func_test.go#L27](https://github.com/tetratelabs/wazero/blob/main/examples/host_func_test.go#L27)
> 
> 另一个更简单的方法是，但请注意文本格式不完整，因此更改源不太可能起作用。进度见[#59 ： ](https://github.com/tetratelabs/wazero/issues/59)[https ://github.com/tetratelabs/wazero/blob/main/examples/simple_test.go](https://github.com/tetratelabs/wazero/blob/main/examples/simple_test.go)

I mean wazero load WASM file which was compiled with office golang compile, and call the functions.

**Comment by wuhuizuo** [comment]
> Hi, and sorry we missed this. Is this the example you are interested in? https://github.com/wuhuizuo/go-wasm-go
> 
> It seems you want to have an example where wazero loads a wasm binary that calls a go function. Correct?
> 
> This example calls a host function: https://github.com/tetratelabs/wazero/blob/main/examples/host_func_test.go#L27
> 
> Another more simpler is this, but note the text format is incomplete, so changing the source will not likely work, yet. See #59 for progress: https://github.com/tetratelabs/wazero/blob/main/examples/simple_test.go

I mean wazero load WASM file which was compiled with office golang compile, and call the functions.

**Comment by codefromthecrypt** [comment]
maybe you can look at this which builds on @pkedy's work to use wazero in wapc-go. It is a fairly complete usage pattern including memory https://github.com/wapc/wapc-go/pull/15

I'm closing the issue because I hope this answered the question!
