### ISSUE TITLE
Published version v1.0.0-beta1 takes precedence over v1.0.0-beta.2

### ISSUE THREAD

**Issue by ncruces** [tetratelabs/wazero#789]
I don't know what caused this, since I see no tag `v1.0.0-beta1`, but according to semver `v1.0.0-beta1` (notice the missing dot) will always take precedence over anything after a dot (like `v1.0.0-beta.2`).

https://pkg.go.dev/github.com/tetratelabs/wazero?tab=versions

**Comment by ncruces** [comment]
The solution is to withdraw `v1.0.0-beta1` (which I don't know how to do) or to not use the dot going forward.

**Comment by codefromthecrypt** [comment]
yeah that tag was an accident and go.mod didn't like it.. I'll look into seeing if there's a way to sort that out

**Comment by codefromthecrypt** [comment]
https://go.dev/ref/mod#go-mod-file-retract will try this

**Comment by codefromthecrypt** [comment]
later fixed up to 

```
// Wrong naming convention
retract v1.0.0-beta1

// Has memory bug and quickly fixed in v1.0.0-beta.2.
retract v1.0.0-beta.1
```

**Comment by ncruces** [comment]
Note that #790 is not sufficient.

You now need to tag this retraction as `v1.0.0-beta.3` (and get it into the module cache), or it never gets "published", and we never get to see the retraction.

Hence the section in https://go.dev/ref/mod#go-mod-file-retract about a retraction retracting itself.
This… is complicated.

**Comment by codefromthecrypt** [comment]
or maybe I won't need to say the exact beta after that.. let's try first

**Comment by codefromthecrypt** [comment]
I guess in any case we have to wait for propagation to take place. Meanwhile, I'll keep #792 to ensure folks don't paste a command to get the broken tag.

**Comment by codefromthecrypt** [comment]
beta 3 shows up but the other tag still does too :) https://pkg.go.dev/github.com/tetratelabs/wazero?tab=versions

**Comment by codefromthecrypt** [comment]
oh... I hope it isn't what I think it is, which is that the redacted version will stay until a release has a semver higher than it..

**Comment by codefromthecrypt** [comment]
ok so problem is `beta` is dead. we can't really use the broken version pattern because if we do, it is invalid from go's mod version syntax.

We need to switch to a word lexicographically later than `beta`

**Comment by codefromthecrypt** [comment]
suggesting on [gophers slack](https://gophers.slack.com/) `#wazero` channel to use "pre" as that allows us to use "rc" later, and also gets us into a position where people won't accidentally upgrade into a broken version

**Comment by codefromthecrypt** [comment]
going with "pre" as it is literally the example given for a pre-release and also comes before rc which we'll almost surely want prior to real 1.0 https://go.dev/ref/mod#glos-pre-release-version

**Comment by codefromthecrypt** [comment]
https://github.com/tetratelabs/wazero/pull/792

**Comment by codefromthecrypt** [comment]
ok it isn't in the public versions cache, yet, but at least considered an upgrade :)

```bash
$ go get -u  github.com/tetratelabs/wazero@v1.0.0-pre.1
go: downloading github.com/tetratelabs/wazero v1.0.0-pre.1
go: upgraded github.com/tetratelabs/wazero v1.0.0-beta1 => v1.0.0-pre.1
```

Thanks tons @ncruces!
