### ISSUE TITLE
Remove wasm.CallGoFunc use reflect.Value

### ISSUE THREAD

**Issue by hafeidejiangyou** [tetratelabs/wazero#823]
**Is your feature request related to a problem? Please describe.**
When I try wazero, I found wasm.CallGoFunc takes a lot of CPU in my case with BenchMarks,  It is show a lot of time is spent on reflections, so I want to remove the reflective call of the host function.

**Describe the solution you'd like**
To remove reflections, the host function signature must be same. And we can use uint64 slice or interface{} slice as the param type, so the step will be:
1. add host function with Module, it will be like this
``` go
_, err := r.NewHostModuleBuilder("env").
ExportFunction("log_i32", func(params []uint64) ([]uint64, error){
	fmt.Println("log_i32 >>", int32(params[0]))
	return nil, nil
}).
ExportFunction("current_year", func(_ []uint64) ([]uint64, error) {
	if envYear, err := strconv.ParseUint(os.Getenv("CURRENT_YEAR"), 10, 64); err == nil {
		return []uint64{uint64(uint32(envYear))}, nil // Allow env-override to prevent annual test maintenance!
	}
	return []uint64{uint64(uint32(time.Now().Year()))}, nil
}).
Instantiate(ctx, r)
```

2. when compile, use reflect to judge the FunctionKind for whether it contain `context.Context` or `apt.Module`
3. when call wasm.CallGoFunc, get the FunctionKind, and use the `params []uint64` as one of the call param
4. call host function 

**Describe alternatives you've considered**
This raw solution can not check the signature of host function, It can be point out when write export function by user.

**Additional context**
-

**Comment by codefromthecrypt** [comment]
Thanks for raising this issue @hafeidejiangyou. I'm also wondering if we can do something about this. Perhaps we can attempt to cast the input to `func([]uint64) ([]uint64, error)` and skip reflection if so? It might require a different code path.

Would you be willing to try to prove the performance gain by making modifications on your fork in a way that the current and the optimized/raw approach can co-exist? Then update the below bench to show the results?

https://github.com/tetratelabs/wazero/blob/b01effc8a91f624c51ce09698d964b0b5b77819f/internal/integration_test/bench/hostfunc_bench_test.go

Note that this experiment is mainly to prove the point, and might need to change a little more if we decide to go forward on it.

**Comment by codefromthecrypt** [comment]
you can also consider the same signature as `api.Function`: `Call(ctx context.Context, params ...uint64) ([]uint64, error)` except note that sometimes you may also need to have a parameter for `api.Module` as that's how you access memory.

**Comment by codefromthecrypt** [comment]
done and released!
