### ISSUE TITLE
Enable/Disable Specific WASI Host Functions

### ISSUE THREAD

**Issue by ShivanshVij** [tetratelabs/wazero#824]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to run WASM modules that I don't necessarily trust - when I don't enable `WASI` this is straight forward, however there are a lot of modules (especially those compiled with `tinygo` with the target `-target=wasi`) that only need a subset of the `WASI` spec. 

Currently, Wazero requires me to enable all of the `WASI` host functions, or none of them.

**Describe the solution you'd like**
I would like to be able to enable `WASI` support using the `wasi_snapshot_preview1` package, and then disable certain host functions. Another option would be to selectively enable certain `WASI` functions using some sort of config file, and that would be a solid solution as well - though it will probably require more work. 

**Describe alternatives you've considered**
There doesn't seem to be any alternative path forward - save for using an alternative wasm runtime.

**Comment by ShivanshVij** [comment]
I've got a potential solution here: https://github.com/loopholelabs/wazero/commit/ed5fdbf3a02cbdbfdbb26a9d0cf6c115a0accf8c

**Comment by codefromthecrypt** [comment]
Hi, @ShivanshVij

So I'm curious about the approach of removing the imports because it is hard to control compilation of guests. Actually there is no access to anything by default even if the the functions are imported. That's because ModuleConfig controls the resources WASI (or otherwise) can access. I expect us to continue that path vs have 40+ settings because the issue applies to anything that accesses resource, not just snapshot01. Make sense?

**Comment by ShivanshVij** [comment]
Wait so @codefromthecrypt what happens if I want to run a wasm module that wants to open a socket? Will wazero allow it to open the socket?

**Comment by ShivanshVij** [comment]
That completely solves my problem - thank you!

**Comment by codefromthecrypt** [comment]
no worries. thanks for your interest and giving wazero a try!

**Comment by ShivanshVij** [comment]
We're actually building a new embedded function runtime (https://github.com/loopholelabs/scale-go) on top of wazero - I'd love to find some way to advertise wazero/give credit to the maintainers. Maybe even help out if there are issues that need tending to.
