### ISSUE TITLE
Interleaving wasm into wasm 

### ISSUE THREAD

**Issue by gedw99** [tetratelabs/wazero#831]
I am working on wasm and introspection with interactive programming patterns.

like the old “ debug and continue” feature you see in sone IDE’s 

So does a tone know how easy it is to join wasm into other wasm ?
For context, imagine a golang function being edited , where I can pick up he change to that function , compile it to wasm and interleave it into the current wasm. 

The values in and out of each function I hold on specialised stack which I can store and replay. Aka hydration. So I can probably I yet leave the wasm without restarting the wasm.

**Comment by codefromthecrypt** [comment]
we currently don't have a way to hot re-compile an existing wasm function. however a host function can do anything including dispatch to a function it can reload..

**Comment by mathetake** [comment]
This is out of scope and you can do anything with host functions as Adrian mentioned.
