### ISSUE TITLE
Optimize `wasm.executeConstExpression`

### ISSUE THREAD

**Issue by ckaznocha** [tetratelabs/wazero#835]
**Is your feature request related to a problem? Please describe.**
I've been doing a bit of profiling. I noticed while instantiating my wasm module, my program is spending a fair bit of time in [`wasm.executeConstExpression`](https://github.com/tetratelabs/wazero/blob/d108ce4c43c6a2062a5ac723c5635163c3a18645/internal/wasm/store.go#L535). Most of the time is spent creating a `*bytes.Reader`. The `*bytes.Reader` is created every time `wasm.executeConstExpression` is called however there are three code paths (`OpcodeRefNull`, `OpcodeVecV128Const`, and an implicit default) which do not use the `*bytes.Reader`.
<img width="1332" alt="Screenshot 2022-11-01 at 12 47 50" src="https://user-images.githubusercontent.com/1851985/199325507-836fd16b-fca9-45fa-9dcb-62b3b471e186.png">

**Describe the solution you'd like**
Only create a `*bytes.Reader` for code paths that use it.

**Describe alternatives you've considered**
Taking a look at a few of the `Decode{Numeric Type}` funcs that the `*bytes.Reader` gets passed to, it seems using an `io.Reader` or a `*bytes.Reader` is an unnecessary indirection. Passing a `[]byte` will eliminate the performance penalty and make for simpler code. All of these functions look to be under `internal` so changing their signatures should be safe.

**Additional context**
Happy to submit a PR!

**Comment by codefromthecrypt** [comment]
I agree that the best is to get rid of the reader entirely from this part. You got it right about internal.. that's why we use it!

There may be other functions that use leb etc which can also use a byte slice instead. If you see other opportunities for the same code pattern, please put it in the same PR.

Most of all, thanks for offering to help!

**Comment by mathetake** [comment]
#837
