### ISSUE TITLE
Provide a list of exports from an api.Module

### ISSUE THREAD

**Issue by clarkmcc** [tetratelabs/wazero#839]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to list all exported functions in an `api.Module`.

**Describe the solution you'd like**
wasmer has an [`Exports`](https://docs.rs/wasmer/latest/wasmer/struct.Exports.html#method.iter) type that allows you to iterate over all exported functions.

**Comment by codefromthecrypt** [comment]
oh interested .. we only exposed it on CompiledModule. Good point!

We should add the same on module

```go
	// ExportedFunctions returns all the exported functions
	// (api.FunctionDefinition) in this module keyed on export name.
	ExportedFunctions() map[string]api.FunctionDefinition

	// ExportedMemories returns all the exported memories
	// (api.MemoryDefinition) in this module keyed on export name.
	//
	// Note: As of WebAssembly Core Specification 2.0, there can be at most one
	// memory.
	ExportedMemories() map[string]api.MemoryDefinition
```
