### ISSUE TITLE
Make host functions available only to a single guest module

### ISSUE THREAD

**Issue by clarkmcc** [tetratelabs/wazero#840]
**Is your feature request related to a problem? Please describe.**
I'd like to have a single runtime run multiple different wasm modules that call out to multiple different host functions. Let's say that I have several wasm modules that call out to HTTP APIs via a host function. I want each module to use call-out to a different API endpoint, but I also don't want the modules to be able to pick which API endpoint they're going to call out to for security purposes.

**Describe the solution you'd like**
When initializing a new module, I'd like to be able to specify what host functions can be called from the guest module, rather than specifying that for the entire runtime (and all modules that run on the runtime).

**Describe alternatives you've considered**
I considered setting up a separate module namespace for each guest module, and then passing the ID of the namespace to the module, but then realized that bindings between host and guest via module names are determined at compile-time.

**Additional context**
I recognize that this might be a limitation of the wasm spec, but figured I'd throw it out anyways.

**Comment by codefromthecrypt** [comment]
To help me understand more, can you put in code why namespace wouldn't work for this? This would allow you to use a different host module instance for each guest, which can have any static policy inside.

https://github.com/tetratelabs/wazero/tree/main/examples/namespace

Another way is to initialize with a context value which your functions read. This could allow you not just the ability to indicate policy per module, but also per request.

**Comment by clarkmcc** [comment]
@codefromthecrypt I didn't see this namespace functionality. Let me dink around with this and see if it solves my problem. If it doesn't your context suggestion seems like a viable option as well. Having context plumbed through everywhere is really nice by the way. A great improvement.

**Comment by mathetake** [comment]
I believe now this should be done with multiple `wazero.Runtime` sharing a `wazero.CompilationCache`. Closing!
