### ISSUE TITLE
Too large offset for ADR

### ISSUE THREAD

**Issue by clarkmcc** [tetratelabs/wazero#847]
**Describe the bug**
I'm compiling a production wasm module that has many, very large regular expressions (around 9kb) and I'm getting the following error when compiling in debug mode only
```
error compiling wasm func[.<regex::exec::ExecNoSync as regex::re_trait::RegularExpression>::captures_read_at::hdbe37ea0d10b827b]: failed to compile: BUG: too large offset for ADR
```
In release mode, I'm not getting the same error
```
[profile.release]
lto = "thin"
opt-level = 's'
strip = "symbols"
```

**To Reproduce**
Sadly, the wasm module is a closed-source project. If it is helpful, I can try to come up with a reproduction, but I wanted to check if there was a quick answer first.

**Environment (please complete the relevant information):**
- Go version: go version go1.19 darwin/arm64
- wazero Version: v1.0.0-pre.3
- Host architecture: arm64
- Runtime mode: compiler

**Comment by codefromthecrypt** [comment]
looks like indeed this is a temporary limitation in the arm64 variant

```
		offset := targetNode.OffsetInBinary() - n.OffsetInBinary()
		if offset > math.MaxUint8 {
			// We could support up to 20-bit integer, but byte should be enough for our impl.
			// If the necessity comes up, we could fix the below to support larger offsets.
			return fmt.Errorf("BUG: too large offset for ADR")
		}
```

**Comment by codefromthecrypt** [comment]
hi @clarkmcc can you run off latest main? Curious how big an ADR offset you have in your wasm, as that's the main thing we need to consider.

**Comment by mathetake** [comment]
oh i didn't think there would be a real example to hit this branch... :D

**Comment by mathetake** [comment]
glad I captured this as an error rather than horrible runtime crash though!

**Comment by clarkmcc** [comment]
I'm having trouble replicating 🙄. I should have set aside that compiled version for further troubleshooting. If I can figure out how to replicate it, I'll post results.

**Comment by mathetake** [comment]
my memory on this has gotten fuzzy so I'm not sure too, but I imagine a huge `br_table` branch might cause this, but yeah not sure

**Comment by mathetake** [comment]
In anyway I don't think we need a reproducer, and we can simply change the encoding of `ADR` instruction https://github.com/tetratelabs/wazero/blob/main/internal/asm/arm64/impl.go#L1844-L1857 here and can add support for maximum 20-bit offset.

**Comment by mathetake** [comment]
here's a quick patch, but haven't gotten around to test it https://github.com/tetratelabs/wazero/pull/851

**Comment by mathetake** [comment]
@clarkmcc could you try the branch in the PR #851?
