### ISSUE TITLE
Ideas for reducing heap memory usage

### ISSUE THREAD

**Issue by anuraaga** [tetratelabs/wazero#889]
As discussed on Slack, I was debugging a problem that runs into GC performance limits in low-CPU environments with Go's default settings. Go's settings can be tweaked and there will likely always be some patterns of usage that stress allocations and will require tweaking e.g. `GOMEMLIMIT`, in these cases, but it could still be possible to reduce GC to lower the chance of this happening or possibly enabling applications to perform better in general. These are just ideas, and may not be good ones.

The ideas come from running this test with memory profiler. I do this by loading in GoLand and hitting the green play button, selecting run with memory profiler.

https://github.com/anuraaga/re2-go/blob/main/exec2_test.go#L19

It is instantiating several million regex's, each instantiating and closing a wasm module. The module has about 2K functions and uses 3 wasm pages of memory.

### Function table

A huge number of the objects are `&function{}` and `&functionInstance`, allocated at these two locations (about 50/50 between the two)

https://github.com/tetratelabs/wazero/blob/main/internal/engine/compiler/engine.go#L543
https://github.com/tetratelabs/wazero/blob/main/internal/wasm/module.go#L609

The instances are always stored into a slice from what I can tell - I wonder if it would be possible to use contiguous slice, e.g. `[]function` instead of pointer slice, e.g. `[]*function` for these. If it is possible, it could dramatically reduce the number of heap objects while still accessing everything through the memory in these slices.

This would definitely make the code more fragile - most likely most logic operations will still need to work on pointer of function, with the goal being for those pointers being into a contiguous slice of memory. It can be easy in such a style to accidentally not use a pointer and break things mysteriously.

Objects:
![image](https://user-images.githubusercontent.com/198344/205823452-3acefda2-d5a3-4453-938a-7ac3d8cc4c9c.png)

### Module memory

The number of objects for memory was very low while the number of bytes is high - for context, the number of bytes in memory objects is about equal to the number of bytes in function objects (which, to me, was surprising, I didn't expect the function objects to be taking so much space but I guess it adds up). I'm not sure how Go's GC performs with respect to number of objects and bytes of objects, both should matter but I think generally GC's are more affected by the number. So optimizing module memory may not have as big an impact as function table.

But one idea is to use a `sync.Pool` for `memory.Buffer`. This would not be as big of a refactoring as the function table change proposed, so I did give it a simple try. Performance went down quite a bit in the general case, I didn't do detailed profiling of it but presume zeroing out the reused buffer on the hot path is not as efficient as letting the GC take care of it. So this may not be practical anyways, but just putting it for the record.

Space:
![image](https://user-images.githubusercontent.com/198344/205823497-f8fd04ab-edbe-4633-8051-2a6d44d614c0.png)

### Call stack

A call stack is allocated every time `ExportedFunction` is called

https://github.com/tetratelabs/wazero/blob/main/internal/engine/compiler/engine.go#L835

I don't know if it's common, but I tend to call `ExportedFunction` a lot to cache the call engines for the many functions in a module.

https://github.com/anuraaga/re2-go/blob/main/re2_wazero.go#L31

Because wasm functions cannot be called in parallel, I wonder if it's possible for the allocated stack to be only once for the module instead of per exported function?

**Comment by codefromthecrypt** [comment]
@anuraaga to clarify as I'm still intermediate level at go, I think "Function table" section is saying move from heap to stack allocation (assuming these things aren't stateful and safe to copy a lot). Is that right? Is there any limitations you foresee in the same env with stack allocation? ;)

**Comment by anuraaga** [comment]
@codefromthecrypt Ah nah don't quite mean that - the slice's backing array is still on the heap, so it means the data of those structs is packed into that contiguous backing array, rather than it being an array of pointers, each to random places in memory. i.e., `make(function, 10)` has a backing array of size `10*sizeof(function{})` with everything inside, while `make(*function, 10)` has size 80 bytes (8 byte per pointer), with each function living somewhere else in memory and the pointers being in the slice.

So AFAIK, there wouldn't be any stack allocations or such that could have a performance tradeoff from the scheme as it's still all memory that can have pointers, just the memory happens to be in one contiguous block. But then we have potential for the aforementioned fragility, it becomes much easier to create code that compiles but used a non-pointer (and therefore copied, and therefore doesn't update the real memory on mutation when intended) and then fails at runtime mysteriously. I think so anyways.

**Comment by anuraaga** [comment]
Came up with an implementation of the idea for function table that isn't that invasive

https://github.com/tetratelabs/wazero/compare/main...anuraaga:less-function-heap-objects?expand=1

It's not optimal, theoretically you shouldn't need two slices, a storage slice and pointer slice, and instead just make sure all pointers in the program are to the storage slice. But the diff size is small, and more importantly it doesn't seem to have the caveat that I mentioned of accidentally accessing a function as a struct copy instead of through pointer - the non-pointer access is hidden away as a function local variable.

Would need microbenchmarks to track better, but just trying out `TestRE2Exhaustive` on my mac normally, the runtime went from ~2m20s to ~1m50s. And the memory profiles do show those objects all gone, and a more spread out profile in general without anything dominating on the object-count front.

If the approach seems reasonable, could try to clean up with more benchs and send out.

**Comment by anuraaga** [comment]
By the way, edited my first comment with a third idea that came to mind after seeing the cleaned up memory profile after the above. Don't think it's as impactful but intuitively seems like it shouldn't be a hard optimization.

**Comment by codefromthecrypt** [comment]
@anuraaga your change looks fine. As we rarely use structs that aren't pointers, in your cleanup add a comment why it isn't, so it isn't "fixed" later. thanks for the help!

**Comment by mathetake** [comment]
but yeah as a temporary change looks fine, so please leave a TODO on making moduleEngine.Functions to `[]function`

**Comment by anuraaga** [comment]
@mathetake Haha yeah my first attempt at trying that looked like I would hit my limit quickly :P Ok the TODO sounds good
