### ISSUE TITLE
Document wazero architecture

### ISSUE THREAD

**Issue by codefromthecrypt** [tetratelabs/wazero#931]
Right now, there's no document covering the architecture of wazero, and leaving implicit assumptions slows engagement on how to proceed certain topics, and above all an understanding of what's in the box.

We should have maybe on the website, a page for wazero architecture. It should have diagrams, so if we do it on the website we can use the stuff we render in Hugo.

Here are some notes I made when @Xe asked today

compiledmodule has the static stuff, including function bytes and the intermediate representation. compiled module is mmapped and reused for each instance of it

instantiated module has in its scope a memory (or imported) table etc. and the parts needed to satisfy wasi (rng etc assigned with ModuleConfig or defaulted) generally we have a XXXInstance type for things in the instantiated module

there's an even smaller scope for function call graphs called "call engine"

**Comment by mathetake** [comment]
will work on it in a few days
