### ISSUE TITLE
Support wazero.Namespace with gojs

### ISSUE THREAD

**Issue by robbertvanginkel** [tetratelabs/wazero#939]
**Is your feature request related to a problem? Please describe.**
I'd like to be able to run multiple wasm modules concurrently and ideally have them share the compilation cache. I noticed that the docs indicate that a cache directory should only be accessed by a single runtime, but that runtime has the concept of `wazero.Namespaces` to instantiate and execute independent wasm modules without conflict.

I've figured out how to do this with `wasi_snapshot_preview1`, where I can build the wasi module with a runtime and Instantiate it into multiple namespaces:
```
var r wazero.Runtime
var config wazero.ModuleConfig
var module wazero.CompiledModule

ns := r.NewNamespace(ctx)
defer ns.Close(ctx) // todo: errcheck

// wasi_snapshot_preview1
if _, err := wasi_snapshot_preview1.NewBuilder(r).Instantiate(ctx, ns); err != nil {
	return err
}
_, err = ns.InstantiateModule(ctx, module, config)
```

However for `gojs`, there's only a `Run()` method which requires a `wazero.Runtime`:
```
// gojs
err = gojs.Run(ctx, r, module, config) // can't use a ns
```

**Describe the solution you'd like**
gojs to have a similar builder interface, and support instantiating the module into a namespace:
```
if _, err := gojs.NewBuilder(r).Instantiate(ctx, ns); err != nil {
	return err
}
_, err = ns.InstantiateModule(ctx, module, config)
```

**Describe alternatives you've considered**
I currently have a mutex around my usage of  `gojs.Run`, which isn't great but does the job for now :). Alternatively I could create new runtimes for each gojs call, but not sharing compilation cache is a big downside.

**Additional context**
Looking at the code for gojs, I think it should be possible to give it an api surface similar to `wasi_snapshot_preview1` to allow using it with namespaces? This would entail some breaking changes (or just new APIs?) so I figured I'd open an issue to ask if making `gojs` support usage like `wasi_snapshot_preview1` makes sense before I look at making a PR!

**Comment by codefromthecrypt** [comment]
Good idea.

Note: namespace doesn't allow inheriting modules from the runtime, which means you have to instantiate the host functions each time. I think the following change would do the trick. Want to try and raise a PR if appropriate?

```diff
diff --git a/imports/go/gojs.go b/imports/go/gojs.go
index 4d5a7eb8..770ae920 100644
--- a/imports/go/gojs.go
+++ b/imports/go/gojs.go
@@ -62,15 +62,19 @@ func WithRoundTripper(ctx context.Context, rt http.RoundTripper) context.Context
 //     Use experimental.WithCompilationCacheDirName to improve performance.
 //   - Both the host and guest module are closed after being run.
 func Run(ctx context.Context, r wazero.Runtime, compiled wazero.CompiledModule, config wazero.ModuleConfig) error {
+       // Use a namespace so that this can be executed multiple times in the same runtime.
+       ns := r.NewNamespace(ctx)
+       defer ns.Close(ctx)
+
        // Instantiate the imports needed by go-compiled wasm.
-       js, err := hostModuleBuilder(r).Instantiate(ctx, r)
+       js, err := hostModuleBuilder(r).Instantiate(ctx, ns)
        if err != nil {
                return err
        }
        defer js.Close(ctx)
 
        // Instantiate the module compiled by go, noting it has no init function.
-       mod, err := r.InstantiateModule(ctx, compiled, config)
+       mod, err := ns.InstantiateModule(ctx, compiled, config)
        if err != nil {
                return err
        }
```

**Comment by codefromthecrypt** [comment]
another way would be to not use a namespace and instead instantiate the host functions into the runtime. This would lead to name conflicts when instantiating the guest, so a unique name must be supplied per run. The main reason to do this would be to reduce instantiation cost of the host functions which may not matter because in general the overhead is high on gojs. TL;DR; I think the above diff might be the easiest and best way, but there is another.

**Comment by codefromthecrypt** [comment]
actually we could just use an atomic number for the module name, so we could hide it..

@robbertvanginkel if this worked without namespaces would you prefer it? 

ex. MustInstantiateGoJS, then gojs.Run (which internally dodges conflict by module name)

**Comment by codefromthecrypt** [comment]
I think making this work like the other imports (ex wasi or assemblyscript) is the best way out. I'll raise a PR in the next day or two. Thanks for raising the issue!

**Comment by robbertvanginkel** [comment]
#940 did indeed fix it for me, thanks and amazing turn around time! 🎉 Having a consistent `NewFunctionExporter`/`Instantiate` interface for all the wasi/gojs/assemby/emscripten imports is very helpful.

One thing to note that when I upgraded from 0dde445074fd to 1f7f20ee2fec this morning, compilations seemed to hang indefinitely with compilation cache until I cleared out the cache dir. If its worth looking into I can see if I can make a minimum reproducible example, but since it's an experimental package and things seem to be moving quickly before the 1.0 I'll defer to you if its something worth looking into more. Let me know!

**Comment by codefromthecrypt** [comment]
@robbertvanginkel thanks for the feedback quick on how to make things better. we really want to get to 1.0 in feb, so it matters a lot.

So, on the cache dir that's interesting. unless go.mod has a replace directive, it should invalidate each commit  https://github.com/tetratelabs/wazero/blob/7f8e629c653f548a6e43d4ec71d798fba4a72761/internal/version/version.go#L14

If you find something wrong and can repro please open another issue!
