### ISSUE TITLE
Is it possible to use host memory in wasi?

### ISSUE THREAD

**Issue by raifpy** [tetratelabs/wazero#943]
Is there any way to share same memory with wasi. Not buffer. Or, can I share my object via pointer with unsafe.Pointer?
Thank you very much!

**Comment by codefromthecrypt** [comment]
are you interested to have wasm move your object around between host functions, or are you interested in wasm reading fields of your object? If the latter you can look at https://karmem.org and https://github.com/knqyf263/go-plugin

If the former, it would require the compiler to support "funcref/externref" which is rarely the case.  If the above doesn't help, maybe elaborate in code the example you want to do and which compiler you are using (tinygo, ...).

**Comment by raifpy** [comment]
I was looking a way to convert setted from host, reading by wasi, or opposite way. 
![image](https://user-images.githubusercontent.com/50047969/208712974-c271bf15-5b9d-4656-b0bd-725d5166ade1.png)
```
.
.
.
achable�
                                               deadlocked: no event sourcetinygo-wasiHello from WASI!��l ��
                                                                                                           �C�C�
����pC\�C
         �pC�C��u�;�i���������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������je����������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
 len: 131072

```

Maybe It could be with converting linear memory buffer's pointer to Object. However my issue is not purpose of wasm.
It look like Karmem very good library to share information between host and wasm. go-plugin is also awesome! But I have a plan to use different languages. Thanks for your reply!

**Comment by codefromthecrypt** [comment]
the short answer is that trying to share host memory like this is complicated and slow, so not recommended. karmem in a polyglot alternative, which more efficiently uses wasm memory.

sharing host memory is currently implemented in gojs https://github.com/tetratelabs/wazero/blob/main/internal/gojs/syscall.go#L406 To do this properly requires reference tracking on both sides (you'll see "ref" a lot in the impl). This is very slow and complicated, but works. I wouldn't recommend doing an ad-hoc version of this.

a more standard way could be to use an externref of whatever you are sharing from the host, but compilers don't really support that either. https://github.com/tetratelabs/wazero/issues/544

I would recommend either doing something like karmem or making your own sdk/abi similar to https://http-wasm.io/ which defines the host model explicitly and copies fields as needed.

**Comment by mathetake** [comment]
I believe this is answered by @codefromthecrypt, not actionable I think. Closing.
