### ISSUE TITLE
fclose <stdin>: Bad file descriptor

### ISSUE THREAD

**Issue by vyskocilm** [tetratelabs/wazero#953]
**Describe the bug**
I experiment with userland unix in Go and your project looks like a perfect match allowing me to run a unix utilities. After I build a few of them and tested them, I have noticed the `fclose <stdin>: Bad file descriptor` appeared. It happens for `os.Stdin`, `bytes.Buffer` or the `*io.PipeReader`. The `io.NopCloser` has no effect there. So I believe this is nothing to do with Go, but with the wasi integration of `fclose`.

**To Reproduce**
A small C reproducer

```c
#include <stdlib.h>
#include <stdio.h>

int main() {
    int ret = fclose(stdin);
    if (ret != 0) {
        perror("fclose <stdin>");
    }
    exit(ret);
}
```

To wasm - `zig cc --target=wasm32-wasi fclose.c -o fclose.wasm`

Run it via this program

```go
//go:embed testdata/fclose.wasm
var fcloseWasm []byte

func main() {
	ctx := context.Background()
	if err := run(ctx); err != nil {
		log.Fatal(err)
	}
}

func run(ctx context.Context) error {
	r := wazero.NewRuntime(ctx)
	defer r.Close(ctx)

	config := wazero.NewModuleConfig().
		WithStdin(io.NopCloser(os.Stdin)).
		WithStdout(os.Stdout).
		WithStderr(os.Stderr)
	wasi_snapshot_preview1.MustInstantiate(ctx, r)

	code, err := r.CompileModule(ctx, fcloseWasm)
	if err != nil {
		return err
	}

	if _, err = r.InstantiateModule(ctx, code, config.WithArgs("wasi")); err != nil {
		if exitErr, ok := err.(*sys.ExitError); ok && exitErr.ExitCode() != 0 {
			fmt.Fprintf(os.Stderr, "exit_code: %d\n", exitErr.ExitCode())
			return err
		} else if !ok {
			return err
		}
	}
	return nil
}
```

```sh
go run main.go 
fclose <stdin>: Bad file descriptor
exit_code: 4294967295
2022/12/21 09:13:07 module "" closed with exit_code(4294967295)
exit status 1
```

**Expected behavior**
The stdin is closed, no error message appear and exit code is 0.

**Screenshots**

**Environment (please complete the relevant information):**
- Go version: go1.19.1 linux/amd64
- wazero Version: github.com/tetratelabs/wazero v1.0.0-pre.5
- Host architecture: amd64
- Runtime mode: compiler

**Comment by codefromthecrypt** [comment]
ack this is a bug as we special case stdio in ways we shouldn't. e.g. they are pre-opened but not (yet) closable. Thanks for the report!
