### ISSUE TITLE
gojs: memory out of bounds

### ISSUE THREAD

**Issue by robbertvanginkel** [tetratelabs/wazero#978]
**Describe the bug**
When reading a sizeable chunk of data (2mb+) from `os.Stdin` using `io.ReadAll` in a go program compiled for gojs, wazero errors with the following stacktrace:

```
wasm error: out of bounds memory access
wasm stack trace:
        .runtime_internal_atomic.Loaduintptr(i32) i32
        .runtime.__gcBitsArena_.tryAlloc(i32) i32
        .runtime.newMarkBits(i32) i32
        .runtime.__mheap_.allocSpan(i32) i32
        .runtime.__mheap_.alloc.func1(i32) i32
        .runtime.systemstack(i32) i32
        .runtime.__mheap_.alloc(i32) i32
        .runtime.__mcache_.allocLarge(i32) i32
        .runtime.mallocgc(i32) i32
        .runtime.growslice(i32) i32
        .io.ReadAll(i32) i32
        .wasm_pc_f_loop()
        .wasm_export_run(i32,i32)
```

**To Reproduce**
A minimal testcase in my wazero fork: https://github.com/robbertvanginkel/wazero/commit/3b222eed7e890cb3e78ef4d030feebb56dcfbb54. Happy to submit as a pr to if it helps as starting point.

**Expected behavior**
No out of bounds memory access error. Maybe an error indicating memory has hit a limit on grow.

**Screenshots**
N/A

**Environment (please complete the relevant information):**
- Go version: go1.19.3
- wazero Version: 62be68dfc5f477d766d9dcfe422dcfc498c7bbfd
- Host architecture: arm64/amd64 (tried both)
- Runtime mode: compiler

**Additional context**
I suspect it may have something to do with
https://github.com/tetratelabs/wazero/blob/5751bd758cf0adab76d212e337ba256e4ac4247c/internal/gojs/runtime.go#L56-L57
(and its referenced https://github.com/tetratelabs/wazero/issues/601)?

**Comment by codefromthecrypt** [comment]
I'll take a look at this prior to the version cut-off for the month. thanks for the repro!

**Comment by codefromthecrypt** [comment]
ps on this.. I'll not ignore it, but it shouldn't have anything we need to do as we aren't caching a memory view anywhere and don't currently support any user defined functions that might.

```
 // TODO: Compiler-based memory.grow callbacks are ignored until we have a generic solution #601 
 var ResetMemoryDataView = goarch.NoopFunction(custom.NameRuntimeResetMemoryDataView) 
```

**Comment by codefromthecrypt** [comment]
oh.. but maybe reslicing could cause a problem! We aren't doing safe copy on data kept in the values cache. I'll look into it either way.

**Comment by codefromthecrypt** [comment]
right now @mathetake is out on holiday, but I was able to get interpreter to pass after this change. Once he's back, maybe it will be quick to sort. This may not make the version tomorrow, due to this, but it seems you have been accustomed to working off main anyway. In any case thanks a lot! https://github.com/tetratelabs/wazero/pull/980

**Comment by codefromthecrypt** [comment]
@robbertvanginkel we're still not at the bottom of it, but you may be able to use a work-around for now. It seems related to wasm allocation vs I/O. https://github.com/tetratelabs/wazero/pull/980#issuecomment-1368134697

**Comment by robbertvanginkel** [comment]
Appreciate the detailed look into it! Working off of main isn't a problem for me now indeed, and I'll give the workaround a try. 

For my use case (protoc plugins, an existing executables+stdio based plugin platform) most code won't assume to know the buffer sizes up front, but could probably work around that if really needed to. Reading the other comments I'll see if nodejs actually runs this go/js wasm without issue, tbh I hadn't tried that to validate.
