### ISSUE TITLE
Suggestion:  enable discussions on this repo

### ISSUE THREAD

**Issue by lthibault** [tetratelabs/wazero#994]
I've noticed that many issues (including some of my own) are not signaling problems with the Wazero codebase, but instead questions for the community to the effect of "how do I do X?" or "is feature Y supported?".

I think it would be helpful to enable the [discussions](https://github.com/tetratelabs/wazero/discussions/landing) feature on this repository for such interactions.  In addition to keeping code issues and developer support separate, the discussions feature has the benefit of facilitating search.

**Comment by codefromthecrypt** [comment]
We currently do a lot of chat on #wazero and #wazero-dev channels on [gophers slack](https://gophers.slack.com/), which is searchable, but not as linkable or searchable here. Knowing that, are you still interested in discussions? Regardless, I think we need to update our issue template.

Note: You may need an [invite](https://invite.slack.golangbridge.org/) to join gophers.

**Comment by lthibault** [comment]
Oh, brilliant.  See you there!

**Comment by mathetake** [comment]
We could update the issue template and put the GopherSlack info there

**Comment by mathetake** [comment]
now that we have provided the gopher slack info in the website https://wazero.io/community/#keeping-up-to-date I think we could close this.
